- datanode/limit_test.go
Make the first simple attempt, add datanode/limit.go unit test
Signed-off-by: jjyaoao jjyaoao@126.com
#1903
NONE
```release-note
```
> test(datanode): add limit.go unit test

- docs-zh/source/deploy/k8s.md
- docs/source/deploy/k8s.md
> doc(fix): fix typo in Kubernetes deployment

- docs-zh/source/faq/kafka.md
- docs-zh/source/sidebarConfig.js
- docs/source/faq/kafka.md
- docs/source/sidebarConfig.js
docs(faq): add kafka consumption issues
> docs(faq): add kafka consumption issues

- blobstore/cli/clustermgr/background.go
- blobstore/cli/clustermgr/clustermgr.go
- docs-zh/source/maintenance/admin-api/blobstore/cm.md
- docs-zh/source/maintenance/tool.md
- docs/source/maintenance/admin-api/blobstore/cm.md
- docs/source/maintenance/tool.md
Support new feature requested in issue #1898 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1898 
```release-note
- `blobstore-cli` now support `enable` or `disable` background task switches
```
> [Feature]: The blobstore-cli supports setting background task switch #1898

- build/build.sh
> fix: add blobstore proxy build

- blobstore/cli/app.go
- client/fs/super.go
- libsdk/libsdk.go
- metanode/partition.go
- objectnode/server.go
- preload/sdk/preloadsdk.go
- sdk/data/blobstore/blobstore_client.go
- sdk/data/blobstore/blobstore_client_test.go
- sdk/data/blobstore/writer_test.go
using local module of blobstore
close: #1527
> build: cubefs using local module of blobstore

- GOVERNANCE.md
- MAINTAINERS.md
chore(GOVERNANCE): add committer role
> chore(GOVERNANCE): add committer role

- .github/workflows/ci.yml
- docker/Dockerfile
- docker/docker-compose.yml
- docker/run_docker.sh
- docker/script/run_format.sh
put rocksdb's libs into the docker image, avoid download file error
> build: put rocksdb libs into the docker image

- blobstore/clustermgr/svr.go
- blobstore/clustermgr/volumemgr/volumemgr_test.go
- blobstore/proxy/allocator/volumemgr.go
1. support 3-az module register to consul
2. fix the test case close db while background exec finish create volume task
> support 3-az module register to consul

- docs-zh/source/user-guide/objectnode.md
- docs/source/user-guide/objectnode.md
fix the sample use of objectnode  user-guide
> fix(docs): fix objectnode user-guide

- README.md
> chore(README): add contributors

- client/fs/dir.go
- client/fuse.go
- datanode/server.go
- docker/conf/physical_client.json
- docker/docker-compose-ci.yml
- master/api_service.go
- master/cluster.go
- master/config.go
- master/data_partition.go
- master/data_partition_check.go
- master/http_server.go
- master/master_manager.go
- master/meta_partition.go
- master/metadata_fsm.go
- master/metadata_fsm_op.go
- master/monitor_metrics.go
- master/server.go
- master/topology.go
- master/vol.go
- metanode/const.go
- metanode/metanode.go
- proto/admin_proto.go
- raftstore/store_rocksdb.go
- sdk/data/wrapper/wrapper.go
- sdk/master/api_admin.go
- sdk/master/api_client.go
- sdk/master/client.go
- sdk/master/name_resolver.go
- shell/tpl/master.tpl
During the development of version 3.3.0, some stability-related issues were discovered and have been fixed, and the fixes need be synchronized to version 3.2.1.
>  stability-related issues have been fixed and merged into  3.2.1

- docs-zh/source/overview/architecture.md
> [doc] : update architecture.html in the ‘doc-zh’ directory

- blobstore/Dockerfile
- blobstore/run.sh
- blobstore/run_docker.sh
- blobstore/start_docker.sh
>  fix(deploy): fix blobstore docker deploy

- cli/cmd/cluster.go
- docs-zh/source/maintenance/tool.md
- docs/source/maintenance/tool.md
improve documentation of cli tool
I originally intended to add documentation for #1943, but later discovered that there were many missing parts in this area, so I decided to add them all together.
> docs(cil): improve documentation of cli tool

- datanode/limit_test.go
* There are some unreachable codes in `limit_test.go`.
* This pull request fix the problem.
#1903
```release-note
```
> test(datanode): fix limit_test.go unit test

- objectnode/api_handler_multipart.go
**this PR fixes #2077  issue**
> ObjectNode UploadPart Interface compares the Content-Md5 with the body checksum.

- docs-zh/source/maintenance/configs/blobstore/scheduler.md
- docs/source/maintenance/configs/blobstore/scheduler.md
add config `message_punish_threshold` and `message_punish_time_m` for blob delete and shard repair task
> docs(config): add punishment docs for blob delete and shard repair

- client/fuse.go
- proto/mount_options.go
close: #2080
start 
to close issue #2080, client listen locally.
> enhance(client): client pporf only be access by local request for safety

- master/api_service.go
In `master/api_services.go`, there are many codes that send an error response and then do not return.
This pull request fix them.
fixes #2084 
```release-note
```
> fix(master): fix #2084

- build/build.sh
> fix: snappy not supported in rocksdb

- .github/workflows/ci.yml
- codecov.yaml
make informational codecov when pull master
> chore(codecov): make informational codecov when pull master

- cli/cmd/fmt.go
- cli/cmd/quota.go
- client/fs/dir.go
- client/fs/file.go
- master/api_args_parse.go
- master/api_service.go
- master/http_server.go
- master/master_quota_manager.go
- master/vol.go
- metanode/meta_quota_manager.go
- proto/fs_proto.go
- proto/meta_proto.go
- sdk/master/api_admin.go
- sdk/meta/view.go
close: #2087
Added multi-directory federation quota
> enhance(master/cli): Added multi-directory federation quota

- cli/cmd/fmt.go
- cli/cmd/metapartition.go
- master/api_service.go
- master/cluster.go
- master/cluster_task.go
- master/meta_partition_manager.go
- proto/model.go
- sdk/meta/meta.go
enhance(cli,client):1. add check inode max mp check 2.client return err
> enhance(cli,client):1. add check inode max mp check 2.client return err

- metanode/txid_allocator_test.go
add txid_allocator.go unit test
Signed-off-by: jjyaoao [jjyaoao@126.com](mailto:jjyaoao@126.com)
#1903
NONE
```release-note
```
> test(metanode): add txid_allocator.go unit test

- README.md
Since the list of contributors is already available on the homepage, it has been removed from the readme.
> chore(README): remove contributors

- datanode/wrap_operator.go
> fix(datanode): add extent count limit when create extent

- objectnode/auth_test.go
add auth.go unit test
Signed-off-by: jjyaoao [jjyaoao@126.com](mailto:jjyaoao@126.com)
#1903
NONE
```release-note
```
> test(objectnode): add auth.go unit test

- datanode/stat_test.go
test(datanode): add stat.go unit test
Signed-off-by: jjyaoao [jjyaoao@126.com](mailto:jjyaoao@126.com)
#1903
NONE
```release-note
```
> test(datanode): add stat.go unit test

- cli/cmd/acl.go
- cli/cmd/cluster.go
- cli/cmd/compatibility.go
- cli/cmd/config.go
- cli/cmd/datanode.go
- cli/cmd/datapartition.go
- cli/cmd/disk.go
- cli/cmd/metanode.go
- cli/cmd/metapartition.go
- cli/cmd/root.go
- cli/cmd/uid.go
- cli/cmd/user.go
- cli/cmd/valid.go
- cli/cmd/vol.go
- cli/cmd/zone.go
Some error messages cannot be displayed correctly:
> feat(cli): add newline in errouts && give suggestions when root command not found 

- cli/cmd/quota.go
- master/master_quota_manager.go
- master/meta_node.go
- metanode/partition_op_quota.go
- sdk/meta/view.go
close: #2107
1.create quota dir without / without error.
2.Create quota with the same directory error message optimization
3.A single quota increases the directory limit to 5
4.Creating a quota, the scene of multiple directories shows that the number of used files is incorrect
5.list quota Sort by quotaId from small to large
> fix(master,cli): Multi-directory quota problem optimization

- blobstore/scheduler/blob_deleter.go
> chore(scheduler): remove log of start delete msg

- objectnode/api_middleware.go
- objectnode/cors_handler.go
- objectnode/fs_volume.go
- objectnode/fs_volume_meta.go
- vendor/golang.org/x/sync/singleflight/singleflight.go
fix  bucket metadata cache synchronization bug
fixes #2106
> fix(objectnode): bucket metadata cache synchronization

- storage/extent_store.go
Signed-off-by: 李艳坤 <liyankun01@58.com>
```release-note
```
> storage: print Error info about loading extent

- client/fuse.go
- libsdk/libsdk.go
> refactor(client): remove local code.

- cli/cmd/vol.go
- datanode/server.go
- master/api_service.go
- metanode/const.go
- metanode/metanode.go
- proto/transaction.go
- sdk/master/client.go
- sdk/master/name_resolver.go
- sdk/meta/api.go
- sdk/meta/operation.go
enhance: add name resolver for master sdk
fix(cli,sdk): 1.fix tx display bug in cli. 2.fix tx request retry bug
> enhance: add name resolver for master sdk

- metanode/partition_op_quota.go
- metanode/partition_store.go
- sdk/data/stream/extent_client.go
close: #2137
fix(metanode): Unmarshal quotaInfo error
> fix(metanode): Unmarshal quotaInfo error

- docs-zh/source/community/article.md
- docs/source/community/article.md
Add recent official account articles
> docs: Add recent official account articles

- docs-zh/source/maintenance/configs/blobstore/scheduler.md
- docs/source/maintenance/configs/blobstore/scheduler.md
- perfect configuration example
> docs(scheduler): perfect configuration example

- metanode/const.go
- metanode/partition_fsm.go
- metanode/partition_item.go
for mp leader send snapshot to follower:
(1) add cursor in snapshot;
(2) when apply snapshot, return error if snapshot format not match;
fixes #2149
return error if snapshot format not match when apply snapshot, so need to think carefully about compatibility issues of upgrading.
> feat(metanode): for mp leader send snapshot to follower:

- blobstore/access/controller/service.go
- blobstore/access/controller/service_test.go
try last service host even if all were punished
> feat(access): try last service host even if all were punished

- blobstore/proxy/allocator.go
- blobstore/proxy/allocator/volume.go
- blobstore/proxy/allocator/volumemgr.go
- blobstore/proxy/allocator/volumemgr_test.go
fix proxy dead lock problem in alloc stage
> fix(proxy): fix proxy dead lock problem in alloc stage

- cli/cmd/const.go
- cli/cmd/quota.go
close: #2171
fix：1.No error reported when creating quota using multiple directories with the same name
2.Deleting quota without revoking it first will cause directories to be undeletable
> fix(cli): Fix 2 quota related issues

- blobstore/blobnode/base/limitio/util_test.go
> test(blobnode): add unit test

- blobstore/api/blobnode/iostat.go
- blobstore/api/blobnode/iostat_test.go
- blobstore/blobnode/base/flow/iostat.go
- blobstore/blobnode/core/chunk/compact.go
- blobstore/blobnode/core/disk/chunkinspect.go
- blobstore/blobnode/core/disk/disk.go
- blobstore/blobnode/core/storage/datafile.go
- blobstore/blobnode/datainspect.go
- blobstore/blobnode/db/metadb.go
- blobstore/blobnode/shard.go
> fix(blobnode): modify camel case

- blobstore/common/rpc/lb.go
fix the problem that the body returned last time was not closed before retrying
> fix(rpc): fix the problem that the body returned last time was not closed before retrying

- metanode/manager_op.go
- metanode/transaction.go
- proto/transaction.go
transaction need consider repeat commit or else return error while network not stable between client and server
> transaction need consider repeat commit or else return error while network not stable between client and server

- metanode/transaction.go
deadlock happend while process expired transactions
> fix(metanode_tx): deadlock happend while process expired transactions

- master/api_args_parse.go
- master/cluster.go
- master/metadata_fsm_op.go
- metanode/manager_op.go
- metanode/partition.go
- metanode/partition_op_extent.go
- metanode/transaction.go
- metanode/transaction_test.go
- proto/admin_proto.go
- proto/transaction.go
- sdk/meta/api.go
- util/exporter/exporter_test.go
- util/synclist/synclist_test.go
fix bug and add test to transaction expirition check process
1)fix(transcation):tx expire check goroutine may start multi times on parrallel
2)test(metanode_transaction): processExpiredTransactions may run mulit times on parrallel if leader change frequncey
3)feat(transaction):enable pause transaction including the expire process process in metanode
> fix bug and add test to transaction expirition check process

- cli/cmd/quota.go
- client/fs/dir.go
- metanode/const.go
- metanode/manager_op.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_quota.go
- proto/fs_proto.go
- sdk/meta/api.go
- sdk/meta/operation.go
close: #2189
1.Subdirectories under the quota directory cannot be moved 2.After creating the quota, delete the quota root directory and create it again, but the apply still succeeds 3.Multi-level directory setting quota report does not has only one / 4.2000w directory file after the quota is created apply error
> fix(master/metanode/cli): Fix the following bugs

- docs-zh/source/maintenance/tool.md
Add directory quota related usage documents
> doc: Add directory quota related usage documents

- metanode/api_handler.go
- metanode/partition.go
- metanode/partition_op_transaction.go
- metanode/transaction_test.go
- proto/fs_proto.go
Support transaction information query, facilitate online problem location
> feat(transaction): add get tx info handle to metanode

- sdk/meta/operation.go
retry logic have no times limitation while get tx conflict from mp
> fix(client.transaction):retry logic have no times limitation while get tx conflict from mp

- build/build.sh
- build/cgo_env.sh
adapt clang compiler
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2199 
```release-note
```
> fix: adapt clang compiler

- cli/cmd/quota.go
- client/fs/dir.go
- master/master_quota_manager.go
- proto/fs_proto.go
- sdk/meta/api.go
#2204 
fix two bugs：
1.Directory nesting issues with different quotas
2.root directory not checked out for nesting
> fix(cli,master): Fixed 2 bugs related to quota

- README.md
> docs(readme): show code coverage in readme

- docker/Dockerfile
copy go bin to docker when build docker image.
> build(docker): copy go bin to docker

- build/build.sh
- master/api_service_test.go
- master/cluster_test.go
- master/id_allocator_test.go
- master/meta_node_test.go
- master/topology_test.go
* Add `IDAllocator` unit tests.
* Fix `TestBalanceMetaPartition` unit test.
#1903 
```release-note
```
> test(master): add `IDAllocator` test and fix `TestBalanceMetaPartition` test

- docs-zh/source/maintenance/atomicity.md
- docs-zh/source/sidebarConfig.js
- docs/source/maintenance/atomicity.md
- docs/source/sidebarConfig.js
> docs: add atomicity document

- proto/fs_proto.go
- proto/transaction.go
- sdk/meta/api.go
- sdk/meta/operation.go
- sdk/meta/transaction.go
reconstruct client transaction send process to clean duplicated code
> reconstruct(client.transaction):reconstruct client transaction send process to clean duplicated code

- metanode/meta_quota_manager.go
> fix(metanode): fix write file does not reach the quota, the error space is full

- master/limiter.go
uid info in manager access not protected by lock
> fix(master): uid info in manager access not protected by lock

- blobstore/common/trace/span_context.go
- blobstore/common/trace/span_test.go
- blobstore/common/trace/tracer_test.go
> fix(test): fixup test case of sort of map keys

- .github/workflows/ci.yml
> test(ci): do not run ci when merge docs

- docker/s3tests/test_bucket_policy.py
- objectnode/api_handler_bucket.go
- objectnode/policy.go
- objectnode/policy_handler.go
- objectnode/result.go
- objectnode/router.go
- objectnode/server.go
1. Fix the problem of returning 500 internal errors in PutBucketPolicy.
2. Add related parameter verification in GetBucketLocation.
fixes #2239
close #2239
```release-note
```
> fix(objectnode): fix bucket policy and location processing

- blobstore/api/proxy/client.go
- blobstore/blobnode/core/chunk/compact.go
- blobstore/cli/common/cfmt/access_test.go
- blobstore/clustermgr/diskmgr/alloc.go
- blobstore/clustermgr/diskmgr/alloc_test.go
- blobstore/common/rpc/lb.go
- blobstore/common/rpc/lb_test.go
- blobstore/common/rpc/server_test.go
- blobstore/common/rpc/simple.go
- blobstore/common/rpc/simple_test.go
correctly close response body
close #2253
> style(blobstore): correctly close response body

- metanode/partition_fsmop_extend.go
- objectnode/fs_volume.go
- sdk/meta/api.go
- sdk/meta/view.go
close: #2259
The directory quota can achieve the quota limit uploaded and written through s3, and it will also count
> feat(sdk): quota supports s3

- master/api_args_parse.go
- master/api_service.go
- master/cluster.go
- master/const.go
close: #2255
The original single directory limit is changed to dirLimit instead of dirQuota
> feat(master): The original single directory limit is changed to dirLimit instead of dirQuota

- blobstore/proxy/allocator/retain_volume_task.go
- blobstore/proxy/allocator/volume.go
- blobstore/proxy/allocator/volumemgr.go
- blobstore/proxy/allocator/volumemgr_test.go
fix alloc volume failed but proxy has available volumes
> fix alloc volume failed but proxy has available volumes

- blobstore/common/rpc/auditlog/auditlog.go
- blobstore/scheduler/client/clustermgr.go
- blobstore/scheduler/client/clustermgr_test.go
> fix(scheduler): fixup stuck when migrating task over 1000

- metanode/partition_fsmop_dentry.go
**Which issue this PR fixes** : fixes #2272
> fix(metanode): fix dentry update idempotence

- cli/cmd/quota.go
- metanode/meta_quota_manager.go
- metanode/partition.go
- metanode/partition_fsm.go
- metanode/partition_store.go
- metanode/partition_store_ticket.go
- proto/fs_proto.go
- proto/meta_proto.go
close: #2271
fix quota capacity statistics are inaccurate
> fix(metanode): fix quota capacity statistics are inaccurate

- sdk/meta/view.go
close: 2274
fix uploading through s3 does not immediately count the quota
> fix(sdk): fix uploading through s3 does not immediately count the quota

- sdk/meta/api.go
close: #2280
```release-note
```
> fix(sdk): fix the error message returned by the uploaded file in the case of over quota

- docker/s3tests/test_object_head.py
- docker/s3tests/test_signature.py
- docker/s3tests/test_transfer.py
- objectnode/api_handler.go
- objectnode/fs_volume.go
- objectnode/result_error.go
**Which issue this PR fixes**: fixes #2276
> perf(objectnode): improve metadata operation performance

- README.md
> doc: add Artifact Hub badge

- .github/workflows/issue_inactive.yml
- .github/workflows/issue_similarity.yml
actions-cool/issues-helper: label  inactive issues.
actions-cool/issues-similarity-analysis: find similarity issues.
> add some issue workflow

- .github/workflows/issue_inactive.yml
- .github/workflows/scorecard.yml
Add regular check of ossf scorecard
> doc: Create scorecard.yml

- docker/conf/datanode.json
- objectnode/api_handler_multipart.go
- objectnode/fs_volume.go
> fix objectnode evictinode and uploadpart interface not compare the Content-Md5

- blobstore/cli/blobnode/shard.go
add mark delete function in cli for blobnode, to solve delete failed in result of unexpected occasion
> feat(cli): add mark delete function in cli for blobnode

- objectnode/acl.go
- objectnode/acl_api.go
- objectnode/acl_api_test.go
- objectnode/acl_handler.go
- objectnode/api_handler_bucket.go
- objectnode/api_handler_multipart.go
- objectnode/api_handler_object.go
- objectnode/fs_volume.go
Reduce the acl meta storage space usage.
**Which issue this PR fixes**: fixes #2313
> feat(objectnode): reduce acl meta storage space usage

- docker/conf/master1.json
- docker/conf/master2.json
- docker/conf/master3.json
- objectnode/api_handler_multipart.go
- objectnode/fs_volume.go
- objectnode/server.go
- sdk/data/blobstore/writer.go
- sdk/meta/meta.go
- util/buf/buffer_pool.go
**Which issue this PR fixes** : fixes #2309
> feat(objectnode): read/write cold volume buffer pool

- objectnode/api_handler_bucket.go
- objectnode/api_handler_multipart.go
- objectnode/api_handler_object.go
- objectnode/policy_handler.go
> refactor(objectnode): refactor some redundant code

- metanode/partition_op_transaction.go
- proto/transaction.go
- sdk/meta/operation.go
fix create file tx op bug.
fix #2322
```release-note
```
> fix(meta & client): fix create op tx failed bug

- .github/workflows/ci.yml
- .github/workflows/issue_inactive.yml
- .github/workflows/issue_similarity.yml
- .github/workflows/release_test.yml
Set permissions to fixup Code scanning alerts
https://github.com/cubefs/cubefs/security/code-scanning/109
> chore(ci): add permissions in workflow

- README.md
Check the repository with CLOMonitor to verify CubeFS complies with project health best practices
> Update README.md to add clomonitor badge

- docs-zh/source/maintenance/configs/master.md
- docs-zh/source/maintenance/configs/metanode.md
- docs/source/maintenance/configs/master.md
- docs/source/maintenance/configs/metanode.md
This pull request enhances the documentation for the Service Configuration Introduction for master and metanode.
> docs(master&metanode): update docs about configurations for master and datanode

- objectnode/acl.go
- objectnode/acl_api.go
- objectnode/acl_enum.go
- objectnode/acl_test.go
- objectnode/fs_volume.go
Refactor the acl structure json tag to make the code more concise.
**Which issue this PR fixes**: fixes #2324
> refactor(objectnode): refactor acl structure json tag

- metanode/manager_op.go
- metanode/partition_fsmop_inode.go
- metanode/partition_fsmop_transaction.go
- metanode/partition_op_dentry.go
- metanode/partition_op_inode.go
- sdk/meta/api.go
let the retry operation success if the operation before already success
**Which issue this PR fixes**: fixes #2329
```release-note
```
> let the retry operation success if the operation before already success

- metanode/manager_op.go
- metanode/partition_fsmop_inode.go
- metanode/partition_fsmop_transaction.go
- metanode/partition_op_dentry.go
- metanode/partition_op_inode.go
- metanode/transaction.go
- sdk/meta/api.go
fix the metanode panic in some atomic op case.
**Which issue this PR fixes**: fixes #2335
```release-note
```
> fix(meta): fix the metanode panic in some atomic op case

- libsdk/libsdk.go
close: #2338
In some scenarios using libsdk need to support quota
> feat(libsdk): libsdk support quota

- metanode/partition_op_transaction.go
- metanode/transaction.go
- metanode/transaction_test.go
Closes #2342
fix(meta): return error status if initToRm failed.
```release-note
```
> fix(meta): return error status if initToRm failed.

- objectnode/policy.go
- proto/user_proto.go
Reduce fuse authentication check when using objnode
> fix(objnode): reduce fuse authentication check

- README.md
> doc: add license scan

- README.md
> doc: update CII Best Practices url

- master/master_manager_test.go
Closes #2355
```release-note
```
> fix(test): import new raftstore package in test file

- metanode/transaction.go
Closes #2363
Retry commit op return success if tx is alredy commit done.
```release-note
```
> fix(meta): Retry commit op return success if tx is alredy commit done.

- libsdk/libsdk.go
Optimized the return error code of the quota limit in the write scenario
> feat(libsdk): Optimized the return error code

- util/config/config.go
**background:** json.Unmarshal converts json literal integer to float64 instead of int64 when taget type is of type interface{}, so the function below are always return 0.
```go
func (c *Config) GetInt(key string) int {
x, present := c.data[key] // the type of 'x' is float64
if !present {
return 0
}
if result, isInt := x.(int); isInt { //isInt is always false, so the result will never be returned
return result
}
return 0
}
```
So we can use the UseNumber method on json.Decoder, which causes all numbers to unmarshal as `json.Number`
Before fixing this bug, value of `m.raftRecvBufSize` will be always '0' 
fixes #2372
> fix(util): fix wrong action when parse config

- cli/cmd/const.go
- cli/cmd/fmt.go
- cli/cmd/vol.go
- master/api_args_parse.go
- master/api_service.go
- master/cluster.go
- master/const.go
- master/metadata_fsm_op.go
- master/vol.go
- proto/admin_proto.go
- sdk/master/api_admin.go
- sdk/meta/api.go
- sdk/meta/meta.go
- sdk/meta/operation.go
- sdk/meta/view.go
close: #2341
Added support for delete-lock-time to Inode.
```release-note
```
> feat(Inode Lock Time): Added support for delete-lock-time to Inode.

- metanode/partition.go
- metanode/partition_fsmop_dentry.go
- metanode/partition_op_inode.go
- metanode/partition_op_transaction.go
- metanode/partition_store.go
- metanode/transaction.go
- metanode/transaction_test.go
- sdk/meta/api.go
- sdk/meta/operation.go
fix some bugs about tx.
#2375
#2366
```release-note
```
> fix some bugs about tx.

- datanode/partition.go
- datanode/partition_raft.go
- datanode/server_handler.go
- metanode/manager_op.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_dentry.go
- metanode/partition_op_inode.go
> Fix the snapshot issue caused by rebasing and cherry-picking old pull requests

- master/const.go
- master/monitor_metrics.go
- util/exporter/gauge.go
> Enhancement: Add master node stat metrics

- client/fs/file.go
- master/metadata_fsm_op.go
- metanode/partition_op_inode.go
- metanode/partition_op_quota.go
- proto/fs_proto.go
- proto/packet.go
- sdk/meta/api.go
- sdk/meta/meta.go
- sdk/meta/operation.go
- sdk/meta/quota_cache.go
- sdk/meta/quota_cache_test.go
close: 2393
Quota interacts with metanode twice when creating and deleting files, and reduces one interaction by caching
> feat(metanode,sdk): Optimize quota performance

- master/meta_partition.go
- master/vol.go
Closes #2400
```release-note
```
> fix(master): fix mp inode range maybe overlap bug when create vol.

- blockcache/cmd.go
- cli/cli.go
- client/fuse.go
- cmd/cmd.go
- fsck/cmd/clean.go
- libsdk/libsdk.go
- master/api_service_test.go
- metanode/transaction_test.go
- preload/sdk/preloadsdk.go
- util/log/log.go
- util/log/log_test.go
- util/log/rotate.go
close: #2399
fix bug that logs were not cleaned in time.
```release-note
```
> fix(log): fix bug that logs were not cleaned in time.

- .github/workflows/codeql.yml
> feat(ci): add SAST tool

- docs-zh/source/maintenance/gui.md
simplify titiles in gui doc and use relative pic addrs
> doc(gui): simplify titiles in gui doc and use relative pic addrs

- blobstore/Dockerfile
- build/compile/arm64/Dockerfile
- build/compile/arm64/centos/Dockerfile
- build/compile/arm64/gcc4/Dockerfile
- docker/authnode/Dockerfile1
- docker/authnode/Dockerfile2
- docker/authnode/Dockerfile3
- vendor/github.com/Shopify/sarama/Dockerfile.kafka
- vendor/golang.org/x/net/http2/Dockerfile
Fixed dockfile version issue，clear code scanning alert by Dockerfile
> feat(ci): clear code scanning alert by Dockerfile

- metanode/partition.go
> fix: uid quota need reset while rebuild not take effect

- docker/conf/master1.json
- docker/conf/master2.json
- docker/conf/master3.json
- objectnode/api_handler_bucket.go
- objectnode/api_handler_multipart.go
- objectnode/api_handler_object.go
- objectnode/fs_volume.go
- objectnode/result.go
- objectnode/server.go
- sdk/data/blobstore/writer.go
- sdk/meta/meta.go
- util/buf/buffer_pool.go
Solve the security issues of code scanning, mainly type conversion issues
> fix(objnode): fix code scan error

- blockcache/bcache/manage.go
- blockcache/bcache/service.go
- cli/cmd/vol.go
- master/api_args_parse.go
- master/http_server.go
fix the problem about the security code-scaning, `123, 124, 140, 141,142, 143, 144`
```release-note
```
> fix(master): fix the bug found in security code-scanning.

- docs-zh/source/maintenance/gui.md
doc(gui): add the method to encrypt database password
```release-note
```
> doc(gui): add the method to encrypt database password

- authtool/authtool.go
- cli/cmd/config.go
- master/api_service.go
- util/cryptoutil/const.go
- util/cryptoutil/cryptoutil.go
> fix alerts found by code scanning

- .github/workflows/codeql.yml
> fix(doc): fix codeql format problem

- docs-zh/source/deploy/manual-deploy.md
- docs-zh/source/maintenance/configs/objectnode.md
- docs-zh/source/user-guide/file.md
- docs/source/deploy/manual-deploy.md
- docs/source/maintenance/configs/objectnode.md
- docs/source/user-guide/file.md
> fix(doc): fix doc err

- util/auditlog/auditlog.go
> fix(codeql): fix codeql code-scanning

- .github/workflows/scorecard.yml
> feat(ci): update scorecards version

- blobstore/blobnode/base/util.go
- blobstore/common/raftserver/util.go
- blobstore/common/raftserver/util_test.go
fix some  alerts that found by code scanning
```release-note
```
> fix(blobstore): fix code scanning alert

- blobstore/access/controller/cluster.go
- blobstore/cli/access/cluster.go
- blobstore/cli/config/config.go
- blobstore/common/rpc/auditlog/prometheus_metric.go
fix some issues that found by code scanning
```release-note
```
> fix bugs that found by code scanning

- docs-zh/source/design/metanode.md
- docs/source/design/metanode.md
fixes some docs bug
```release-note
```
> fix(doc): fixes some docs bug

- master/meta_partition.go
- metanode/partition_fsmop_dentry.go
- objectnode/api_handler_bucket.go
- objectnode/api_handler_multipart.go
- objectnode/api_handler_object.go
- objectnode/api_middleware.go
- objectnode/const.go
- objectnode/fs.go
- objectnode/fs_volume.go
- objectnode/fs_volume_meta.go
- objectnode/object_lock.go
- objectnode/object_lock_test.go
- objectnode/result_error.go
- objectnode/router.go
- proto/perm_action.go
- sdk/meta/api.go
- sdk/meta/operation.go
**Which issue this PR fixes** : fixes #2454
> feat(objectnode): object lock

- java/src/main/java/io/cubefs/fs/TestCfsClient.java
- master/api_service.go
- preload/preload.go
- preload/sdk/preloadsdk.go
- sdk/master/api_admin.go
- storage/extent_store.go
- util/multipart.go
fix the problem of the security code-scaning: 32~ 110
> fix(master,sdk,preload): fix some bugs found in security code-scanning

- metanode/partition_op_inode.go
fixes: #2468 
```release-note
```
> fix(metanode): fix start a transaction and create an inode, but do not return quota information

- .github/workflows/codeql.yml
remove no use cpp, javascript codeql check.
```release-note
```
> chore(workflow): remove cpp, javascript codeql check.

- docs-zh/source/user-guide/k8s.md
- docs/source/user-guide/k8s.md
Fix doc for k8s, update `cfs-rbac.yaml` to  `csi-rbac.yaml`.
> [Doc] Fix doc for k8s

- master/api_args_parse.go
- master/api_service.go
> fix(master): fix parameter validation problem

- .github/workflows/codeql.yml
> fix(ci): Temporarily reduce the time of ci running

- blobstore/access/server.go
- blobstore/api/blobnode/shard.go
- blobstore/blobnode/core/storage/storage.go
- blobstore/clustermgr/diskmgr/diskmgr.go
- blobstore/common/rpc/auditlog/response.go
fix some code scan bug
```release-note
```
> fix(blobstore): fix some code scan bug

- objectnode/api_handler.go
- objectnode/result_error.go
Specific s3 4xx error returned when file is locked for deletion
> fix(objnode): file delete lock

- docs-zh/source/tools/gui.md
doc(gui): add how to compose url
```release-note
```
> doc(gui): add how to compose url

- sdk/meta/operation.go
fix cli panic when executing apply/revoke 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue 
fixes #2484
> fix cli panic when executing apply/revoke 

- blobstore/blobnode/core/storage/storage.go
- build/build.sh
- master/api_service_test.go
- master/cluster_test.go
- master/meta_node_test.go
- master/meta_partition.go
1. Open master ci test
2. Fix some ci test errors
```release-note
```
> fix(master): fix some test errors and open master ci test

- README.md
> feat(doc): update FOSSA

- docs/source/sidebarConfig.js
fixes docs error
fixes #
```release-note
```
> fix(docs): fix docs error

- docs-zh/source/user-guide/blobstore.md
- docs/source/quick-start/verify.md
- docs/source/user-guide/blobstore.md
fix docs error
fixes #
```release-note
```
> fix(docs): fix some docs error

- metanode/transaction.go
Closes #2509
fixes #
```release-note
```
> fix(meta): when tx is already exist, not return internal error.

- master/config.go
- master/vol.go
> perf(master): Optimize MP split algorithm

- master/api_service.go
- proto/packet.go
> fix(master):cold volume meta get verlist should  not check too strict

- docker/conf/datanode.json
- lcnode/lc_op.go
- lcnode/lc_scanner.go
- lcnode/lc_scanner_test.go
- lcnode/meta.go
- lcnode/meta_test.go
- lcnode/snapshot_scanner.go
- lcnode/snapshot_scanner_test.go
- master/cluster.go
- master/lifecycle_manager.go
- master/lifecycle_task.go
- master/snapshot_manager.go
- sdk/meta/api.go
1)refactor some code about snapshot
2)fix some bugs
3)add some ut
fixes #
```release-note
```
> refactor(lcnode): refactor some code in lcnode

- master/meta_partition_manager.go
- metanode/partition.go
- metanode/partition_fsm.go
- proto/admin_proto.go
1. Add committed index for meta partition response.
2. refactor some warn logs.
fixes #
```release-note
```
> refactor(master): add committed index for mp

- master/monitor_metrics.go
Support displaying the capacity usage of each nodeset, the number of dp mp replicas in metric report.
```bash
$ curl "http://192.168.0.11:17010/metrics" | grep -v "#" | grep cfs_master_nodeset
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 27047    0 27047    0     0  5282k      0 --:--:-- --:--:-- --:--:-- 5282k
cfs_master_nodeset_data_total_GB{nodeset="1"} 158.64603424072266
cfs_master_nodeset_data_usage_ratio{nodeset="1"} 0.21210218133040248
cfs_master_nodeset_data_used_GB{nodeset="1"} 33.649169921875
cfs_master_nodeset_dp_replica_count{nodeset="1"} 52
cfs_master_nodeset_meta_total_GB{nodeset="1"} 2
cfs_master_nodeset_meta_usage_ratio{nodeset="1"} 0.1770496368408203 …
```
> feat(metric): setup nodeset metrics

- master/vol.go
- sdk/meta/api.go
- sdk/meta/meta.go
- sdk/meta/view.go
> fix(sdk): fix inodefull err when the rw mp is not pulled in time

- util/exporter/exporter.go
> chore(sdk): remove inner useless code.

- master/cluster.go
- master/metadata_fsm_op.go
- master/topology.go
1. add dp into decommission list by goroutine when master load meta data
2. restor e decommission progress for disk when master restart
> bugfix(master):fix the issue of master being suspended when reading dp metadata

- objectnode/meta_cache.go
objnode metacache supports background evict
> enhance(objnode): metacache support background evict

- datanode/partition_op_by_raft.go
- datanode/wrap_operator.go
- metanode/dentry.go
- metanode/multi_ver_test.go
- metanode/transaction.go
- metanode/transaction_test.go
- sdk/data/stream/stream_writer.go
1） Dentry marshal and unmarshal not consistent base on version and add test
2） The rebase code caused unconditional repeated execution of doOverWrite, without considering the snapshot scenario
3）  The result of RandomWriteSubmit should be checked for the retcode interface type. Failure to do so may trigger exceptions or errors in the code execution
fixes #
```release-note
```
> fix bug of snapshot  caused by rebase and modification recently for extention

- objectnode/api_handler_object.go
- objectnode/fs_volume.go
Fix superfluous writeheader when batach delete failed.
> fix(objectnode): fix superfluous writeheader

- metanode/multi_ver_test.go
- metanode/packet.go
- metanode/partition_free_list.go
- metanode/partition_fsm.go
- metanode/partition_op_inode.go
- metanode/partition_op_uniq.go
- metanode/partition_op_uniq_test.go
- sdk/meta/api.go
- storage/extent.go
- storage/extent_store.go
- storage/persistence_crc.go
- util/unit.go
fix(metanode).snapshot.split ext punch hole requires 4k alignment or else delete normal data
fix(metanode): snapshot. inode once unlink didn't take verseq
inner version not released
```release-note
```
> fix(metanode).snapshot related bugs

- lcnode/lc_op.go
- lcnode/snapshot_scanner.go
- lcnode/snapshot_scanner_test.go
- master/admin_task_manager.go
- master/cluster.go
- master/lifecycle_manager.go
- master/lifecycle_node.go
- master/lifecycle_task.go
- master/snapshot_manager.go
- proto/packet.go
- proto/snapshot.go
> refactor(lcnode): refactor some code about lcnode task manager

- metanode/partition.go
Closes #2560
fixes #
```release-note
```
> refactor(meta): refactor isFollowerRead func to improve performance.

- master/meta_partition.go
- master/vol.go
> fix(master): mp split task should wait mp heartbeat done

- master/cluster.go
- master/data_node.go
- master/data_partition.go
- master/filecrc.go
- master/topology.go
- metanode/partition_fsm.go
- proto/packet.go
- sdk/data/stream/extent_cache.go
- sdk/data/stream/extent_handler.go
- sdk/data/stream/stream_writer.go
- util/exporter/histogram.go
refactor(lcnode): refactor some code about lcnode task manager
enhance(master).crc check log no need be consider as error while crc is equal but applyid not
bugfix(master): fix deadlock when resotre running dp meta
fixes #
```release-note
```
> merge3.4.0 left and clean logs

- depends/tiglabs/raft/raft_fsm_leader.go
- depends/tiglabs/raft/server.go
- depends/tiglabs/raft/transport_heartbeat.go
1. Add someRaft logs
fixes #
```release-note
```
> feat(raft): add some logs

- depends/tiglabs/raft/server_test.go
- metanode/dentry.go
- metanode/inode.go
- metanode/partition_fsmop_dentry.go
- metanode/partition_fsmop_inode.go
- metanode/sorted_extents.go
- sdk/data/stream/extent_handler.go
- security/security-release-process.md
- util/log/log.go
update security committee and reduce log output
fixes #
```release-note
```
> update security committee and reduce log output

- master/nodeset_selector.go
- master/nodeset_selector_test.go
* In specified case (only 2 nodesets in a zone), current implementation of `CarryWeightNodesetSelector` will be equal with `RoundRobinNodesetSelector`.
* The pull request fix the bug and add more tests to nodeset selector.
```release-note
```
> [Fix]: `CarryWeightNodesetSelector` will be equal with `RoundRobinNodesetSelector` in specified case

- master/multi_ver_snapshot.go
- metanode/partition_op_extent.go
- proto/admin_proto.go
enhance(master): snapshot. update process of version sequence check in strategy since ver update from second to microscond
enhance(Raft): update error output to warn since the mp inconstent may be caused by raft log behind
fixes #
```release-note
```
> snapshot. update process of version sequence check in strategy and update log ouput 

- objectnode/ratelimit.go
- objectnode/server.go
- util/config/config.go
- util/reloadconf/reload_conf.go
> feat(objectnode): add some s3qos log

- objectnode/ratelimit.go
> fix(objectnode): fix s3 put api qos not work

- lcnode/meta.go
- lcnode/meta_test.go
- lcnode/snapshot_scanner.go
- metanode/partition_fsmop_dentry.go
- proto/fs_proto.go
- sdk/data/stream/stream_writer.go
- sdk/meta/api.go
- snapshot/cmd/clean.go
refactor function name and param mainly relate to snapshot
> refactor function name and param mainly relate to snapshot

- cli/cmd/disk.go
- sdk/data/manager/limiter.go
- sdk/graphql/client/cluster/client.go
- sdk/graphql/client/login_client.go
- sdk/graphql/client/user/client.go
- sdk/graphql/client/user/my_client.go
Solve warnings that do not comply with go language rules
> feat(sdk): Solve warnings that do not comply with go language rules

- objectnode/ratelimit.go
> fix(objectnode): fix s3qos resource release

- metanode/inode.go
- metanode/manager_op.go
- metanode/multi_ver_test.go
- metanode/partition.go
- metanode/partition_fsm.go
- metanode/partition_op_extent.go
- proto/packet.go
- sdk/data/wrapper/wrapper.go
enhance(metanode): snapshot. mp update version list according master and apply by raft submit
1)apply to avoid conflict with version commit process
2)consistent with master verlist then do verlist append and delete
3)normal version commit from master also need consider the seq in the mp list
>  snapshot. mp update version list according master and apply by raft submit

- blobstore/blobnode/base/qos/config.go
- blobstore/blobnode/base/qos/qos.go
- blobstore/blobnode/base/qos/qos_test.go
- blobstore/blobnode/config.go
- blobstore/blobnode/core/chunk/chunk_test.go
- blobstore/blobnode/core/chunk/compact_test.go
- blobstore/blobnode/core/config.go
- blobstore/blobnode/core/disk/disk.go
- blobstore/blobnode/core/storage/datafile_test.go
- blobstore/blobnode/shard.go
- blobstore/blobnode/shard_test.go
- blobstore/blobnode/startup.go
- blobstore/blobnode/svr.go
- blobstore/util/taskpool/iopool.go
- blobstore/util/taskpool/iopool_mock.go
- blobstore/util/taskpool/iopool_test.go
fix #1915
optimize the qos of blobnode
fixes #1915
```release-note
```
> feature(blobnode): Limit the number of threads for blobnode, optimize qos config

- master/cluster.go
- master/metadata_fsm_op.go
- master/multi_ver_snapshot.go
- metanode/manager.go
- metanode/manager_op.go
- metanode/multi_ver_test.go
- metanode/partition.go
- metanode/partition_fsm.go
- metanode/partition_op_extent.go
- repl/repl_protocol.go
enhance(master):load multi version error need exit
fix(master):version time cann't be equal
enhance(master):snapshot.update creatiton and deletion condition in strategy
enhance(metanode):snapshot. version message from master need raft submit and quened
> snapshot.enhance version creation and syncronization process

- .gitattributes
fix problem with png files being modified
> fix: fix problem with png files being modified

- docs-zh/source/deploy/metrics/metrics.md
- docs-zh/source/tools/cli.md
- docs/source/deploy/metrics/metrics.md
- docs/source/tools/cli.md
update docs about nodeset
fixes #
```release-note
```
> feat(docs): update docs about nodeset

- objectnode/fs_volume.go
temporary data security check for concurrent complete
> fix(objectnode): temporary data security check for concurrent complete

- datanode/space_manager.go
- docker/script/run_test.sh
- master/metadata_fsm.go
- master/metadata_fsm_op.go
* Show more information in CI to help debug.
* Fix dp count limit.
* Avoid non-atomic `os.RemoveAll` when apply snapshot.
```release-note
```
> [Fix]: fix some bugs & show node information in CI to help debug

- master/server.go
- raftstore/raftstore_db/store_rocksdb.go
* Close RocksDB when master shutdown normally.
```release-note
```
> [Fix]: Close RocksDB when master shutdown

- blobstore/common/trace/span.go
- blobstore/util/log/log.go
- blobstore/util/log/logext.go
ignore format logging if mismatch log level
fixes #2611 
```release-note
```
> chore(trace): ignore format logging if mismatch log level

- docker/script/run_format.sh
- storage/error.go
- storage/extent.go
- storage/extent_store.go
- storage/extent_store_test.go
- storage/extent_test.go
clean test data of extent storage
fixes #
```release-note
```
> chore(store): clean test data of extent storage

- blobstore/common/trace/span.go
ignore format span if mismatch log level
fixes #2611
```release-note
```
> chore(trace): ignore format span if mismatch log level

- depends/bazil.org/fuse/fs/serve.go
- metanode/extend.go
- metanode/multi_ver_test.go
- metanode/partition_fsmop_extend.go
- metanode/partition_op_extend.go
- metanode/partition_op_extent.go
- proto/fs_proto.go
- sdk/data/stream/stream_writer.go
- sdk/data/wrapper/wrapper.go
- sdk/meta/conn.go
enhance(metanode):snapshot.support xattr
fix(metanode):snapshot.changed the way snapshots are read, and the metanode needs to adapt to range reads
> snapshot.add xattr and fix bugs

- UPDATE.md
add update docs, from v1.2.2 to v1.2.3, solve handle blob delete msg too slow
fixes #
```release-note
```
> docs(scheduler): add update docs, from v1.2.2 to v1.2.3, solve handle blob delete msg too slow

- docs-zh/source/maintenance/troubleshoot/strategy.md
- docs/source/maintenance/troubleshoot/strategy.md
Fix local document hyperlinks.
> fix(docs): fix local document hyperlinks

- metanode/partition_op_extent.go
snapshot.check version list with master miss condition and panic
> fix(metanode):snapshot.check version list with master miss condition and panic

- blobstore/common/rpc/auditlog/response.go
- objectnode/api_context.go
do not copy buffer in response writer
fixes #
```release-note
```
> do not copy buffer in response writer

- blobstore/common/rpc/auditlog/auditlog.go
- blobstore/common/trace/span.go
- blobstore/common/trace/span_test.go
- blobstore/common/trace/tracer.go
recursively save span operation name
fixes #2626
```release-note
```
> recursively save span operation name

- metanode/inode.go
- metanode/partition_fsmop_dentry.go
- metanode/partition_fsmop_inode.go
> enhance(log): clean debug log output

- blobstore/common/rpc/auditlog/auditlog_test.go
- blobstore/common/rpc/auditlog/response.go
close: #2652
rpc response implements interface read from
fixes #2652
```release-note
```
> feat(rpc): response implements interface read from

- depends/tiglabs/raft/raft_fsm_leader.go
- metanode/partition.go
- metanode/partition_store.go
> feat(raft):add raft log

- metanode/inode.go
- metanode/manager_op.go
- metanode/multi_ver_test.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/sorted_extents.go
- proto/extent_key.go
- sdk/meta/conn.go
> enhance features  and fix some bugs related with snapshot

- depends/tiglabs/raft/storage/wal/config.go
- depends/tiglabs/raft/storage/wal/log_storage.go
- metanode/inode.go
- metanode/partition.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/uniq_checker.go
- util/timeutil/time.go
- util/timeutil/time_test.go
reduce raft log index memory usage
fixes #2663
> [Enhancement]: metanode: Reduce raft index log mem

- master/cluster.go
- sdk/data/wrapper/wrapper.go
(1)fix returned err if init datapartition failed when creating volume.
(2)optimize a log in client.
> fix(master): fix returned err if init datapartition failed when creating volume.

- docs-zh/version.json
- docs/version.json
fix the problem that version.json format is incorrect
> fix(docs): fix the problem that version.json format is incorrect

- docs-zh/source/quick-start/node.md
- docs/source/quick-start/node.md
update content to the latest version
> enhance(docs): update content to the latest version

- blobstore/common/rpc/auditlog/filter.go
- blobstore/common/rpc/auditlog/filter_test.go
feat(rpc): #1924 add log filter
```release-note
```
> feat(rpc): #1924 add log filter

- objectnode/api_handler_object.go
- objectnode/fs_volume.go
- sdk/meta/api.go
lifecycle skip deleting locked object
> fix(objectnode): lifecycle skip locked object

- blobstore/common/rpc/auditlog/auditlog.go
- blobstore/common/rpc/auditlog/auditlog_test.go
- blobstore/common/rpc/auditlog/filter.go
- blobstore/common/rpc/auditlog/filter_test.go
- blobstore/common/rpc/auditlog/proto.go
- blobstore/common/rpc/example/app.go
- blobstore/common/rpc/example/main/main.conf
- docs-zh/source/maintenance/configs/blobstore/base.md
- docs-zh/source/maintenance/configs/blobstore/blobnode.md
- docs/source/maintenance/configs/blobstore/base.md
- docs/source/maintenance/configs/blobstore/blobnode.md
blobstore rpc auditlog with log filter
fixes #1924
```release-note
```
> feat(rpc): auditlog with log filter

- docs-zh/source/community/article.md
- docs/source/community/article.md
> enhance(docs): update articles to latest

- master/vol.go
avoid split during volume creation
> fix(master): avoid split during volume creation

- build/build.sh
- master/api_service.go
- master/cluster.go
- master/multi_ver_snapshot.go
- master/vol.go
- master/vol_test.go
- metanode/inode.go
- metanode/manager_op.go
- metanode/multi_ver_test.go
- metanode/partition_fsmop_inode.go
- proto/fs_proto.go
- sdk/meta/operation.go
fix(metanode):append extents no need to care verSeq in client's request
enhance(master):rewrite lock and check logic for mpslock of volume, the lock may hang by small probability event
> enhance(master):rewrite lock and check logic for mpslock of volume, the lock may hang by small probability event

- objectnode/api_handler_bucket.go
- objectnode/api_handler_multipart.go
- objectnode/api_handler_object.go
- objectnode/const.go
fix read body entirely into memory
Security issue: https://github.com/cubefs/cubefs/security/advisories/GHSA-qc6v-g3xw-grmx
> fix(objectnode): fix read body entirely into memory

- master/api_service.go
- master/cluster.go
- master/metadata_fsm_op.go
- master/multi_ver_snapshot.go
- master/vol.go
Encapsulated mpslock, the deadlock timeout class locates the specific stack, and one deadlock has been resolved. Fixed some minor optimization
> Fix master deadlock and some issues

- objectnode/api_handler_object.go
> fix(objectnode): fix delete object 5xx error

- docs-zh/source/deploy/yum.md
- docs/source/deploy/yum.md
Deploy the rpm package path updated to 3.3.0
> feat(docs): Deploy the rpm package path updated to 3.3.0

- lcnode/lc_scanner.go
- lcnode/meta.go
- lcnode/meta_test.go
- lcnode/server.go
- lcnode/snapshot_scanner.go
- master/cluster.go
- master/lifecycle_manager.go
- master/lifecycle_node.go
1. fix(lcnode): close metawrapper in lcnode
2. fix(lcnode): stop lcnode straightway
> fix(lcnode): stop lcnode straightway

- datanode/wrap_operator.go
- metanode/inode.go
- metanode/partition_fsmop_dentry.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_inode.go
- metanode/sorted_extents.go
- metanode/sorted_extents_test.go
- proto/model.go
truncate refMap not be set trigger panic while restart，truncate punch hole on extent and it's extent key should add to ref map, otherwise may trigger panic.
> fix(metanode):truncate refMap not be set trigger panic while restart

- Makefile
- build/build.sh
- deploy/cmd/cluster.go
- deploy/cmd/config.go
- deploy/cmd/datanode.go
- deploy/cmd/docker.go
- deploy/cmd/firewall.go
- deploy/cmd/master.go
- deploy/cmd/metanode.go
- deploy/cmd/restart.go
- deploy/cmd/root.go
- deploy/cmd/ssh.go
- deploy/cmd/start.go
- deploy/cmd/start_docker_compose.go
- deploy/cmd/stop.go
- deploy/cmd/transform.go
- deploy/config.yaml
- deploy/deploy_cli.go
fixes #1927 
```release-note
```
> deploy-test

- master/meta_partition.go
> fix(master): fix mp heartbeat done flag

- metanode/sorted_extents.go
not setEk true outside of storeSplitEk
```release-note
```
> 🐞 fix(meta): fix setSplitEk error log bug.

- master/vol.go
mp split task limit volume creation time
> mp split task limit volume creation time

- objectnode/api_handler_object.go
- objectnode/post_policy.go
- objectnode/result.go
- objectnode/result_error.go
Allows users to upload objects through forms when using ObjectNode.
fixes #2695
> feat(objectnode): support post object

- master/lifecycle_task.go
Signed-off-by: zhaochenyang <zhaochenyang@oppo.com>
fixes #
```release-note
```
> fix(lcnode): fix panic caused by lcnode heartbeat

- objectnode/api_handler_object.go
> fix(object): fix content length limit

- objectnode/api_handler_object.go
> fix(objectnode): fix error response with object lock in postobject

- objectnode/api_handler_bucket.go
> Fix/create bucket err 3.3.0

- objectnode/api_handler_bucket.go
> fix(object): fix create bucket err

- sdk/master/client.go
- sdk/meta/meta.go
> fix(sdk): fix error value returned in serveRequest

- depends/tiglabs/raft/server.go
- metanode/partition.go
- metanode/partition_fsmop_dentry.go
1)add interface of IsRestoring to raft store for better performace while do IsFollowerRead jugement
2)enhance cold volume create replicaNum check
> Some optimizations have been made since the release of version 3.3.0

- repl/repl_protocol.go
> 🐞 fix(datanode): fix print connection log panic.

- objectnode/api_handler_object.go
- objectnode/post_policy.go
- objectnode/result_error.go
> Merge in the code fixed in PostObject

- build/build.sh
- metanode/inode.go
- repl/packet.go
- repl/repl_protocol.go
- sdk/data/stream/extent_cache.go
- sdk/data/stream/stream_writer.go
fix(client):try direct write need check the extent offset
fix(datanode): read random write packet miss verlist element
enhance(client):GetEndForAppendWrite
> fix bugs related with snapshot and do some enhancements

- objectnode/policy.go
- proto/user_proto.go
s3api perm is compatible with fuse perm
> fix(objectnode): s3api perm is compatible with fuse perm

- MAINTAINERS.md
* Add commiter to `MAINTAINERS.md`
See also:[Wechat Doc](https://mp.weixin.qq.com/s/m5lfzInds7I7v_k-k_6r_Q)
```release-note
```
> [Chore]: Add commiter to `MAINTAINERS.md`

- objectnode/api_handler_multipart.go
- objectnode/result_error.go
> fix(object): partNumber of multipart must be greater than 0

- cli/cmd/fmt.go
- cli/cmd/vol.go
- master/api_service.go
- master/api_service_test.go
- master/cluster.go
- master/http_server.go
- master/metadata_fsm_op.go
- master/mocktest/data_server.go
- master/mocktest/meta_server.go
- master/mocktest/partition.go
- master/vol.go
- metanode/manager_op.go
- metanode/partition.go
- metanode/partition_op_dentry.go
- metanode/partition_op_extent.go
- metanode/partition_op_inode.go
- metanode/partition_op_transaction.go
- proto/admin_proto.go
- sdk/master/api_admin.go
* Make a cherry-pick.
```release-note
```
> [Cherry-Pick]: Commit audit log control to  branch `develop-v3.3.1`

- master/gapi_user.go
- master/user.go
from cncf security audit:
Timing attack can leak user passwords
> enhance(gapi):Timing attack can leak user passwords and CubeFS leaks users key in logs from cncf security audit

- metanode/manager.go
- metanode/partition.go
- metanode/partition_free_list.go
- metanode/transaction.go
- util/auditlog/auditlog.go
- util/set.go
- util/set_test.go
* Merge `GetDataPartitionsView` RPCs in same volume into one.
* Merge `GetVolumeSimpleView` RPCs in same volume into one.
fixes #1908
* Please view the note of commits.
```release-note
```
> [Enhancement]: Merge RPCs in same volume into one

- blobstore/blobnode/core/chunk/chunk_test.go
- blobstore/blobnode/core/chunk/compact_test.go
- blobstore/common/profile/gen.go
- blobstore/common/trace/span.go
- blobstore/common/trace/span_test.go
fixup testing of compacting service overload
fixes #
```release-note
```
> fixup testing of compacting service overload

- blobstore/clustermgr/volumemgr/volumemgr.go
> fix(ClusterMgr): fix volume manager deadlock

- blobstore/blobnode/work_shard_recover.go
fix blobnode deadlock from cubefs-draft-security-audit-report
fixes #2791 
```release-note
```
> fix(blobnode): fix put shard deadlock

- util/flowctrl/keycontroller.go
- util/ratelimit/keyratelimit.go
> fix(Object): fix limiter lib deadlock

- blobstore/common/rpc/auditlog/auditlog.go
- objectnode/acl_handler.go
- objectnode/api_handler_multipart.go
- objectnode/api_handler_object.go
> enhance(object): add time-consuming tracking in object access

- docs-zh/source/overview/introduction.md
- docs/source/overview/introduction.md
fixes #2780
```release-note
```
> fix(docs): fix introduction video url

- cmd/cmd.go
Remove duplicate redirect code in cmd.go.
fixes #
```release-note
```
> chore(cmd): remove duplicate redirect code in cmd.go

- MAINTAINERS.md
Add commiter
See https://mp.weixin.qq.com/s/m5lfzInds7I7v_k-k_6r_Q
> chore: update MAINTAINERS.md

- blobstore/blobnode/base/qos/qos_test.go
fix probabilistic ut fail
fixes #
```release-note
```
> fix(blobnode): fix probabilistic ut fail

- metanode/partition_fsmop_inode.go
- metanode/sorted_extents.go
- proto/packet.go
- sdk/data/stream/extent_cache.go
- sdk/data/stream/stream_writer.go
- storage/extent_store.go
1）extent cache wrongly update
2）during lastKey reuse handler may not have a effective key
3)  datanode mod append write allocated wrongly
> Fix snapshot inconsistent bugs about modification based on snapshot

- blobstore/blobnode/core/blobfile.go
- blobstore/blobnode/core/blobfile_test.go
- blobstore/blobnode/core/chunk/chunk_test.go
- blobstore/blobnode/core/chunk/compact_test.go
- blobstore/blobnode/core/disk/compact_test.go
- blobstore/blobnode/core/disk/disk.go
- blobstore/blobnode/core/storage/datafile_test.go
- blobstore/blobnode/work_shard_recover.go
- blobstore/util/taskpool/iopool.go
- blobstore/util/taskpool/iopool_mock.go
- blobstore/util/taskpool/iopool_test.go
io pool add prometheus, timeout I/O need to report
fixes #2779
```release-note
```
> enhance(blobnode): support prometheus at io pool module

- blobstore/clustermgr/volumemgr/alloc.go
- blobstore/clustermgr/volumemgr/startup.go
- blobstore/clustermgr/volumemgr/volumemgr.go
- blobstore/clustermgr/volumemgr/volumemgr_test.go
The idle volume is stored into shards to reduce the lock scope.
> volume allocation optimization

- master/cluster.go
… to avoid panic
fix(master): not use var pointer dataNode if not got if from cluster, to avoid panic
> fix(master): not use var pointer dataNode if not got if from cluster, to avoid panic

- cmd/cfg/datanode.json
- datanode/disk.go
- datanode/limit_io.go
- datanode/limit_io_test.go
- datanode/partition_op_by_raft.go
- datanode/server.go
- datanode/server_handler.go
- datanode/wrap_operator.go
- docs-zh/source/maintenance/configs/datanode.md
- docs/source/maintenance/configs/datanode.md
limit datanode disk flow and io concurrency
fixes #
```release-note
```
> limit datanode disk flow and io concurrency

- blockcache/bcache/manage.go
fix possible deadlocks of bcache
fixes #
```release-note
```
> fix(bcache): fix possible deadlock of bacahe

- docs-zh/source/tools/cfs-cli/volume.md
- docs/source/tools/cfs-cli/volume.md
> [Doc]: Add some docs about cli

- objectnode/api_handler_bucket.go
- objectnode/result_error.go
- objectnode/server.go
Configurably disable volume create by s3 and listbucket add authedVols
> Configurably disable volume create by s3 and listbucket add authedVols

- fsck/cmd/gc.go
> fix(fsck): add lock to protect host map

- .github/workflows/ci.yml
- .semgrep.yml
- docker/docker-compose.yml
- docker/run_docker.sh
- objectnode/auth.go
- objectnode/const.go
1. add sast tools: gosec
2. add sast tools: semgrep
> feat(ci): add sast tools gosec and semgrep

- .github/slsa/slsa-authtool-linux-amd64.yml
- .github/slsa/slsa-bcache-linux-amd64.yml
- .github/slsa/slsa-client-linux-amd64.yml
- .github/slsa/slsa-fdstore-linux-amd64.yml
- .github/slsa/slsa-fsck-linux-amd64.yml
- .github/slsa/slsa-preload-linux-amd64.yml
- .github/workflows/goreleaser.yml
- .github/workflows/slsa-releaser.yml
- .gitignore
- .goreleaser.yaml
- Makefile
- build/build.sh
- docker/docker-compose.yml
- docker/run_docker.sh
see: #2811
fixes #2811
```release-note
```
> build(workflow): build disabled cgo binary with slsa releaser

- datanode/data_partition_repair.go
- datanode/partition_op_by_raft.go
- datanode/wrap_operator.go
- master/cluster.go
- master/data_partition.go
- master/meta_partition.go
- metanode/inode.go
- metanode/multi_ver_test.go
- metanode/partition.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/partition_store_ticket.go
- proto/model.go
- proto/packet.go
- proto/perm_action.go
- repl/packet.go
- storage/extent.go
- storage/extent_store.go
- storage/extent_test.go
[fix(datanode):repair get extent size need include snapshot size]
fix(metanode):inode lock scope in inner tempory snapshot deletion sho… 
fix(datanode):extent repairt after 128M 
fix(datanode): readConn check read packet not consistent with client … 
fix(metanode): inode deletion condition be updated to avoid accidenta…
> fix bugs in 1.dead lock 2.datanode repair 3.dir snapshot deletion 

- blockcache/cmd.go
- client/fuse.go
- cmd/cmd.go
- preload/sdk/preloadsdk.go
fix the problem of gosec
fixes #
```release-note
```
> fix the problem of gosec

- blockcache/cmd.go
- client/fuse.go
- cmd/cmd.go
- preload/sdk/preloadsdk.go
fix gosec problems
fixes #
```release-note
```
> fix gosec problems

- cli/cmd/fmt.go
- master/api_service.go
- master/api_service_test.go
- master/cluster.go
- master/metadata_fsm_op.go
- master/vol.go
- proto/admin_proto.go
- util/auditlog/auditlog.go
- util/auditlog/auditlog_test.go
* Enable audit log by default.
* Remove lock from auditlog.
* Please be careful when cherry-pick this commit.
```release-note
```
> [Feature]: Enable audit log by default

- .github/slsa/slsa-authtool-linux-amd64.yml
- .github/slsa/slsa-bcache-linux-amd64.yml
- .github/slsa/slsa-client-linux-amd64.yml
- .github/slsa/slsa-fdstore-linux-amd64.yml
- .github/slsa/slsa-fsck-linux-amd64.yml
- .github/slsa/slsa-preload-linux-amd64.yml
- .github/workflows/goreleaser.yml
- .github/workflows/slsa-releaser.yml
- .gitignore
- .goreleaser.yaml
- Makefile
- build/build.sh
- docker/docker-compose.yml
- docker/run_docker.sh
build cgo-disabled binary with slsa releaser
build with goreleaser
fixes #
```release-note
```
> build cgo-disabled binary with slsa releaser

- .semgrep.yml
> fix(ci): fix semgrep rules

- lcnode/lc_scanner.go
> fix(code scan): remove default statements in select added before

- SECURITY.md
- authnode/http_server.go
- blobstore/cmd/cmd.go
- blobstore/common/consul/consul.go
- blobstore/common/raftserver/transport.go
- master/http_server.go
- master/user.go
- metanode/inode.go
- objectnode/acl_api.go
- objectnode/server.go
[fix(metanode):add lock release before panic for security]
(https://github.com/cubefs/cubefs/commit/dcb5ee8c5d9715f986c3af2b92e3c8634f8701cb)
> some commits related with security audit

- fsck/cmd/gc.go
> 🐞 fix(fsck): close clean switch before online.

- master/api_args_parse.go
- master/api_service.go
- master/node_selector.go
…g volume
Signed-off-by: true1064 <tangjingyu@oppo.com>
feat(master): [hybrid cloud] sort AllowedStorageClass[] while creating volume
> feat(master): [hybrid cloud] sort AllowedStorageClass[] while creating volume

- datanode/wrap_operator.go
> ✨ feat(data): refactor delete logic to check opcode first

- datanode/data_partition_repair.go
- datanode/partition.go
add debug log for datanode repair
> enhance(datanode): add debug log for datanode repair

- lcnode/const.go
- lcnode/lc_op.go
- lcnode/lc_scanner.go
- lcnode/server.go
- lcnode/snapshot_scanner.go
- master/cluster.go
- master/lifecycle_manager.go
- master/lifecycle_task.go
- master/snapshot_manager.go
- proto/admin_proto.go
- proto/lifecycle.go
- proto/snapshot.go
1. add lcTaskCountLimit
2. delete Scanning and add WorkingCount
3. add lcnode addr in heartbeat resp and scan resp
fixes #
```release-note
```
> enhance(lcnode): support multi task

- master/api_service.go
- master/api_service_test.go
fix(master): check if the cluster has resource to support req.VolStorageClass when create vol.
> fix(master): check if the cluster has resource to support req.VolStorageClass when create vol.

- master/api_args_parse.go
… in vol.allowedStorageClass
fix(master): when updateVol, check that req.VolStorageClass should be  in vol.allowedStorageClass
> fix(master): when updateVol, check that req.VolStorageClass should be  in vol.allowedStorageClass

- lcnode/lc_scanner.go
- lcnode/lc_transition.go
- lcnode/meta.go
- lcnode/meta_test.go
- metanode/api_handler.go
- metanode/partition.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/partition_op_inode.go
- metanode/sorted_hybridcloud_obj_extents.go
- proto/fs_proto.go
- sdk/meta/api.go
- sdk/meta/operation.go
1.bugfix(metanode):fix bug when update extent key after migration
2.enhance(metanode): add api for get full inode infomation include eks
> enchance(metanode):add api for get full inode infomation include eks

- libsdk/libsdk.go
multi-thread call cfs_rename leadto same ino
fixes #
```release-note
```
> fix(libsdk): multi-thread call cfs_rename leadto same ino

- master/api_service.go
- sdk/meta/view.go
fix the calculation of vol usedSize
> bugfix(client,master):fix the calculation of vol usedSize

- objectnode/api_handler_object.go
- objectnode/fs_volume.go
1. fix listobjectv1 err with delimiter
2. data security check for concurrent complete request
> fix listobjectv1 err with delimiter / data security check for concurrent complete request

- cli/cmd/vol.go
- master/api_args_parse.go
- master/api_service.go
- master/cluster.go
- master/http_server.go
- master/vol.go
- proto/admin_proto.go
- proto/auth_proto.go
- sdk/master/api_admin.go
feat(master, cli): add API to add storageClass to volume's allowedStorageClass list
> feat(master, cli): add API to add storageClass to volume's allowedStorageClass list

- fsck/cmd/common.go
- fsck/cmd/gc.go
- fsck/cmd/root.go
- storage/extent_store.go
fixes #2880 
```release-note
```
> remove clean flag & not return error when read garbage.

- docker/script/run_format.sh
show diffs of gofmt in ci format.
fixes #
```release-note
```
> feat(ci): show diffs of gofmt in ci format

- blockcache/bcache/client.go
- blockcache/bcache/manage.go
- blockcache/bcache/packet.go
- blockcache/bcache/service.go
- blockcache/cmd.go
- docker/Dockerfile-ltp
- docker/build_docker.sh
- docker/docker-compose.yml
- docker/run_docker.env
- docker/run_docker.sh
- docker/script/run_format.sh
- lcnode/const.go
- lcnode/lc_op.go
- lcnode/lc_scanner.go
- lcnode/lc_scanner_test.go
- lcnode/server.go
- lcnode/snapshot_scanner.go
- lcnode/snapshot_scanner_test.go
- storage/extent_test.go
golangci lint apply into lcnode and blockcache.
remove ltp in docker if no ltptest.
fixes #
```release-note
```
> chore(lcnode): golangci lint apply into lcnode, remove ltp in docker if no ltptest

- cli/cmd/fmt.go
- master/api_service.go
- master/cluster.go
- master/metadata_fsm.go
- master/metadata_fsm_op.go
- raftstore/raftstore_db/store_rocksdb.go
* Fix #2841.
* Fix typo in `cfs-cli datanode info`.
* Make `UpdateData/MetaNode` to be atomic.
fixes #2841
```release-note
```
> [Fix]: fix some bugs

- datanode/const.go
- metanode/inode.go
- metanode/partition_fsmop_inode.go
- metanode/sorted_extents.go
- sdk/data/stream/stream_reader.go
fix(metanode):Snapshot.refactor inode deletion and consider system verlist dependency
fix(metanode): Regarding reference counting, performing append writes in the middle of the EKS and unifying the condition for appending as the last key (lastKey) of the EKS
> fix snapshot bugs: 1)extent meta reference management optimization 2)snapshot deletion

- master/api_service_test.go
- master/node_selector.go
- master/node_selector_test.go
- master/nodeset_selector.go
- master/nodeset_selector_test.go
* Ticket Node/Nodeset Selector cann't pass unit tests in some cases.
* It already by replaced by Straw Node/Nodeset Selector.
```release-note
```
> [Refactor]: Remove ticket node/nodeset selector

- docs-zh/source/overview/architecture.md
**Which issue this PR fixes**: fixes #2962
> fix(doc): Corrected typos in documents

- cli/api/metaapi.go
- cli/cli.go
- cli/cmd/datanode.go
- cli/cmd/root.go
- datanode/server_handler.go
- docker/docker-compose.yml
- fsck/cmd/check.go
- fsck/cmd/getInfo.go
- master/api_service.go
- master/api_service_test.go
- master/data_node_test.go
- master/data_partition_test.go
- master/id_allocator_test.go
- master/master_manager_test.go
- master/meta_node_test.go
- master/meta_partition_test.go
- master/mocktest/data_server.go
- master/mocktest/meta_server.go
- master/mocktest/util.go
- master/node_selector_test.go
- master/nodeset_selector_test.go
- master/topology_test.go
- master/vol_test.go
- proto/admin_proto.go
- proto/admin_proto_test.go
- proto/auth_proto.go
- sdk/master/client.go
- snapshot/cmd/common.go
parse http response in proto.HTTPReplyRaw
fixes #
```release-note
```
> chore(proto): parse http response in proto.HTTPReplyRaw

- docker/docker-compose.yml
- docker/run_docker.sh
* Support run CI test on podman.
fixes #
* It is better to change nginx ports to `8080`(or any >= 1024 port).
```release-note
```
> [Feature]: CI tests support run on podman

- Makefile
> [Build]: Add makefile rule to build in docker

- master/multi_ver_snapshot.go
- master/vol.go
…uring the deletion of data processing
Ohterwise,if the master goes down, it may cause to crash because it's in the raft apply process
> enhance(master):Forbit parrallel check volume's status

- cli/cmd/const.go
- cli/cmd/vol.go
- docs-zh/source/maintenance/admin-api/master/volume.md
- docs/source/maintenance/admin-api/master/volume.md
- master/api_args_parse.go
- master/api_service.go
- master/cluster.go
- master/cluster_test.go
- master/const.go
- master/gapi_volume.go
- master/vol.go
- sdk/graphql/client/volume/client.go
- sdk/master/api_admin.go
set dpCount when create volume
fixes #2978
```release-note
```
> feat(dp): set dpCount when create volume

- Makefile
- docker/docker-compose.yml
- docker/run_docker.sh
1、use variables in docker yml
2、CI tests support run on podman
fixes #
```release-note
```
> chore(docker): use variables in docker yml

- objectnode/auth_signature_chunk_test.go
- objectnode/auth_signature_v2.go
- objectnode/auth_signature_v4.go
- objectnode/cors.go
- objectnode/cors_handler.go
- objectnode/policy.go
- objectnode/policy_action.go
- objectnode/policy_condition.go
- objectnode/policy_ipaddressop_test.go
- objectnode/policy_statement.go
- objectnode/policy_statement_test.go
- objectnode/policy_stringlikeop_test.go
- objectnode/policy_stringset_test.go
- objectnode/policy_valueset_test.go
> refactor(object): add CubeFS's statement comment

- lcnode/const.go
- lcnode/lc_scanner.go
- lcnode/server.go
1. add debug service
fixes #
```release-note
```
> enhance(lcnode): [hybrid cloud] lifecycle transition

- metanode/api_handler.go
- metanode/const.go
- metanode/inode.go
- metanode/partition.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_inode.go
- proto/fs_proto.go
feat(meta): [hybrid cloud] provide an API to modify inode's ctime, for debug/test purpose.
> feat(meta): [hybrid cloud] provide an API to modify inode's ctime, for debug/test purpose.

- blobstore/scheduler/config.go
- blobstore/scheduler/volume_inspector.go
- blobstore/scheduler/volume_inspector_test.go
> feat(scheduler): add sealed vid cache for inspect process of scheduler

- docs-zh/source/maintenance/configs/blobstore/cm.md
- docs/source/maintenance/configs/blobstore/cm.md
> docs(blobstore): update config documentation for blobstore

- cli/cmd/fmt.go
- master/api_service.go
- master/metadata_fsm_op.go
- master/vol.go
- proto/admin_proto.go
Updated the volume information query interface to show the current delayed deletion time of the volume
fixes #
```release-note
```
> Updated the volume information query interface to show the current delayed deletion time of the volume

- docs-zh/source/maintenance/configs/blobstore/cm.md
- docs-zh/source/quick-start/verify.md
- docs-zh/source/user-guide/blobstore.md
- docs/source/maintenance/configs/blobstore/cm.md
- docs/source/user-guide/blobstore.md
update deploy documentation for blobstore
fixes #
```release-note
```
> docs(blobstore): update deploy documentation for blobstore

- datanode/partition_op_by_raft.go
fix datanode raft snapshot exceed the limit
close: #2738
> bugfix(datanode):fix datanode raft snapshot exceed the limit

- lcnode/lc_scanner.go
- lcnode/meta.go
- lcnode/meta_test.go
- metanode/partition_op_inode.go
- proto/fs_proto.go
- proto/packet.go
- sdk/meta/api.go
- sdk/meta/operation.go
- util/auditlog/auditlog.go
add audit log for migration in metanode
> feature(metanode):add audit log for migration

- lcnode/lc_transition.go
- lcnode/server.go
> enhance(lcnode): [hybrid cloud] fix lcnode log

- blobstore/common/proto/proxy.go
- blobstore/scheduler/blob_deleter.go
roll back to init stage, when err is shard not mark delete
fixes #
```release-note
```
> fix(scheduler): roll back to init stage, when err is shard not mark delete

- metanode/inode.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/partition_op_inode.go
> bugfix(metanode): fix writeGen rollback to 0

- blobstore/api/blobnode/worker.go
- blobstore/blobnode/task_shard_repair_test.go
- blobstore/blobnode/worker_service_test.go
fix codec to handle eof error for use partial repair
fixes #
```release-note
```
> fix(blobnode): fix codec to handle eof error

- datanode/disk.go
- datanode/partition.go
- datanode/wrap_operator.go
- master/metadata_fsm_op.go
- master/topology.go
- sdk/data/stream/stream_writer.go
> add recent commits to 3.3.1.

- GOVERNANCE.md
- blobstore/common/raftserver/server_test.go
- datanode/data_partition_repair.go
- datanode/partition.go
- datanode/partition_op_by_raft.go
- datanode/wrap_operator.go
- datanode/wrap_post.go
- datanode/wrap_prepare.go
- master/api_service_test.go
- metanode/manager_op.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/sorted_extents.go
- proto/extent_key.go
- repl/packet.go
- sdk/data/stream/extent_client.go
- sdk/data/stream/extent_handler.go
- sdk/data/stream/extent_reader.go
- sdk/data/stream/stream_conn.go
- sdk/data/stream/stream_writer.go
- sdk/data/wrapper/wrapper.go
- sdk/meta/api.go
- sdk/meta/conn.go
- sdk/meta/meta.go
- sdk/meta/operation.go
> snapshot issue && maintainer rules && security improvement

- client/fuse.go
- master/api_service_test.go
- master/cluster.go
- master/cluster_task.go
- master/const.go
- master/gapi_volume.go
- master/metadata_fsm_op.go
- master/monitor_metrics.go
- master/vol.go
- proto/status.go
exit when volume has been marked delete
fixes #
```release-note
```
> exit when volume has been marked delete

- docker/run_docker.sh
> [Chore]: Build in docker support go build cache

- cli/cmd/vol.go
> refactor(cli): remove pasue flag in transaction flag hint.

- metanode/dentry.go
- metanode/extend.go
- metanode/inode.go
- metanode/manager_op.go
- metanode/meta_quota_manager.go
- metanode/multi_ver_test.go
- metanode/multipart.go
- metanode/partition.go
- metanode/partition_delete_extents.go
- metanode/partition_free_list.go
- metanode/partition_fsm.go
- metanode/partition_fsmop.go
- metanode/partition_fsmop_dentry.go
- metanode/partition_fsmop_extend.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_dentry.go
- metanode/partition_op_extent.go
- metanode/partition_op_inode.go
- metanode/partition_op_quota.go
- metanode/partition_op_uniq_test.go
- metanode/partition_store.go
- metanode/sorted_extents.go
- metanode/transaction.go
> Refactor the output format of variables in logs

- metanode/manager_op.go
- sdk/meta/operation.go
add debug log to check opMetaExtentsList value
> enhance(client,metanode): add debug log to check opMetaExtentsList value

- lcnode/lc_op.go
- lcnode/lc_scanner.go
- master/api_service.go
> enhance(lcnode): [hybrid cloud] add start time in heartbeat

- docker/run_docker.sh
* Fix go build cache support in `make docker`.
```release-note
```
> [Chore]: fix `get_go_build_cache`

- libsdk/libsdk.go
- metanode/const.go
- metanode/manager.go
- metanode/manager_op.go
- metanode/partition.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_extend.go
- metanode/partition_op_extend.go
- proto/fs_proto.go
- proto/packet.go
- sdk/meta/api.go
- sdk/meta/operation.go
support dir lock
fixes #
```release-note
```
> fix(libsdk,meta): support dir lock

- master/api_service_test.go
- master/vol_test.go
fix the unit test problem of testCreateColdVol.
fixes #
```release-note
```
> fix(master):fix the unit test problem of testCreateColdVol.

- MAINTAINERS.md
Update maintains according to rules of maintainer
> update(docs):Update maintainers

- cli/cmd/datanode.go
- cli/cmd/fmt.go
- cli/cmd/metanode.go
- master/api_service.go
- master/cluster.go
- master/cluster_stat.go
- master/gapi_cluster.go
- proto/model.go
- sdk/data/wrapper/wrapper.go
fixes #3017 
```release-note
```
> [fix]: use original NodeStatInfo field type to adapt old services

- README.md
> Update(docs):Add offical twitter link

- blobstore/access/stream.go
- blobstore/access/stream_mock_test.go
- blobstore/access/stream_put.go
- blobstore/access/stream_put_test.go
- blobstore/api/blobnode/shard.go
- blobstore/blobnode/core/chunk/chunk.go
- blobstore/blobnode/core/chunk/chunk_test.go
- blobstore/blobnode/core/disk/disk_test.go
- blobstore/blobnode/core/proto.go
- blobstore/blobnode/core/storage/storage.go
- blobstore/blobnode/core/storage/storage_cp.go
- blobstore/blobnode/core/storage/storage_test.go
- blobstore/blobnode/disk_mock_test.go
- blobstore/blobnode/shard.go
access module force delete blob msg, remove proxy kafka delete and repair msg
blobnode module support force delete, if bid is not exist, it also successful
fixes #
```release-note
```
> feat(access): delete blob msg, remove proxy kafka delete and repair msg

- blobstore/access/controller/bidmgr.go
- blobstore/access/controller/metric_task.go
- blobstore/access/controller/retain_volume_task.go
- blobstore/access/controller/volumeinfo.go
- blobstore/access/controller/volumemgr.go
porting proxy's volume management code, modify to adapt access module
fixes #
```release-note
```
> feat(access): porting proxy's volume management code, modify to adapt access module

- blobstore/access/controller/allocator_mock_test.go
- blobstore/access/controller/bidmgr_test.go
- blobstore/access/controller/metric_task_test.go
- blobstore/access/controller/retain_volume_task_test.go
- blobstore/access/controller/volumeinfo_test.go
- blobstore/access/controller/volumemgr_test.go
porting proxy's allocator unit test
fixes #
```release-note
```
> test(access): porting proxy's allocator unit test

- .github/workflows/check_pull_request.yml
- blockcache/cmd.go
- cli/cli.go
- cli/cmd/cluster.go
- cli/cmd/root.go
- lcnode/server.go
- storage/extent_store.go
- util/config/config.go
- util/timeutil/time.go
- util/timeutil/time_test.go
revert from 1ee5e30e524ebadeebb63ab1cf2126f9aa56b855
#2122
fixes #
```release-note
```
> feat(ci): check pull request message

- master/api_args_parse.go
- sdk/master/api_admin.go
- sdk/master/api_client.go
- sdk/master/api_node.go
- sdk/master/api_user.go
- sdk/master/client.go
- sdk/master/request.go
- util/compressor/compressor.go
- util/compressor/compressor_test.go
- util/compressor/gzip.go
- util/compressor/gzip_test.go
Master http interface respond encoding body if client accept some encoding，now implement `gzip`
fixes #
> feat(master): http request with gzip encoding

- blobstore/access/stream.go
- blobstore/api/blobnode/shard.go
- blobstore/blobnode/service.go
- blobstore/blobnode/shard.go
1.fix the force delete api of blobnode
2.fix blocked and disk not found, when access force delete  
fixes #
```release-note
```
> fix(access,blobnode): fix the forced deletion of the access client   

- libsdk/libcfs.h
- libsdk/libsdk.go
libsdk support cfs_link, cfs_symlink
fixes #
```release-note
```
> fix(libsdk): libsdk support cfs_link, cfs_symlink

- master/api_service.go
- master/vol_test.go
fix the problem of TestCreateColdVol.
fixes #
```release-note
```
> fix(master): fix the problem of TestCreateColdVol

- metanode/const.go
- metanode/inode.go
- metanode/partition_free_list.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/partition_op_inode.go
- metanode/sorted_hybridcloud_obj_extents.go
- proto/fs_proto.go
1.  The deletion of inode support hybridcloud
2.  Delaying deletion of data before migration
> The deletion of inode and  delaying deletion of data before migration

- sdk/master/api_admin.go
- sdk/master/api_node.go
- sdk/master/client.go
- sdk/master/request.go
- util/string.go
- util/string_test.go
remove is timeout header from client
> style(sdk): remove is timeout header from client

- blobstore/scheduler/cluster_topology.go
- blobstore/scheduler/volume_inspector.go
- blobstore/scheduler/volume_inspector_test.go
add ut for inspect process of scheduler
fixes #
```release-note
```
> refactor(scheduler): add ut for inspect process of scheduler

- sdk/data/stream/extent_client.go
GetStreamer drop request in channel leadto deadlock
fixes #
```release-note
```
> fix(sdk): GetStreamer drop request in channel leadto deadlock

- metanode/const.go
- metanode/inode.go
- metanode/manager.go
- metanode/manager_op.go
- metanode/partition.go
- metanode/partition_free_list.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_inode.go
- proto/fs_proto.go
- proto/packet.go
- sdk/meta/api.go
- sdk/meta/operation.go
feature(metanode): Support deleting discard migration data
> feature(metanode): Support for deleting discard migration data

- sdk/data/stream/stream_writer.go
For better readable, put write append multi steps to single function.
> refactor(client): Put write append multi steps to single function

- master/api_service.go
- master/meta_partition.go
- master/vol.go
- metanode/manager_op.go
- metanode/multi_ver_test.go
- metanode/partition.go
- metanode/partition_fsm.go
- proto/admin_proto.go
- proto/meta_proto.go
- proto/model.go
…d size of volumes and metapartitions by storage class.
feat(master): [hybrid cloud] Support querying the inode count and used size of volumes and metapartitions by storage class.
> feat(master): [hybrid cloud] Support querying the inode count and used size of volumes and metapartitions by storage class.

- docs-zh/source/sidebarConfig.js
- docs/source/sidebarConfig.js
fix sidebarConfig bug, missing letter e
fixes #
```release-note
```
> fix(docs): fix sidebarConfig bug, missing letter e

- sdk/data/stream/stream_writer.go
flush operation appeared bad file descriptor
fixes #
```release-note
```
> fix(sdk): flush operation appeared bad file descriptor

- master/api_service.go
- master/vol.go
…impleView(), to reduce CPU overload
perf(master): move preload dp capacity calculation to the background and execute it periodically.
> perf(master): move preload dp capacity calculation to the background and execute it periodically.

- blobstore/blobnode/core/chunk/compact.go
- blobstore/blobnode/core/storage/datafile.go
- blobstore/blobnode/core/storage/datafile_test.go
- blobstore/blobnode/core/storage/metadb.go
> refactor(blobnode): some change of code style for blobnode

- master/api_service.go
While creating a volume, if blobStore  is in req.allowedStorageClass but req. ebsBlockSize is not assigned, set it to default value.
> fix(master): While creating a volume, if blobStore  is in req.allowedStorageClass but req. ebsBlockSize is not assigned, set it to default value.

- cmd/cmd.go
- metanode/api_handler.go
- metanode/manager.go
- metanode/manager_op.go
- metanode/manager_resp.go
- metanode/packet.go
- metanode/partition_op_inode.go
- metanode/server.go
- metanode/transaction.go
add tracelog in metanode http server.
fixes #
```release-note
```
> feat(tracelog): add tracelog in metanode http server

- cli/cmd/vol.go
- master/api_service.go
- master/vol.go
- sdk/master/api_admin.go
*fix(master): set ebsblockSize when add blobStore to volume's allowedStorageClass
> fix(master): set ebsblockSize when add blobStore to volume's allowedStorageClass

- sdk/data/stream/extent_client.go
- sdk/data/stream/stream_writer.go
> cherry-pick sdk change from develop-3.3.2 to Release 3.3.0

- metanode/const.go
- metanode/inode.go
- metanode/partition_free_list.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_inode.go
migration ek failed
notify follower to delete migration ek if update migration ek failed
> fix(metanode): notify follower to delete migration ek if update

- lcnode/const.go
- lcnode/lc_scanner.go
- lcnode/meta.go
- lcnode/meta_test.go
- lcnode/server.go
- sdk/meta/api.go
- sdk/meta/operation.go
support setting delayDelMinute after migration
> fix(lcnode): [hybrid cloud] set delayDelMinute after migration

- cli/cmd/vol.go
- client/fuse.go
- fsck/cmd/getInfo.go
- master/api_args_parse.go
- master/api_service.go
- master/api_service_test.go
- master/cluster.go
- master/data_partition_map.go
- master/vol.go
- metanode/partition_free_list.go
- proto/errors.go
- proto/header.go
- sdk/data/wrapper/wrapper.go
- sdk/master/client.go
1. add feature of compressing client/partitions response data
2. flush log before exiting client
fixes #
```release-note
```
> feat(master): compress client/partitions response data

- docs-zh/source/user-guide/authnode.md
- docs/source/user-guide/authnode.md
docs(authnode): add Master API Authentication
> docs(authnode): add Master API Authentication

- objectnode/policy.go
- proto/user_proto.go
cherry pick this commit from master branch to develop 3.3.2
Which issue this PR fixes:
When fuse read and write permissions are set, improve the compatibility of s3api permission verification.
> fix(objnode): s3api perm check is enhancedly compatible with fuse perm.

- datanode/const.go
- datanode/data_partition_repair.go
- datanode/partition_op_by_raft.go
- datanode/server.go
- datanode/server_handler.go
- datanode/wrap_operator.go
- fsck/cmd/common.go
- fsck/cmd/gc.go
- fsck/cmd/getInfo.go
- fsck/cmd/root.go
- fsck/main.go
- master/api_service.go
- proto/extent_key.go
- proto/packet.go
- repl/packet.go
- repl/repl_protocol.go
- storage/extent_store.go
- storage/extent_store_test.go
- util/bloom_filter.go
cherry-pick the cfs-fsck tool with garbage data scanning and cleaning functionality from the release-oppo-v3.3.1 branch.
> cherry-pick the cfs-fsck tool with garbage data scanning and cleaning functionality from the release-oppo-v3.3.1 branch.

- datanode/partition.go
fix(data): function startEvict() should not trigger panic when failed to fetch volume info from master
> fix(data): function startEvict() should not trigger panic when failed to fetch volume info from master

- master/metadata_fsm.go
- raftstore/raftstore_db/store_rocksdb.go
fixes #3145 
```release-note
```
> fix(master): avoid cross device link when apply snapshot

- master/master_manager_test.go
- master/metadata_fsm.go
- raftstore/raftstore_db/store_rocksdb.go
- util/fileutil/exists.go
- util/fileutil/exists_test.go
fixes #1916 #3145
```release-note
```
> chore(master): pick snapshot optimization to `develop-v3.3.2` 

- datanode/partition_raft.go
fix(data): when traversing the replicas slice, avoid panics caused by… changes in the slice length
> fix(data): when traversing the replicas slice, avoid panics caused by… changes in the slice length

- cli/cmd/compatibility.go
- metanode/inode.go
- metanode/partition_free_list.go
- metanode/partition_op_extent.go
- metanode/sorted_extents.go
fixes #3140
```release-note
```
> fix(meta): `GetAllExtsOfflineInode` failed to delete extent keys

- datanode/partition.go
- datanode/partition_op_by_raft.go
- datanode/partition_raftfsm.go
- datanode/wrap_operator.go
- metanode/manager_op.go
- proto/packet.go
- storage/extent.go
- storage/extent_store.go
- storage/extent_store_test.go
- storage/persistence_crc.go
1) enhance(datanode): Add testCase for snapshot crc and reconstruct some related code.
2) update(datanode): Store verlist at metadata of data partition for replay randomWrite, otherwise may trigger snapshot write inconsistent between replicas.
> fix(snapshot): Add testCase for snapshot crc  and store verlist at metadata of data partition

- datanode/const.go
- datanode/data_partition_repair.go
- datanode/partition_op_by_raft.go
- datanode/server.go
- datanode/server_handler.go
- datanode/wrap_operator.go
- fsck/cmd/common.go
- fsck/cmd/gc.go
- fsck/cmd/gc_test.go
- fsck/cmd/getInfo.go
- fsck/cmd/root.go
- fsck/main.go
- master/api_service.go
- proto/extent_key.go
- proto/packet.go
- repl/packet.go
- repl/repl_protocol.go
- storage/extent_store.go
- storage/extent_store_test.go
- util/bloom_filter.go
cherry-pick the cfs-fsck tool with garbage data scanning and cleaning functionality from the release-oppo-v3.3.1 branch.
> cherry-pick the cfs-fsck tool with garbage data scanning and cleaning functionality from the release-oppo-v3.3.1 branch. 

- cli/cmd/vol.go
- master/api_args_parse.go
- master/api_service.go
- master/meta_partition_test.go
- master/mocktest/meta_server.go
- master/vol.go
- sdk/master/api_admin.go
fixes # 2704
Support create multiple meta partitions at one time , using `cfs-cli volume add-mp [VOLUME] [NUMBER]` command
```release-note
```
> feat(metanode): Support create multiple meta partitions at one time

- lcnode/lc_transition.go
- lcnode/lc_transition_test.go
- lcnode/server.go
- sdk/data/blobstore/blobstore_client.go
multipart migration to blobstore
> fix(lcnode): [hybrid cloud] multipart migration to blobstore

- metanode/partition_free_list.go
- metanode/partition_free_list_test.go
* Meta partition delete inode file support rolling
```release-note
```
> feat(meta): delete inode file support rolling

- cli/cmd/const.go
- cli/cmd/datapartition.go
- datanode/partition.go
- datanode/wrap_operator.go
- master/api_service.go
- metanode/datapartition.go
- metanode/partition_delete_extents.go
- metanode/partition_free_list.go
- repl/packet.go
- repl/repl_protocol.go
- sdk/master/api_admin.go
- storage/extent_store.go
> chore(meta): pick dp discard commits to `develop-v3.3.3` 

- master/metadata_fsm.go
- master/metadata_fsm_test.go
- raftstore/raftstore_db/store_rocksdb.go
- raftstore/raftstore_db/store_rocksdb_test.go
fixes #3152 #3160
```release-note
```
> fix(master):  use `DeleteRange` to clear rocksdb

- lcnode/lc_transition.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_inode.go
- metanode/sorted_extents.go
- metanode/sorted_obj_extents.go
- proto/fs_proto.go
fix(metanode): support empty file migration
> fix(metanode): support empty file migration

- proto/packet.go
…de BufferPool
fixes #3156
```release-note
```
> fix(datanode): datanode high memory usage because the allocation outside the BufferPool

- master/metadata_fsm.go
- master/metadata_fsm_test.go
- raftstore/raftstore_db/store_rocksdb.go
- raftstore/raftstore_db/store_rocksdb_test.go
> chore(master): pick 2 commits to `develop-v3.3.2`

- client/fs/dir.go
- client/fs/icache.go
- metanode/forbidden_migration_list.go
- metanode/inode.go
- metanode/partition_forbidden_migration_list.go
1.inode marshall support empty file
2.update file node cache if storage class had been changed
> inode marshall support empty file and update file node cache if storage class had been changed

- metanode/partition_op_inode.go
> enhance(metanode): remove unnecessary code

- metanode/api_handler.go
- metanode/datapartition.go
- metanode/dentry.go
- metanode/metanode.go
- metanode/multi_ver_test.go
- metanode/partition_delete_extents.go
- metanode/partition_free_list.go
- metanode/partition_free_list_test.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_dentry.go
- metanode/partition_op_dentry.go
- metanode/partition_store.go
- metanode/transaction.go
- metanode/transaction_test.go
- proto/packet.go
- proto/packet_test.go
log trace into meta partition
fixes #
```release-note
```
> chore(metanode): trace into meta partition

- metanode/partition_delete_extents.go
fixes #3169
```release-note
```
> feat(meta): batch delete extents when truncate file

- objectnode/api_handler_multipart.go
- objectnode/api_middleware.go
- objectnode/auth.go
1. Fix sts auth process and signatureIgnoredActions configuration
2. PartNumber of multipart must not be greater than 10000
fixes #
```release-note
```
> fix(object): adjust sts auth and partNumber fix

- client/fs/dcachev2.go
- client/fs/icache.go
- client/fs/inode.go
- client/fs/super.go
- client/fuse.go
Replace the log package in fuse that does not require trace
```release-note
```
> chore(fuse): replace log package:where no need trace log

- metanode/partition_free_list.go
- metanode/partition_free_list_test.go
> chore(meta): pick inode delete file rolling to `develop-v3.3.3`

- master/api_args_parse.go
- master/api_service.go
- master/cluster.go
- master/data_partition.go
- master/metadata_fsm_op.go
- master/server.go
enhance for dataparition decommission from release-3.3.2
> feat(master): enhance for dataparition decommission from release-3.3.2

- datanode/data_partition_repair.go
- datanode/disk.go
- datanode/limit_io.go
- datanode/metric.go
- datanode/nodeinfo.go
- datanode/partition.go
- datanode/partition_op_by_raft.go
- datanode/partition_raft.go
- datanode/partition_raftfsm.go
- datanode/server.go
- datanode/server_handler.go
- datanode/space_manager.go
- datanode/wrap_operator.go
- datanode/wrap_prepare.go
- repl/packet.go
- storage/extent.go
- storage/extent_store.go
- storage/fallocate_darwin.go
- storage/fallocate_windows.go
- storage/persistence_crc.go
use blobstore log instead of cubefs in datanode
fixes #
```release-note
```
> chore(datanode): use blobstore log instead of cubefs

- client/fuse.go
- proto/mount_options.go
MountOption add parameter DisableMountSubtype
fixes #
```release-note
```
> fix(fuse): MountOption add parameter DisableMountSubtype

- lcnode/const.go
- lcnode/lc_op.go
- lcnode/server.go
- lcnode/snapshot_scanner.go
- master/lifecycle_manager.go
- master/metadata_fsm_op.go
- master/snapshot_manager.go
fix lcnode panic and reduce task allocation time
> fix(lcnode): fix lcnode panic and reduce task allocation time

- fsck/cmd/common.go
- fsck/cmd/gc.go
- metanode/inode.go
- metanode/sorted_hybridcloud_obj_extents.go
feat(fsck): support scanning  migrate-extent garbage
> feat(fsck): support scanning  migrate-extent garbage

- util/auditlog/auditlog.go
- util/auditlog/auditlog_test.go
> chore(util): pick audit log recycle feature to `develop-v3.3.2`

- metanode/partition_op_extend.go
> fix(meta): Protect MetaPartition UpdateXAttr interface

- master/data_partition.go
- master/data_partition_check.go
- master/meta_partition.go
- sdk/master/client.go
some enhance feature for datapartition decommission
> feat(datanode): enhance for datapartition decommission

- cli/api/metaapi.go
- cli/cli.go
- cli/cmd/compatibility.go
- cli/cmd/root.go
- metanode/inode.go
- metanode/partition_fsmop_extend.go
- proto/extent_key.go
- proto/lifecycle.go
- proto/model.go
- proto/packet.go
- proto/transaction.go
- repl/packet.go
- repl/repl_protocol.go
logging into proto functions
fixes #
```release-note
```
> chore(proto): logging into proto functions

- client/fs/file.go
- client/fs/inode.go
- client/fs/super.go
- sdk/data/blobstore/blobstore_client.go
- sdk/data/blobstore/reader.go
- sdk/data/blobstore/reader_test.go
- sdk/data/blobstore/writer.go
- sdk/data/blobstore/writer_test.go
- sdk/data/stream/extent_cache.go
- sdk/data/stream/extent_client.go
- sdk/data/stream/extent_handler.go
- sdk/data/stream/extent_reader.go
- sdk/data/stream/stream_conn.go
- sdk/data/stream/stream_reader.go
- sdk/data/stream/stream_writer.go
> chore(sdk): add trace log to sdk/data

- master/api_service.go
- master/vol_test.go
Modify the execution order of deletion after freezing to avoid possible early deletion pitfalls.
fixes #
```release-note
```
> fix(master): Modify the execution order of deletion after freezing to avoid possible early deletion pitfalls.

- metanode/partition_free_list.go
- metanode/partition_free_list_test.go
- util/fileutil/stat.go
- util/fileutil/stat_test.go
- util/fileutil/statfs.go
- util/fileutil/statfs_test.go
fixes #3194 
```release-note
```
> fix(meta): limit the count of metanode inode audit log

- client/fs/dir.go
- client/fs/file.go
- sdk/data/stream/extent_client.go
> chore(client): update log package of client

- blobstore/common/trace/span.go
- blobstore/common/trace/span_context.go
- blobstore/common/trace/span_options.go
- blobstore/common/trace/span_test.go
- blobstore/common/trace/tracer.go
- blobstore/common/trace/tracer_options.go
- blobstore/common/trace/tracer_test.go
trace prefer to format track log
fixes #3223 #3224
```release-note
```
> perf(common): trace prefer to format track log

- client/fs/dir.go
- client/fs/file.go
- libsdk/libsdk.go
- proto/packet.go
- proto/packet_test.go
- sdk/meta/api.go
- sdk/meta/conn.go
- sdk/meta/operation.go
> feat(metasdk): add some span methods to packet

- cli/cmd/acl.go
- cli/cmd/cluster.go
- cli/cmd/compatibility.go
- cli/cmd/config.go
- cli/cmd/datanode.go
- cli/cmd/datapartition.go
- cli/cmd/disk.go
- cli/cmd/http_service.go
- cli/cmd/metanode.go
- cli/cmd/metapartition.go
- cli/cmd/nodeset.go
- cli/cmd/quota.go
- cli/cmd/root.go
- cli/cmd/uid.go
- cli/cmd/user.go
- cli/cmd/valid.go
- cli/cmd/version.go
- cli/cmd/vol.go
- cli/cmd/zone.go
> chore(cli): feed context todo in commands

- sdk/meta/api.go
- sdk/meta/meta.go
- sdk/meta/operation.go
- sdk/meta/quota_cache.go
- sdk/meta/transaction.go
- sdk/meta/transaction_helper.go
- sdk/meta/view.go
with #21965653
fixes #
```release-note
```
> chore(metasdk): replace cubefs log with blobstore log

- client/fs/dir.go
- client/fs/file.go
- client/fs/inode.go
- client/fs/super.go
- libsdk/libsdk.go
- metanode/partition_free_list.go
- objectnode/fs_volume.go
- preload/sdk/preloadsdk.go
- sdk/data/blobstore/blobstore_client.go
- sdk/data/blobstore/reader.go
- sdk/data/blobstore/reader_test.go
- sdk/data/blobstore/writer.go
- sdk/data/blobstore/writer_test.go
- sdk/data/manager/limiter.go
- sdk/data/stream/extent_client.go
- sdk/data/stream/extent_handler.go
- sdk/data/stream/stream_reader.go
- sdk/data/stream/stream_writer.go
- sdk/data/wrapper/data_partition.go
- sdk/data/wrapper/data_partition_selector.go
- sdk/data/wrapper/default_random_selector.go
- sdk/data/wrapper/k_faster_random_selector.go
- sdk/data/wrapper/wrapper.go
- sdk/meta/operation.go
with #21965653
fixes #
```release-note
```
> chore(sdk): complete trace log in client and sdk/data

- objectnode/api_handler_bucket.go
- objectnode/api_handler_multipart.go
- objectnode/api_handler_object.go
- objectnode/result.go
- objectnode/result_error.go
1. fix tagging config verification
2. fix request parts check in complete multipart
fixes #
```release-note
```
> fix(object): fix tagging config verification and request parts check in complete multipart

- blockcache/bcache/client.go
- blockcache/bcache/manage.go
- blockcache/bcache/packet.go
- blockcache/bcache/service.go
- blockcache/cmd.go
- client/fs/super.go
- sdk/data/blobstore/blobstore_client_test.go
- sdk/data/blobstore/reader.go
- sdk/data/blobstore/reader_test.go
- sdk/data/blobstore/writer_test.go
- sdk/data/stream/extent_client.go
- sdk/data/stream/stream_reader.go
- sdk/data/stream/stream_writer.go
with #21974670
logging with trace log in block cache
fixes #
```release-note
```
> chore(bcache): logging with trace log in block cache

- authnode/api_service.go
- authnode/authnode_manager.go
- authnode/cluster.go
- authnode/http_server.go
- authnode/keystore_fsm.go
- authnode/keystore_fsm_op.go
- authnode/server.go
- deploy/deploy_cli.go
- fsck/cmd/clean.go
- raftstore/monitor.go
- raftstore/raftstore_db/store_rocksdb.go
- snapshot/cmd/clean.go
with #21965811
logging with trace log in common
fixes #
```release-note
```
> chore(common): logging with trace log in common

- blobstore/access/controller/cluster.go
- blobstore/access/controller/volume.go
- blobstore/access/controller/volume_test.go
- blobstore/access/controller/volumemgr.go
- blobstore/access/controller/volumemgr_test.go
- blobstore/access/stream.go
- blobstore/access/stream_alloc.go
- blobstore/access/stream_loop.go
- blobstore/access/stream_loop_test.go
- blobstore/access/stream_mock_test.go
- blobstore/access/stream_put.go
1.optimize the process: seal the volume at background when the write failed
2.optimize some functions and variable naming, and add read volume cache configuration
fixes #
I will merge it into one commit, after review is completed
```release-note
```
> feat(access): optimize the process: seal the volume at background when the write failed

- blobstore/util/log/log.go
- blobstore/util/log/log_test.go
change log level with name
fixes #
```release-note
```
> style(util): change log level with name

- master/cluster.go
- master/mocktest/data_server.go
- master/mocktest/meta_server.go
- proto/packet.go
- proto/packet_test.go
- util/log/log.go
with #21965811
transfer trace id to request id in packet
fixes #
```release-note
```
> chore(common): transfer trace id to request id in packet

- proto/packet.go
- sdk/meta/operation.go
with #21965653
fixes #
```release-note
```
> chore(metasdk): add trace id to requst id of sdk of meta

- objectnode/result.go
listobjectv2 IsTruncated required
> fix(object): listobjectv2 IsTruncated required

- sdk/data/stream/extent_client.go
- sdk/data/stream/stream_reader.go
- sdk/data/stream/stream_writer.go
> fix(sdk): one streamer has multi server maybe leadto bad file descriptor

- sdk/data/stream/stream_writer.go
fix write qos of hot volume
fixes #3287
```release-note
```
> fix(client): write qos of hot volume

- cli/cmd/disk.go
- cli/cmd/fmt.go
- cli/cmd/util.go
- cli/cmd/util_test.go
with #21965811
fixes #
```release-note
```
> feat(cli): auto format struct and table

- sdk/data/stream/extent_client.go
> fix(sdk): EvictStream leadto deadlock

- sdk/data/stream/extent_handler.go
> fix(sdk): fix ek conflict error

- .github/pull_request_template.md
- PR title format should be *type(scope): subject*. For details, see *[Pull Request Title](https://github.com/cubefs/cubefs/blob/master/.github/workflows/check_pull_request.yml)*.
- Each pull request should address only one issue, not mix up code from multiple issues.
- Each commit in the pull request has a meaningful commit message. For details, see *[Commit Message](https://github.com/cubefs/cubefs/blob/master/.github/workflows/check_pull_request.yml)*.
- Fill out the template below to describe the changes contributed by the pull request. That will give reviewers the context they need to do the review.
- Once all items of the checklist are addressed, remove the above text and this checklist, leaving only the filled out template below.
> Either this PR fixes an issue,
Fixes: #3305
> or …
> chore(doc): improve pull request template content

- datanode/partition.go
- datanode/partition_raft.go
- datanode/space_manager.go
- sdk/data/wrapper/wrapper.go
- util/buf/buffer_pool.go
> fix(datanode): fix some typo error

- cli/cmd/disk.go
- cli/cmd/fmt.go
- datanode/space_manager.go
- master/api_service.go
- master/data_node.go
- master/http_server.go
- proto/admin_proto.go
- proto/errors.go
- proto/model.go
- proto/status.go
- sdk/master/api_admin.go
- sdk/master/api_client.go
fixes #1895
```release-note
```
> feat(cli): cfs-cli add functionality to show disk info

- CHANGELOG.md
- docs-zh/source/maintenance/configs/master.md
- docs-zh/source/tools/cfs-cli/cluster.md
- docs-zh/source/tools/cfs-cli/volume.md
- docs-zh/version.json
- docs/source/maintenance/configs/master.md
- docs/source/tools/cfs-cli/cluster.md
- docs/source/tools/cfs-cli/volume.md
- docs/version.json
1. update change log.
2. add doc for volume delay deletion.
> Either this PR fixes an issue,
> Explain here the context, and why you're making that change. What is the problem you're trying to solve.
--------------
blaaaaa
> Describe the modifications you've done.
-----------------
``` text
blaaaaa
```
> Show in a checkbox-style, the expected types of changes your project is supposed to have:
--------------------
- [x ] Documentation Update (if none of the other choices apply)
> *(Please pick either of the following options.)*
-------------------------
- [ x] Make sure that the change passes the testing checks.
*(or)*
*(or)*
This …
> docs(docs): add docs about v3.3.2.

- .github/workflows/check_pull_request.yml
- .github/workflows/scorecard.yml
> Explain here the context, and why you're making that change. What is the problem you're trying to solve.
--------------
update scorecard analysis action yaml
> Describe the modifications you've done.
-----------------
> Show in a checkbox-style, the expected types of changes your project is supposed to have:
--------------------
> *(Please pick either of the following options.)*
-------------------------
> Which of the following parts are affected by this change?
-------------------------------------------------------------------------
> Is there a chinese and english document modification?
-----------------
> How long would you like the team to be completed in your contributing?
--------------------
> enter the …
> docs(action): update scorecard analysis action yaml

- client/fs/dir.go
- client/fs/file.go
- client/fs/inode.go
- lcnode/const.go
- lcnode/lc_scanner.go
- lcnode/server.go
- lcnode/snapshot_scanner.go
- libsdk/libsdk.go
- master/cluster.go
- master/lifecycle_task.go
- master/snapshot_manager.go
- metanode/api_handler.go
- metanode/inode.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extent.go
- metanode/partition_op_inode.go
- metanode/sorted_hybridcloud_obj_extents.go
- proto/fs_proto.go
- proto/packet.go
- sdk/data/stream/extent_cache.go
- sdk/data/stream/extent_client.go
- sdk/data/stream/extent_handler.go
- sdk/data/stream/extent_reader.go
- sdk/data/stream/stream_conn.go
- sdk/data/stream/stream_reader.go
- sdk/data/stream/stream_writer.go
- sdk/data/wrapper/default_random_selector.go
erge changes from oppo/develop-hybridcloud-lifecycle
> merge changes from oppo/develop-hybridcloud-lifecycle

- .github/pull_request_template.md
change tips of pull request template as comment.
``` text
content anything.
```
> docs(template): change tips of pull request template as comment

- docs-zh/source/deploy/yum.md
- docs/source/deploy/yum.md
update rpm version for yum deploy.
``` text
depoly docs.
```
- [x ] Documentation Update (if none of the other choices apply)
- [ x] Make sure that the change passes the testing checks.
- [x ] Anything that affects deployment
- [x ] `doc-complete` 
- [x ] `free-time`
> docs(docs): update rpm version from 3.3.0 to 3.3.2.

- CONTRIBUTING.md
Update the document of contributing, demonstrate contributor activity and recruitment.
``` text
Update the document of contributing
```
> feat(doc): Update the document of contributing

- ROADMAP.md
``` text
Update certain fields in the document to provide more accurate descriptions
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Update the document of the roadmap

- blobstore/common/rpc/auditlog/prometheus_metric.go
fix metric to microsecond of response duration.
``` text
service_response_duration_ms_*
```
> fix(blobstore): fix metric to microsecond of response duration

- ADOPTERS.md
``` text
Update the document of adopters
```
*(example:)*
*(or)*
> feat(doc): Update the document of adopters

- sdk/data/stream/extent_handler.go
The necessary repairs will be synchronized to version 3.3.1 in the near future.
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(adk): revert fix ek conflict error. 

- metanode/partition_op_extent.go
Fixes: #3373 
return OpNotExistErr instead of OpErr when inode does not exist, so that ShouldRetry return false when file is deleted while writing
``` text
change OpErr to OpNotExistErr in CheckQuota when inode not exist
```
- Bugfix (non-breaking change which fixes an issue)
*(or)*
*(or)*
*(example:)*
*(or)*
- MetaNode
- `doc-not-needed` 
- `whenever`
PR …
> fix(metanode): do not retry if inode does not exist

- MAINTAINERS.md
Fixes: no
Main Issue: no
I contributed a lot of code to the CubeFS. In the meantime, I've reviewed at a lot of PRs too. I want to add myself(Shuqiang Zheng) as a committer to do more things.
In the future, I would first like to see the project code improve stability and security by continuously optimizing legacy issues. Then I will consider improving its performance and scalability, for example by providing support for rdma to improve communication performance.
This year, I'm also looking forward to more areas of progress with CubeFS.
PRs: https://github.com/cubefs/cubefs/pulls?page=1&q=is%3Apr+author%3Ashuqiang-zheng
Reviews: https://github.com/pulls?q=is%3Apr+reviewed-by%3Ashuqiang-zheng+is%3Aclosed
``` text
Update the maintainers documentation.
```
This change is a trivial rework / …
> feat(doc): Add Shuqiang Zheng to be a committer.

- Release.md
- depends/Readme.md
Add documentation of dependency details 
``` text
Add depends/Readme.md  according to go.mod and indicate CNCF projects
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Add the documentation of dependency details

- RELEASE.md
- ROADMAP.md
- Update the document of the roadmap as the branch name has been changed
- update the documentation for Release.md as its filename's capitalization does not match other .md files, and add more detailed information.
``` text
- Update the document of the roadmap as the branch name has been changed
- update the documentation for Release.md as its filename's capitalization does not match other .md files, and add more detailed information.
```
*(or)*
*(or)*
*(example:)*
- *This can be realized in a mocked environment, like a test …
> feat(doc): Update the document of the roadmap.md and release.md

- GOVERNANCE.md
…rocesses
In particular, improve the necessary requirements and decision-making process for becoming a committer or maintainer.
Correct minor issues and clarify certain decision-making processes，In particular, improve the necessary requirements and decision-making process for becoming a committer or maintainer.
> feat(doc): Correct minor issues and clarify certain decision-making processes

- authnode/api_service.go
- authtool/authtool.go
- cli/cli.go
- cli/cmd/cluster.go
- cli/cmd/config.go
- cli/cmd/const.go
- cli/cmd/datanode.go
- cli/cmd/datapartition.go
- cli/cmd/http_service.go
- cli/cmd/metanode.go
- cli/cmd/metapartition.go
- cli/cmd/user.go
- cli/cmd/vol.go
- datanode/server.go
- master/api_args_parse.go
- master/cluster.go
- master/const.go
- master/http_server.go
- master/server.go
- metanode/const.go
- metanode/metanode.go
- proto/auth_proto.go
- proto/errors.go
- sdk/auth/client.go
- sdk/master/api_admin.go
- sdk/master/api_node.go
- sdk/master/api_user.go
- sdk/master/client.go
- util/keystore/keystore.go
add authentication for master admin api 
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(auth): add authentication for master admin api

- CONTRIBUTING.md
improving the developer process.
> chore(doc): improving the developer process

- gosdk/cfs_client.go
Fixes: #3419
Main Issue: #3419
provide user mode interface of go language
``` text
provide user mode interface of go language
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(sdk): add gosdk. #3419

- metanode/partition.go
…elease memory when deletePartition
Fixes: #xyz
blaaaaa
``` text
func (mp *metaPartition) Reset() (err error) {
-       mp.inodeTree.Reset()
mp.dentryTree.Reset()
+       mp.inodeTree.Reset()
+       mp.extendTree.Reset()
+       mp.multipartTree.Reset()
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(metanode): metaPartition Reset, extendTree multipartTree Reset, release memory when deletePartition

- blobstore/access/server_test.go
- blobstore/common/errors/access.go
refactor error code to 4xx
``` text
common/error/access.go
```
> refactor(access): change access request limited to 4xx

- RELEASE.md
Update the release documentation and add docker image info
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Update the release documentation and add docker image info

- blobstore/access/controller/volume.go
- blobstore/access/controller/volume_test.go
- blobstore/blobnode/heartbeat.go
- blobstore/clustermgr/disk.go
- blobstore/clustermgr/diskmgr/diskmgr.go
- blobstore/clustermgr/volumemgr/volumeunit.go
- blobstore/common/rpc/client.go
- blobstore/common/rpc/context.go
- blobstore/common/rpc/proto.go
- blobstore/common/taskswitch/task_switch.go
- blobstore/common/trace/span_options.go
- blobstore/scheduler/migrate.go
- blobstore/scheduler/migrate_test.go
- util/errors/panichook.go
- util/string.go
> chore(blobstore): merge version 1.4.1

- GOVERNANCE.md
feat(doc): Update the governance documentationa
- Clearify the promotion and exit rules for committers.
- Add the Expectations for maintainer and committers
- Clearify the core maintainers
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Update the governance documentation

- docker/run_docker.sh
``` text
fix(docker): Update docker-compose to docker compose to adapt to github unbuntu env change
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(docker): Update docker-compose to docker compose to adapt to github unbuntu env change

- GOVERNANCE.md
- MAINTAINERS.md
Update some maintainer's Affiliation information
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Update Sub-project rules and update maintainer info

- blobstore/scheduler/service.go
- blobstore/scheduler/service_test.go
Fixed the problem where the scheduler module background task reclaim failed and caused the task to be blocked.
``` text
when task excute failed, scheduler reclaim volume unit from clustermgr with source vuid not dest vuid
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(scheduler): reclaim from clustermgr with source vuid

- security/CubeFS-self-assessment.md
- security/security-release-process.md
``` text
feat(doc): Add CubeFS-self-assessment.md
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Add CubeFS-self-assessment.md

- blobstore/api/clustermgr/volume.go
- blobstore/common/proto/const.go
- util/string.go
incorrect conversion between integer types
``` text
see https://github.com/cubefs/cubefs/security/code-scanning
```
> fix(util): incorrect conversion between integer types

- authnode/authnode_manager.go
- authnode/config.go
- authnode/server.go
- cli/cmd/vol.go
- datanode/server.go
- datanode/server_handler.go
- metanode/dentry.go
- metanode/inode.go
- metanode/meta_quota_manager.go
- proto/transaction.go
incorrect conversion between integer types and slice memory allocation with excessive size value
``` text
see https://github.com/cubefs/cubefs/security/code-scanning
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(security): fix issues of incorrect conversion between integer types and slice memory allocation with excessive size value

- metanode/dentry.go
- metanode/inode.go
- metanode/meta_quota_manager.go
- proto/errors.go
incorrect conversion between integer types and slice memory allocation with excessive size value
``` text
see https://github.com/cubefs/cubefs/security/code-scanning
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(security): slice memory allocation with excessive size value. 

- console/service/file.go
Fixes: #xyz
fix uncontrolled data used in network request
``` text
see https://github.com/cubefs/cubefs/security/code-scanning
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(sdk): fix Uncontrolled data used in network request

- shell/genIp.sh
It can be very confued without tips while the interface name is misspelled or even forgot to change the default value 'bond0'.
> feat(build): check interface exist before use

- client/fs/super.go
- docker/run_docker.sh
- sdk/data/stream/extent_client.go
- sdk/data/stream/stream_remote_cache.go
Fixes: #xyz
optimize get inode meta info when prepareCacheRequests
``` text
optimize get inode meta info when prepareCacheRequests
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(flashcache): optimize get inode meta info when prepare requests

- blobstore/clustermgr/diskmgr/alloc_test.go
- blobstore/clustermgr/diskmgr/diskmgr.go
with #22565373
Fixes: #xyz
allocChunks failure causes concurrency issues
``` text
fix cm AllocChunks failure causes concurrency issues
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(clustermgr): fix cm AllocChunks failure causes concurrency issues

- README.md
CubeFS completed the OpenSSF silver badge assessment and updated the OpenSSF Best Practices badge from 'pass' to 'silver'.
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Update OpenSSF Best Practices to silver badge

- docs-zh/source/deploy/yum.md
- docs/source/deploy/yum.md
commit message
Fixes: #3524
Main Issue: #3524
support yum deployment under ARM architecture
``` text
I make an rpm package for ARM architecture and add some instructions to yum.md, now you can install it according to the documentation
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Add instructions for yum deployment under arm architecture

- MAINTAINERS.md
Update the information of the maintainer members
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Update the information of the maintainer members

- docs-zh/source/feature/trash.md
- docs-zh/source/quickstart/cluster-deploy.md
- docs/source/feature/trash.md
- docs/source/quickstart/cluster-deploy.md
Fixes: #3537 
Main Issue: #3537 
Add some details and problem solutions to cluster-deploy.md.By the side, Based on the last submission, the command for MD5 encryption was added to the trash document.
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(docs): Add some details and problem solutions to cluster-deploy.md

- docs-zh/source/ops/capacity.md
- docs-zh/source/ops/zone.md
- docs/source/ops/capacity.md
- docs/source/ops/zone.md
Fixes: #3543 
Main Issue: #3543 
Correct some incomprehensible parts of the ops documentation and modifie some text descriptions
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(docs): Revise capacity.md and zone.md to be easier to understand

- docs-zh/source/dev-guide/admin-api/master/cluster.md
- docs-zh/source/dev-guide/admin-api/master/failureDomain.md
- docs-zh/source/dev-guide/admin-api/master/user.md
- docs-zh/source/dev-guide/admin-api/master/volume.md
- docs-zh/source/dev-guide/admin-api/metanode/dentry.md
- docs-zh/source/dev-guide/admin-api/metanode/inode.md
- docs-zh/source/dev-guide/admin-api/metanode/partition.md
- docs/source/dev-guide/admin-api/master/failureDomain.md
- docs/source/dev-guide/admin-api/master/user.md
- docs/source/dev-guide/admin-api/master/volume.md
- docs/source/dev-guide/admin-api/metanode/dentry.md
- docs/source/dev-guide/admin-api/metanode/inode.md
- docs/source/dev-guide/admin-api/metanode/partition.md
Fixes: #3549
Main Issue: #3549
Modify the details of the documentation in the dev-guide section，correct some typographical errors
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(docs): Modify the details of the documentation in the dev-guide section

- docker/run_docker.sh
- metanode/partition_fsm.go
- metanode/partition_fsmop_inode.go
Fixes: #xyz
blaaaaa
``` text
blaaaaa
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(metanode): if clusterEnableSnapshot is not enbale, do not apply VersionOp

- docs-zh/source/ops/configs/blobstore/access.md
- docs-zh/source/user-guide/blobstore.md
- docs/source/ops/configs/blobstore/access.md
- docs/source/user-guide/blobstore.md
> docs(access): fix limit of access upload and download

- master/api_service.go
- metanode/inode.go
- metanode/metanode.go
- metanode/multi_ver_test.go
- metanode/partition_delete_extents.go
- metanode/partition_fsmop_inode.go
Fixes: #xyz
blaaaaa
``` text
blaaaaa
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(meta): reset reserved flag when marshal inode.

- CHANGELOG.md
- docs-zh/source/dev-guide/admin-api/master/datanode.md
- docs-zh/source/dev-guide/admin-api/master/management.md
- docs-zh/source/dev-guide/admin-api/master/meta-partition.md
- docs/source/dev-guide/admin-api/master/datanode.md
- docs/source/dev-guide/admin-api/master/management.md
- docs/source/dev-guide/admin-api/master/meta-partition.md
``` text
update changelog for v3.4.0
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): update changelog for v3.4.0

- docs-zh/version.json
- docs/version.json
Signed-off-by: chihe <chihe@oppo.com>
(cherry picked from commit 10e31d808de3eb00195bfeffa2393b23b499667a)
``` text
add version tag for doc 
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): add version tag 3.4.0 for doc

- flashnode/cachengine/engine.go
- flashnode/cachengine/lru.go
- flashnode/extent_reader.go
- flashnode/flashnode.go
- sdk/data/stream/extent_flash_cache.go
Fixes: #xyz
1.  add block createtime and print it when expired
2. flashnode enable config enableTmpfs
3. Optimize the delay of client obtaining flashnode connection
``` text
blaaaaa
```
*(or)*
*(or)*
*(example:)*
*(or)*
> perf(remotecache): Optimize the delay of client obtaining flashnode connection

- docs-zh/source/design/objectnode.md
- docs/source/design/objectnode.md
``` text
modify the path for object-system-structure.png
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(doc): modify the path for object-system-structure.png

- docs-zh/source/design/objectnode.md
- docs-zh/source/maintenance/security_practice.md
- docs-zh/source/ops/zone.md
- docs-zh/source/security/security_practice.md
- docs/source/design/objectnode.md
- docs/source/maintenance/security_practice.md
- master/data_partition.go
``` text
update path for png in docs
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(docs): update path for png in docs

- docs-zh/source/design/blobstore.md
``` text
fix path for cfs-arch-ec.png
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(doc): fix path for cfs-arch-ec.png

- docs-zh/source/maintenance/security_practice.md
- docs-zh/source/security/security_practice.md
``` text
fix path for png in security practice
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(doc): fix path for png in security practice

- blobstore/cmd/blobnode/blobnode.conf
- docs-zh/source/ops/configs/blobstore/blobnode.md
- docs-zh/source/user-guide/blobstore.md
- docs/source/ops/configs/blobstore/blobnode.md
- docs/source/user-guide/blobstore.md
blobnode: qos limit read and write bandwidth, discard overload io
This change is no code, just documents
> docs(blobnode): qos limit read and write bandwidth, discard overload io

- client/fuse.go
- master/data_node.go
- master/monitor_metrics.go
- metanode/extend.go
- metanode/multi_ver_test.go
- metanode/partition_fsm.go
- metanode/partition_fsmop_extend.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_inode.go
- metanode/partition_op_quota.go
- metanode/partition_op_uniq.go
- metanode/partition_op_uniq_test.go
- sdk/meta/trash.go
- util/exporter/exporter.go
``` text
compatible with 3.4.0 before
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(master,datanode,metanode): compatible with 3.4.0 before

- docs-zh/source/feature/autofs.md
- docs-zh/source/feature/quota.md
- docs/source/feature/autofs.md
- docs/source/feature/quota.md
Fixes: #3574 
Main Issue: #3574 
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(docs): Correct incorrect commands in quota and autofs

- docs-zh/source/feature/autofs.md
- docs-zh/source/ops/fsck.md
- docs/source/deploy/yum.md
- docs/source/feature/autofs.md
- docs/source/ops/fsck.md
Fixes: #3587
Main Issue: #3587 
``` text
add fsck tool usage documentation and modify some inaccuracies in the autofs documentation
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(docs): add fsck tool usage

- blobstore/common/raftserver/config.go
- blobstore/common/raftserver/server.go
@formatter:off
add a config for raft server, if config true follower propose will not forward to leader 
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(common): add DisableProposalForwarding config to raftserver

- blobstore/common/raftserver/wal/log_file_test.go
- blobstore/common/raftserver/wal/record_writer.go
Fixes: #xyz
raft node restart may lose 1M log
``` text
remove raft wal try flush
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(clustermgr): remove raft wal try flush

- blobstore/cli/clustermgr/list_all.go
- blobstore/clustermgr/persistence/volumedb/volumetbl.go
- blobstore/clustermgr/persistence/volumedb/volumetbl_test.go
Main Issue: #3411
see more in #3411
> fix(clustermgr): fix kvDBPath argument for blobstore-cli cm listAllDB

- docs-zh/source/design/blobstore.md
``` text
modify png path for blobstore
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(doc): modify png path for blobstore

- cmd/cmd.go
- datanode/data_partition_repair.go
- datanode/repl/repl_protocol.go
- datanode/wrap_operator.go
- depends/tiglabs/raft/transport_heartbeat.go
- depends/tiglabs/raft/transport_replicate.go
- master/api_service.go
- master/api_service_test.go
- master/cluster.go
- master/data_node.go
- master/data_partition.go
- master/monitor_metrics.go
- metanode/extend.go
- metanode/inode.go
- metanode/meta_quota_manager.go
- metanode/partition.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_quota.go
- metanode/partition_op_quota_test.go
- metanode/partition_store.go
- metanode/sorted_extents.go
- proto/packet.go
- sdk/meta/api.go
``` text
fix(all): modification recently from local
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(all): modification recently from local

- metanode/partition.go
- metanode/partition_test.go
- util/fileutil/write.go
- util/fileutil/write_test.go
> fix(metanode): fsync the crc file after wirte

- docs-zh/source/ops/fsck.md
- docs/source/ops/fsck.md
Fixes: #3627 
Main Issue: #3627 
Add fsck force clean instruction.
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(doc): Modify fsck clean instructions.

- lcnode/lc_transition.go
- objectnode/fs_volume.go
Fixes: #xyz
remove unecessary hashBuf and memroy copy operation when calculate file md5sum
``` text
blaaaaa
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(object): buffer optimization when calculate md5sum

- blobstore/common/raftserver/wal/wal.go
- blobstore/common/raftserver/wal/wal_test.go
with #22897498
A hardstate commit in wal that is larger than lastIndex will cause raft startup exceptions
``` text
fix abnormal hardState commit
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(clustermgr): fix abnormal hardState commit

- client/fs/dcache.go
- client/fs/dir.go
- client/fs/file.go
- client/fs/super.go
- objectnode/api_handler_bucket.go
- objectnode/api_middleware.go
- objectnode/fs_manager.go
- objectnode/fs_volume.go
``` text
reduce the memory consumption of the client r
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(client): reduce the memory consumption of the client

- .github/workflows/ci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/release_test.yml
- .github/workflows/scorecard.yml
- util/string_test.go
see more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> chore(github): upgrade action of upload-artifact

- metanode/partition_fsmop_inode.go
> fix(meta): fix metanode panic when append empty extents. 

- docs-zh/source/faq/troubleshoot/case.md
- docs/source/faq/troubleshoot/case.md
Fixes: N/A
Main Issue: N/A
N/A
``` text
```
- [  ] Documentation Update (if none of the other choices apply)
*(or)*
*(or)*
*(example:)*
*(or)*
- [  ] `doc-complete` 
- [  ] `whenever`
> docs(all): Add FAQ pages.

- .github/workflows/codeql.yml
> chore(github): upgrade codeql to v3

- docs-zh/source/faq/troubleshoot/case.md
- docs/source/faq/troubleshoot/case.md
Fixes: #xyz
N/A
``` text
N/A
```
- [  ] Documentation Update (if none of the other choices apply)
*(or)*
*(or)*
*(example:)*
*(or)*
- [  ] `doc-complete` 
- [  ] `whenever`
> docs(doc): Fix some document mistake.

- docs-zh/source/ops/configs/lcnode.md
- docs-zh/source/sidebarConfig.js
- docs/source/ops/configs/lcnode.md
- docs/source/sidebarConfig.js
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(doc): add cubefs lcnode config

- .semgrepignore
> chore(test): add semgrep ignore paths

- docs-zh/source/ecology/k8s.md
- docs/source/ecology/k8s.md
Fixes: #xyz
Main Issue: #3684
The version of the csi driver image on the documentation is not up to date, causing problems with cubefs deployed using helm.
``` text
Modify csi driver image to 3.4.0.
```
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(doc): modify the csi driver image.

- master/topology.go
- objectnode/policy_const.go
- objectnode/policy_statement.go
- objectnode/policy_v2.go
> chore(style): fix semgrep of ip v6 in document

- docs-zh/source/faq/troubleshoot/case.md
- docs/source/faq/troubleshoot/case.md
Fixes: nil
Main Issue: nil
``` text
Add FAQ cases.
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(docs): update FAQ cases.

- client/fuse.go
- master/server.go
- master/vol.go
- metanode/partition.go
- metanode/partition_fsmop_inode.go
- metanode/partition_op_extend.go
- metanode/partition_test.go
- proto/mount_options.go
- sdk/data/stream/extent_client.go
- sdk/data/stream/stream_reader.go
- sdk/data/stream/stream_writer.go
- util/exporter/exporter.go
- util/fileutil/write.go
- util/fileutil/write_test.go
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(all): merge some modifaction to release-3.5.0

- docs-zh/source/deploy/yum.md
- docs-zh/source/feature/hybridcloud.md
- docs-zh/source/quickstart/cluster-deploy.md
> docs(docs): correct some issuse about docs. #23131054

- docs-zh/source/sidebarConfig.js
- docs/source/sidebarConfig.js
> docs(docs): add feature hybridcloud file to sidbar.

- docs-zh/source/sidebarConfig.js
- docs/source/sidebarConfig.js
> docs(docs): add faq upgrade file to sidbar.

- ROADMAP.md
Update the ROADMAP of 2025 
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(doc): Update the ROADMAP of 2025

- docs-zh/source/quickstart/single-deploy.md
- docs/source/quickstart/single-deploy.md
Fixes:  N/A
Main Issue:  N/A
Add one more method to install single node storage.
``` text
Add one more method to install single node storage.
```
- [  ] Documentation Update (if none of the other choices apply)
*(or)*
*(or)*
*(example:)*
*(or)*
- [  ] `doc-complete` 
- [  ] `whenever`
> docs(docs): Add one new single mode setup method.

- docs-zh/source/deploy/yum.md
- docs/source/deploy/yum.md
> docs(docs): update yum rpm to 3.5.0.

- build/build.sh
Fixes: #xyz
enable multi-thread compilation in rocksdb
``` text
- add -j$1 in rocksdb make command
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(build): enable multi-thread compilation in rocksdb

- metanode/packet.go
- metanode/packet_test.go
- metanode/server.go
- proto/packet.go
Fixes: #3730 
Main Issue: #3730 
Allocating a Packet struct for every request is too costly.
``` text
align and reuse the Packet struct to reduce allocated memory in the func serveConn
```
i have added unit test
> perf(metanode): align and reuse the Packet struct to reduce allocated memory

- docker/docker-compose.yml
Fixes: #3746 
blaaaaa
``` text
upgrade grafana image versiont to 6.5
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(build): grafana container can not start

- docs-zh/source/dev-guide/sdk.md
- docs/source/dev-guide/sdk.md
Fixes: #xyz
add sdk user manual
``` text
add sdk user manual
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(docs): add sdk user manual.

- docs-zh/source/dev-guide/admin-api/blobstore/cm.md
- docs/source/dev-guide/admin-api/blobstore/cm.md
this command cannot enable volume inspect for scheduler service
```
curl -X POST http://127.0.0.1:9998/config/set -d '{"key":"vol_inspect","value":"true"}' --header 'Content-Type: application/json'
```
```
type TaskType string
const (
TaskTypeDiskRepair    TaskType = "disk_repair"
TaskTypeBalance       TaskType = "balance"
TaskTypeDiskDrop      TaskType = "disk_drop"
TaskTypeManualMigrate TaskType = "manual_migrate"
TaskTypeVolumeInspect TaskType = "volume_inspect"
TaskTypeShardRepair   TaskType = "shard_repair"
TaskTypeBlobDelete    TaskType = "blob_delete"
)
```
*(or)*
*(or)* …
> docs(cm): fix volume_inspect switch key

- Makefile
- blobstore/testing/dial/connect.go
- blobstore/testing/dial/dial.go
- blobstore/testing/dial/main/dial.conf
- blobstore/testing/dial/main/main.go
- blobstore/testing/dial/metric.go
- blobstore/testing/dial/service.go
- build/build.sh
``` text
add dial testing for blobstore
```
> feat(dial): add dial testing for blobstore

- .github/workflows/check_pull_request.yml
``` text
check commit message with some letters
```
> chore(github): check commit message with letters

- blobstore/common/raftserver/server.go
> fix(blobstore): waiting apply snapshot finish when save new raft log

- .github/workflows/check_pull_request.yml
list all commits and json to local file
> chore(ci): list all commits and json to local file

- docs-zh/source/faq/troubleshoot/case.md
- docs/source/faq/troubleshoot/case.md
@formatter:off
Fixes: #xyz
add some FAQ
``` text
add some FAQ
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(docs): add FAQ

- blobstore/common/codemode/codemode.go
- blobstore/common/codemode/codemode_test.go
> feat(all): add EC24P8 codemode for ocs archive

- docs-zh/source/feature/flash.md
- docs/source/feature/flash.md
> fix(docs): Remove the description of redundant flash nodes

- docs-zh/source/deploy/yum.md
- docs/source/deploy/yum.md
> docs(docs): update yum rpm to 3.5.1

- CHANGELOG.md
> docs(docs): update change log for v3.5.1

- blobstore/common/crc32block/sized_coder_test.go
> test(common): fix testing of range to next block

- docs-zh/source/user-guide/flashnode.md
- docs/source/user-guide/flashnode.md
PR in forked repository: cherry pick change from pull request #3843
> fix(doc): cli, Change flashGroup to flashgroup, otherwise it will cause an error

- docs-zh/source/user-guide/flashnode.md
- docs/source/user-guide/flashnode.md
> fix(doc): cli Change flashGroup to flashgroup

- master/monitor_metrics.go
Fixes: #3856 
Main Issue: #3856 
1. Partition info query blocks with no response
2. checkDataPartitions task will be blocked
``` text
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(master): fix checkDataPartitions dead lock

- blobstore/access/controller/service.go
- blobstore/access/controller/service_test.go
- blobstore/access/stream/stream_put.go
- go.mod
CodeDiskBroken
``` text
[blaaaaa](put: update cache cos put needs N+M-1 written shards 
get: ignore cos get just need N+1 shards)
```
> fix(access): update repairing volume cache

- docs-zh/source/deploy/yum.md
- docs/source/deploy/yum.md
Fixes: nil
Main Issue: nil
update yum.md for v3.5.2
``` text
update yum.md for v3.5.2
```
*(or)*
*(or)*
*(example:)*
*(or)*
> docs(docs): update yum.md for v3.5.2

- blobstore/cmd/cmd.go
Since the lumberjack package has a compression option, this option is also added to the log configuration. The default value is false, and it is up to the user to decide whether to enable it.
Fixes: #xyz
blaaaaa
``` text
blaaaaa
```
*(or)*
*(or)*
*(example:)*
*(or)*
> feat(blobstore): add compress option to log configuration

- master/admin_task_manager.go
Fixes: #3872
Resubmission of #3875 @zhumingze1108
Add retry to syncSendAdminTask to automatic retry on transient network failure
Add retry logics to both read and write.
> fix(master): add retry to syncSendAdminTask to handle transient error

- blobstore/util/graceful/procmaster.go
Fixes: #xyz
blaaaaa
``` text
blaaaaa
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(blobstore): fix typo

- blobstore/blobnode/datainspect.go
- blobstore/blobnode/datainspect_test.go
``` text
fix(blobnode): fix data inspect goroutine leak
```
> fix(blobnode): fix data inspect goroutine leak

- blobstore/common/rpc/client.go
- blobstore/common/rpc/client_test.go
- go.mod
- go.sum
thread-safe in rpc response body.
> fix(rpc): timeout with response in rpc client

- client/fs/dir.go
Fixes: #xyz
blaaaaa
``` text
blaaaaa
```
*(or)*
*(or)*
*(example:)*
*(or)*
> fix(client): Fixed issues #3935 readdir offset
