cubefs/cubefs

util/exporter/alarm.go, util/exporter/consul_register.go, util/exporter/counter.go, util/exporter/exporter.go, util/exporter/exporter_test.go, util/exporter/gauge.go, util/exporter/timepoint.go, util/exporter/util.go
=> init exporter

metanode/api_handler.go, metanode/btree.go, metanode/const.go, metanode/datapartition.go, metanode/dentry.go, metanode/extents.go, metanode/free_list.go, metanode/inode.go, metanode/manager.go, metanode/manager_op.go, metanode/manager_proxy.go, metanode/manager_resp.go, metanode/metanode.go, metanode/packet.go, metanode/partition.go, metanode/partition_delete_extents.go, metanode/partition_free_list.go, metanode/partition_fsm.go, metanode/partition_fsmop.go, metanode/partition_fsmop_dentry.go, metanode/partition_fsmop_inode.go, metanode/partition_item.go, metanode/partition_op_dentry.go, metanode/partition_op_extent.go, metanode/partition_op_inode.go, metanode/partition_store.go, metanode/partition_store_ticket.go, metanode/raft_server.go, metanode/server.go, metanode/time.go
=> init metanode

datanode/partition_op_by_raft.go, datanode/partition_raft.go, datanode/partition_raftfsm.go, raftstore/config.go, raftstore/partition.go, raftstore/raftstore.go, raftstore/raftstore_test.go, raftstore/resolver.go, raftstore/store.go, raftstore/store_rocksdb.go
=> init raftStore

datanode/partition_metrics.go, datanode/server.go, datanode/wrap_operator.go, proto/admin_proto.go, proto/admin_task.go, proto/errors.go, proto/extent_key.go, proto/fs_proto.go, proto/meta_proto.go, proto/packet.go, proto/status.go, repl/repl_protocol.go
init (fix conflicts and init proto packet)
=> init (fix conflicts and init proto packet)

client/fs/dir.go, client/fs/file.go, client/fs/super.go, cmd/cfg/fuse.json, datanode/partition_op_by_raft.go, datanode/server.go, datanode/server_handler.go, metanode/manager.go, metanode/manager_op.go, metanode/packet.go, metanode/partition.go, metanode/partition_free_list.go, metanode/partition_fsmop_inode.go, proto/packet.go, raftstore/raftstore.go, repl/repl_protocol.go, sdk/data/stream/extent_reader.go, sdk/data/stream/stream_writer.go, storage/extent_store.go, storage/persistence_crc.go, vendor/github.com/tiglabs/raft/raft.go
client: 
1.try other hosts for network errors
2.use single instance for File and Dir object
metanode:
1.use tcp packet notify all raft followers to free inodes
datanode:
1.remove read check appliedID
2.change extentcache fp to 100
3.fix always repair has delete extents
repl:
1.modify funcName from reciveFromFollower to checkLocalResultAndReceiveFromFollower
=> fix some bug:

README.md
=> add logo on cfs

MAINTAINERS.md
=> add MAINTAINERS file

.travis.yml, Makefile
=> add travis ci config

cmd/cmd.go
=> UPDATE author on cmd/cmd.go

README.md
=> modify doc url

metanode/partition_fsm.go, metanode/partition_store.go
fix bug: metanode Repeated allocation of inodes
=> fix bug: metanode Repeated allocation of inodes

sdk/data/stream/extent_reader.go, sdk/data/stream/stream_writer.go
Move some error messages from error to warn log.
=> sdk: suppress some error messages

datanode/wrap_operator.go, master/api_service.go, master/cluster.go, master/cluster_task.go, master/const.go, master/data_partition.go, master/metadata_fsm_op.go, master/vol.go
creating vol api: add mpCount parameter
=> creating vol api: add mpCount parameter

GOVERNANCE.md, MAINTAINERS.md
We need to make sure "chubaofs-maintainers@groups.io" works before merge.
=> Add governance

datanode/wrap_operator.go, master/api_service.go, master/cluster.go, master/cluster_task.go, master/const.go, master/data_partition.go, master/metadata_fsm_op.go, master/vol.go, metanode/partition_fsm.go, metanode/partition_store.go, sdk/data/stream/extent_reader.go, sdk/data/stream/stream_writer.go
medatanode: Repeated allocation of inode numbers
master:Persitence dataPartition disk Path and creating vol api: add mpCount parameter
sdk: suppress some error messages
=> resolve repeated allocate inode and modify createVol api

client/fs/dir.go
This will enable the support to fifo and socket file types.
=> client: enable support to fifo and socket file types

sdk/data/stream/extent_client.go, sdk/meta/meta.go
Retry if mount failed in case master is unavailable temporarily.
=> sdk: retry if mount failed in case master is unavailable temporarily

client/build.sh, client/fuse.go, cmd/build.sh, cmd/cmd.go
Sometimes a verbose build info is more useful than just a commit SHA-1.
=> Add verbose build info

metanode/partition_fsm.go, raftstore/raftstore.go, vendor/github.com/tiglabs/raft/raft_fsm.go
=> fix: 1. raft election timeout; 2. raft fatal event panic metanode

cmd/cmd.go, datanode/disk.go, datanode/partition.go, datanode/partition_op_by_raft.go, datanode/server.go, datanode/wrap_operator.go, metanode/manager.go, metanode/partition.go, metanode/partition_free_list.go, repl/packet.go, sdk/meta/operation.go, util/exporter/alarm.go, util/exporter/exporter.go, util/exporter/timepoint.go
1.metanode painc
2.when pprof not start,then painc
3.add when datanode disk error ,then warn,and change disk error to -1
4.add when load datapartition failed,then warn
5. use ump monitor if exporter not enable
=> fix bugs about(metanode and datanode)

datanode/partition_raft.go, metanode/partition_fsmop.go
=> fix: partition is nil when apply remove raft node

metanode/partition_fsmop.go
=> fixbug: metanode not start ,when it killed by kill -9

.travis.yml, README.md, docker/docker-compose.yml, docker/run_docker.sh, docker/script/start_client.sh
=> add run docker script

README.md, docker/docker-compose.yml, docker/run_docker.sh, docker/script/start_client.sh
=> Update docker helper script

client/fs/dir.go, docker/docker-compose.yml, docker/ltp/runtest/fs
1.client: delete inode cache in Remove and Rename
2.Disable rwtest* and ftest* test cases since they will cause docker
container to hang forever. Looks like an issue when running LTP in
docker containers. So comments out these cases for now.
=> merge dev to master

.travis.yml, docker/Dockerfile, docker/build_docker.sh, docker/docker-compose.yml, docker/run_docker.sh, docker/script/run_test.sh, docker/script/start_client.sh
=> add cfs-base dockerfile

datanode/wrap_prepare.go, storage/extent_store.go
=> fix: when datanode is killed,then maxBaseExtentId so low

docs/source/quick-start-guide.rst, docs/source/user-guide/datanode.rst, docs/source/user-guide/master.rst, docs/source/user-guide/metanode.rst
=> docs: update according to recent changes

cmd/cfg/datanode.json, cmd/cfg/master.json, cmd/cfg/meta.json, cmd/cmd.go, datanode/disk.go, datanode/partition.go, datanode/wrap_prepare.go, metanode/metanode.go, metanode/partition.go, metanode/partition_fsm.go, metanode/partition_store.go, storage/extent_store.go, util/ump/ump.go, util/ump/ump_async_log.go
=>  Regularize some variable names and config file

client/build.sh, cmd/build.sh, docs/source/admin-api/master/data-partition.rst, docs/source/admin-api/master/volume.rst, docs/source/index.rst, docs/source/quick-start-guide.rst, docs/source/user-guide/client.rst, docs/source/user-guide/datanode.rst
=> docs: update documents

docs/source/conf.py
=> Delete latex build

client/fuse.go, cmd/cmd.go, datanode/server.go, util/ump/ump.go, util/ump/ump_async_log.go
=> when warnLogDir not config,then warn and rename RestSize to reservedSize

datanode/partition_raft.go, datanode/server.go
=> fix: More information when start server error

docker/docker-compose.yml
=> remove docker client security opt

docker/docker-compose.yml
=> add privileged for docker-compose server node

datanode/server.go
=> config retain space can not over default value.

docs/source/admin-api/master/volume.rst, docs/source/administration.rst, docs/source/design/master.rst, docs/source/quick-start-guide.rst, docs/source/user-guide/datanode.rst, docs/source/user-guide/master.rst
1. disk config detail
2. default create 10 data partition and 3 meta partition when create volume
3. resource manager is master
=> fix docs issue

docker/monitor/grafana/provisioning/dashboards/chubaofs.json, util/exporter/exporter.go
normalize exporter cluster name to match promethues metrics regex
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
=> normalize exporter cluster name

master/api_service.go, master/data_node.go, master/data_partition.go, master/data_partition_map.go, master/disk_manager.go
In the following scenario,decommission disk may be decommission  no any data partition,this pr can solve it.
1. occurred disk error
2. remove bad disk from configuration file 
3. restart data node
4. send decommission disk to resource manager
=> refine decommission disk

docs/source/index.rst, docs/source/user-guide/cfs-grafana-dashboard.json, docs/source/user-guide/docker.rst
add chubaofs docker-compose deploy docs
=> update docs docker

client/build.sh, clientv2/build.sh, cmd/build.sh
check GOPATH in build.sh, if not set, error and exit
=> add GOPATH check in build.sh

datanode/disk.go, datanode/partition.go
=> fix: when disk error,the disk status not change

datanode/const.go
=> change dataPartition  IntervalToUpdateReplica to 600 seconds

master/api_service.go, master/data_partition_check.go, master/id_allocator.go, master/meta_partition.go, master/vol.go
=> write data partition decommission url message  to log

client/fuse.go, cmd/cmd.go, datanode/const.go, datanode/disk.go, datanode/partition.go, datanode/partition_raftfsm.go, master/cluster.go, master/cluster_task.go, master/data_node.go, master/data_partition.go, master/data_partition_check.go, master/metadata_fsm_op.go, metanode/partition_fsm.go, metanode/partition_store_ticket.go, sdk/data/stream/extent_client.go, storage/extent.go, storage/extent_store.go, util/exporter/alarm.go, util/ump/ump.go, util/ump/ump_async_log.go
=> fix: warnMesg failed on warnLogDir

datanode/partition_raft.go
=> fix: get partition size packet result code error

Makefile, build/build.sh
remove rocksdb lua_path dependency and auto set tmp GOPATH for build
=> fix build with lua bug

client/fs/super.go, client/fuse.go, clientv2/fs/super.go, clientv2/main.go, docs/source/quick-start-guide.rst, docs/source/user-guide/client.rst, vendor/github.com/jacobsa/daemonize/LICENSE, vendor/github.com/jacobsa/daemonize/daemonize.go
Leverage jacobsa daemonize package to start client and clientv2 as a daemon. So no explicit background commands like "nohup" is needed.
=> Daemonize client

Makefile, build/build.sh
=> update build: move rocksdb and snappy build dir

README.md, docs/source/quick-start-guide.rst
=> update docs: add make build in readme and docs

docs/source/quick-start-guide.rst
=> update docs: remove server and client

master/cluster.go, master/const.go, master/data_partition.go, master/operate_util.go, master/vol.go, proto/admin_proto.go, util/ump/ump.go, util/ump/ump_async_log.go
Check whether vol is valid. If there is no meta partition with start being 0, the vol is considered invalid
=> Check vol valid

README.md, build/build.sh
update build.sh for user permission
add the paper reference
=> build: update build.sh for user permission

clientv2/fs/dir.go, clientv2/fs/misc.go
=> clientv2: fix to get the latest file size

.gitignore
=> Ignore generated build files

Makefile, build/build.sh
=> build: update build.sh and Makefile

docker/ltp/runtest/fs
=> ci: enable LTP rwtest cases

docker/ltp/runtest/fs
=> Revert "ci: enable LTP rwtest cases"

datanode/partition.go, datanode/partition_op_by_raft.go, datanode/partition_raft.go, datanode/partition_raftfsm.go, datanode/space_manager.go, datanode/wrap_operator.go, datanode/wrap_prepare.go, proto/packet.go, repl/const.go, repl/packet.go, repl/repl_protocol.go
1. use one thread to send and recive from follower on primary backup repl protocol ,imporve performance
2. change random write raft serialize not use json
3. change the packet.GetUniqueLogId mesg
=> random write use binary encode and import primary backup repl protocol

.gitignore, Makefile, build/build.sh
=> build: update build.sh

build/build.sh
1. update make clean/dist-clean for rm full path
=> build: fix multi users build bug

Makefile, build/build.sh
1. change /tmp/cfs path
2. update make clean/dist-clean
=> build: fix no root user permission bug

Makefile, build/build.sh
=> build: remove client unused depends

datanode/partition.go, datanode/partition_raft.go, datanode/space_manager.go
=> init replicas info from create data partition request

datanode/disk.go, datanode/partition_op_by_raft.go, datanode/server.go, master/api_service.go, master/cluster.go, master/data_node.go, master/meta_node.go, metanode/metanode.go, proto/packet.go, repl/packet.go, repl/repl_protocol.go
1. when datanode or metanode start,must compare partition with master
2. datanode add backend check disk status func
=> Enhancement: when datanode or metanode start,compare with master,and datanode add auto disk check status

vendor/github.com/tiglabs/raft/raft_fsm.go
=> fix: when raft member become leader,must apply from appliyID to commitID

docker/script/run_test.sh
=> fix: add del vol step after ltptest in travis-ci test script

storage/extent_store.go
Enhancement: extent_store LoadTinyDeleteFileOffset return s.baseTinyDeleteOffset 
prevent read from disk 
=> Enhancement: extent_store LoadTinyDeleteFileOffset return s.baseTinyDeleteOffset

clientv2/fs/file.go, clientv2/fs/super.go, sdk/meta/meta.go, sdk/meta/view.go
This commit add warning reports if error occurs in clientv2. The
reported message include client IP as well.
=> enhancement: improve log message details for clientv2

clientv2/fs/dir.go, clientv2/fs/file.go
=> enhancement: add performance tracepoint for clientv2

master/api_service.go, master/api_service_test.go, master/cluster.go, master/cluster_task.go, master/cluster_test.go, master/data_partition.go, master/meta_partition.go, master/meta_partition_test.go, master/metadata_fsm_op.go, master/mocktest/data_server.go, master/mocktest/meta_server.go, master/vol.go, master/vol_test.go
Support pass dp num for create vol
=> Support pass dp num for create vol

docs/source/quick-start-guide.rst, docs/source/user-guide/client.rst, docs/source/user-guide/datanode.rst, docs/source/user-guide/master.rst, docs/source/user-guide/metanode.rst
=> Refactor: Doc :delete warnLogDir config

sdk/meta/api.go
=> fix: treat ddelete not exist error as successful

cmd/cmd.go, docker/script/start_datanode.sh, docker/script/start_master.sh, docker/script/start_meta.sh
Start server as a daemon, so no need to use nohup.
=> feature: daemonize server

client/fuse.go, clientv2/main.go, cmd/cmd.go, util/log/log.go
=> Feature: support log module change loglevel on line

metanode/manager_op.go, util/log/log.go
=> Refactor: log checkroration checkTime change to 1 second and metanode api logLevel change

datanode/server.go, metanode/metanode.go
=> fix: update export init for consul register

cmd/cmd.go
=> fix: err is shadowed in server main function

datanode/server.go
=> Fix: datanode cannot register to master,but not exit

client/fuse.go, clientv2/main.go, cmd/cmd.go
Check LoadConfigFile before starting daemon, since it will invoke
os.Exit() without notifying the parent process. So we should make sure
that it is successful.
=> fix: check LoadConfigFile before starting daemon

README.md, ROADMAP.md
Revert due to license check failure.
=> Fix license check failure

client/fuse.go, clientv2/main.go, cmd/cmd.go, util/config/config.go
Signed-off-by: wuwenjia5 <wuwenjia5@jd.com>
=> fix: return error from function LoadConfigFile to the caller

README.md
Signed-off-by: Liying Zhang <zhangliying1@jd.com>
=> Add Community Info

storage/extent.go
=> Fix: extentStorage engine :autoComputeCrc compute crc error

docker/Dockerfile-dev, docker/build_docker_dev.sh, docker/docker-compose-dev.yml, docker/docker-compose.yml
1. Use static ip address for meta/data nodes.
2. Add some useful tools to the dev docker compose environment.
=> Update docker compose for debug convenience

metanode/api_handler.go, metanode/free_list.go, metanode/partition_free_list.go, metanode/partition_fsmop_inode.go
1. clean up response of get all inodes info
2. fix metanode orphan inodes memleak
=> Fix metanode orphan inode memleak

master/server.go
=> fix: set default port to non-system reserved port

datanode/disk.go, datanode/space_manager.go, master/data_node.go, master/monitor_metrics.go, proto/admin_proto.go
=> feature: add metrics

docker/monitor/grafana/provisioning/dashboards/chubaofs.json, docs/source/user-guide/cfs-grafana-dashboard.json
=> enhancement: update grafana dashbord for disk error metric

datanode/disk.go, datanode/server.go, datanode/space_manager.go
Refactor: delete resverd space on datanode config file
=> Refactor: delete resverd space on datanode config file 

datanode/data_partition_repair.go, datanode/disk.go, datanode/partition_raft.go, datanode/space_manager.go, datanode/wrap_operator.go, master/admin_task_manager.go, master/cluster.go, master/cluster_task.go, master/data_node.go, master/data_partition.go, master/meta_node.go, master/monitor_metrics.go, metanode/partition_fsmop.go, proto/packet.go, raftstore/config.go, repl/packet.go, storage/extent_store.go, util/ump/ump_async_log.go
=> refactor: refine labels of the disk error metric

storage/extent_store.go
=> Refactor: optimize auto compute crc

MAINTAINERS.md
=> Refactor: Update Maintainer.md

README.md, docker/run_docker.sh
=> enhancement: update run docker script with check diskpath size

cmd/cfg/master.json, docs/source/quick-start-guide.rst, docs/source/user-guide/master.rst
=> Refactor: change Demo Master config

Makefile, authnode/api_service.go, authnode/authnode_manager.go, authnode/cluster.go, authnode/config.go, authnode/const.go, authnode/http_server.go, authnode/keystore_fsm.go, authnode/keystore_fsm_op.go, authnode/keystore_snapshot.go, authnode/server.go, authtool/authtool.go, build/build.sh, cmd/cmd.go, master/config.go, proto/auth_proto.go, proto/errors.go, raftstore/store_rocksdb.go, util/caps/caps.go, util/cryptoutil/const.go, util/cryptoutil/cryptoutil.go, util/cryptoutil/ticket.go, util/iputil/ip.go, util/keystore/keystore.go, vendor/github.com/prometheus/procfs/go.mod
Signed-off-by: jzeng4 <jzeng04@gmail.com>
=> Add a general Authentication & Authorization framework for chubaofs.

datanode/disk.go, datanode/server.go, datanode/space_manager.go, master/cluster.go, raftstore/config.go, storage/extent_store.go, util/ump/ump.go
Fix:if the datanode config file resverdSpace > 30GB, the resverdSpace parameter  does not work and gofmt project
=> Fix:the datanode config resverdSpace parameter  does not work 

docker/Dockerfile-cfs, docker/build_docker_cfs.sh
build Chubaofs docker image that contains cfs-server and cfs-client
=> enhancement: support build  Chubaofs docker image that contains cfs-server and cfs-client

docs/source/quick-start-guide.rst, docs/source/user-guide/datanode.rst, docs/source/user-guide/master.rst, docs/source/user-guide/metanode.rst
=> enhancement: sync configFile on docs

Makefile, docs/source/quick-start-guide.rst
~/chubaofs# make build
/bin/sh: 1: [[: not found
refer to https://stackoverflow.com/a/37528631/6288539
Signed-off-by: Lei Liu <lei01.liu@horizon.ai>
=> makefile: slience /bin/sh syntax warning

MAINTAINERS.md, docs/source/use-case.rst
Refactor: delete hbase usecase and add maintainers
=> Refactor: delete hbase usecase and add maintainers

README.md
This is required per CNCF policies: https://github.com/cncf/foundation/blob/master/website-guidelines.md
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add CNCF reference to README

README.md
Signed-off-by: Wei Ding <wding109@gmail.com>
**What this PR does / why we need it**:  The README file has some grammar issue and duplicated CNCF reference
Fix grammar issue and remove duplicated CNCF reference in README
```release-note
```
=> Fix grammar and remove duplicated CNCF reference

metanode/partition_fsm.go, objectnode/fs_volume.go
- fix issue#329.
- fix serval logging format pattern.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #329 
```release-note
```
=> Fix: panic occurred when list multipart uploads (issue#329)

docs/source/evaluation.rst
- Add: volume setup information to document evaluation content.
=> Add: volume setup information to document evaluation content.

objectnode/acl.go, objectnode/acl_handler.go, objectnode/router.go
fix objectnode router pattern for bucket acl
```release-note
```
=> Fix: objectnode router pattern for acl 

docs/source/contributing.rst, docs/source/index.rst
copy the existing CONTRIBUTING.MD to docs
```release-note
```
=> Add contributing section to docs

docker/docker-compose.yml, master/api_service.go, master/api_service_test.go, master/cluster.go, master/cluster_task.go, master/cluster_test.go, master/const.go, master/meta_partition.go, master/meta_partition_manager.go, proto/admin_proto.go, proto/errors.go, proto/model.go
Only one replica can be taken offline at the same time, and other replicas can be taken offline only after recovery is completed
```release-note
```
=> fix: decommission replica one by one

docker/monitor/grafana/provisioning/dashboards/chubaofs.json, docs/source/user-guide/cfs-grafana-dashboard.json
update chubaofs monitor grafana dashboard config
```release-note
```
=> Update: grafana dashboard config

docker/Dockerfile-cfs, docker/build_docker_cfs.sh
Signed-off-by: chengyu-l <chengyu_l@126.com>
enhancement: Support Chubaofs docker image builded that contains cfs-server and cfs-client
NA
```release-note
```
=> enhancement: Support Chubaofs docker image builded that contains cfs-server and cfs-client

objectnode/auth_signature_v2.go, objectnode/auth_signature_v4.go
fix objectnode signature v2 calculate stringsing bug
```release-note
```
=> Fix: objectnode signature v2 content-type err

README.md
=> Update README: adding guide for ChubaoFS cluster deployment by Helm; added benchmark

client/fuse.go
Signed-off-by: chengyu-l <chengyu_l@126.com>
add log output when client start failed in frontground
NA
NA
```release-note
```
=> enhance: add log output when client start failed in frontground

objectnode/fs_volume.go, objectnode/router.go
- Fix: issue when copy file across folder by using object storage interface.
- Enhancement API routing.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #360 
None.
```release-note
Fix: issue when copy file across folder by using object storage interface.
```
=> Fix: issue when copy file across folder by using object storage interface.

CHANGELOG.md
=> Update CHANGELOG from v1.5.0 to v1.5.1.

objectnode/auth_signature_v2.go
Fix objectnode signature v2 calcuation issue.
=> Fix objectnode signature v2 calcuation issue

docs/source/faq.rst
Signed-off-by: Justice <justice_103@126.com>
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #368 
```release-note
```
=> Enhancement: add hadoop ozone vs chubaofs faq

.travis.yml
=> travis ci update

cmd/cmd.go, cmd/common/server.go, datanode/const.go, datanode/server.go, metanode/const.go, metanode/manager.go, metanode/metanode.go, metanode/partition.go, metanode/partition_store_ticket.go, objectnode/server.go
Extract duplicate server code to a common module.
N/A
N/A
N/A
=> refactor: clean up duplicate server code

master/cluster.go, master/cluster_task.go, master/codec_node.go, master/const.go, master/ec_node.go, master/http_server.go, master/meta_partition.go, master/meta_partition_manager.go, master/operate_util.go, proto/admin_proto.go, proto/errors.go, proto/model.go, proto/packet.go
Initialize the ec master module, define the communication protocol between master and codecNode, master and ecnode, and implement the feature of retrieving all codecnodes
N/A
N/A
N/A
```release-note
```
=> feature: ec

Makefile, cmd/cmd.go, ecnode/server.go, ecnode/server_handler.go, ecnode/wrap_operator.go, ecnode/wrap_post.go, ecnode/wrap_prepare.go
=> initialize ecnode with tcp service api

README.md
=> Update README: add guide of yum installation for ChubaoFS cluster.

cmd/cmd.go, codecnode/server.go, proto/model.go, sdk/master/api_node.go
Register the node to master and get an allocated node id.
```release-note
```
=> feature: introduce codec node

docker/docker-compose-dev.yml
Divide server component in docker-compose-dev.yml to masters, metanodes
and datanodes for debug convenience.
```release-note
```
=> enhancement: make docker compose more fine grained

docs/source/admin-api/master/cluster.rst, docs/source/admin-api/master/data-partition.rst, docs/source/admin-api/master/datanode.rst, docs/source/admin-api/master/management.rst, docs/source/admin-api/master/meta-partition.rst, docs/source/admin-api/master/metanode.rst, docs/source/admin-api/master/volume.rst, docs/source/admin-api/metanode/dentry.rst, docs/source/admin-api/metanode/inode.rst, docs/source/admin-api/metanode/partition.rst, docs/source/index.rst, docs/source/manual-deploy.rst, docs/source/user-guide/client.rst, docs/source/user-guide/datanode.rst, docs/source/user-guide/master.rst, docs/source/user-guide/metanode.rst, docs/source/user-guide/monitor.rst, docs/source/user-guide/objectnode.rst, docs/source/user-guide/yum.rst
=> doc: update parameters in documentation according to yum tools.

client/fuse.go, clientv2/main.go, cmd/cmd.go, util/sys/dup_darwin.go, util/sys/dup_linux.go, util/sys/dup_windows.go
- Enhancement: wrap `syscal.Dup3` to support build on darwin and windows
=> Enhancement: wrap syscal.Dup3 to support build on darwin and windows

docker/conf/nginx.conf, docker/conf/objectnode.json, docker/docker-compose.yml
- Enhancement: add nginx and upstream for objectnode in docker compose
=> Enhancement: add nginx and upstream for objectnode in docker compose

client/fs/super.go, client/fuse.go, clientv2/fs/super.go, clientv2/main.go, proto/mount_options.go, sdk/master/api_client.go, sdk/meta/meta.go, sdk/meta/view.go
Use token to distinguish the abilities of client, readonly or readwrite.
```release-note
```
=> feature: introduce token to client

cli/cmd/fmt.go, cli/cmd/user.go, client/fuse.go, master/api_service.go, master/api_service_user.go, master/const.go, master/http_server.go, master/master_manager.go, master/metadata_fsm.go, master/metadata_fsm_op.go, master/user.go, master/userdata_fsm_op.go, objectnode/api_handler_bucket.go, objectnode/auth_signature_v2.go, objectnode/auth_signature_v4.go, objectnode/fs_store_user.go, objectnode/fs_volume.go, objectnode/policy.go, objectnode/server.go, proto/admin_proto.go, proto/user_proto.go, sdk/master/api_admin.go, sdk/master/api_user.go
- Refactor the index of user store. 
- Refactor user api 'updatePolicy' and 'removePolicy'
- fixes #383 
- fixes #423 
NONE.
=> Refactor the index of user store and user api

docs/source/user-guide/client.rst
Update the client mount options doc.
```release-note
```
=> docs: update FUSE client mount options

cli/cmd/user.go, master/api_service.go, master/api_service_user.go, master/const.go, master/http_server.go, master/master_manager.go, master/server.go, master/user.go, proto/admin_proto.go, proto/errors.go, proto/user_proto.go, sdk/master/api_user.go
1. Add cli and master api 'updateUser' and 'deleteUser'.
2. Remove create user automatical.
3. Ignore userSrc exists or not when transfer volume.
NONE.
NONE.
NONE.
=> Enhancement: API and CLI command for update user information and delete user

sdk/meta/api.go, sdk/meta/meta.go, sdk/meta/view.go
When iget method gets an ENOENT response error from metanode, it is
probably because the target meta partition has been splited, and the
client is not using the latest partition view. So we try to pull a
meta partitions view from the master in such case.
```release-note
```
=> fix: iget error due to metapartition split

cli/cmd/vol.go, docker/script/build.sh, master/api_service.go, master/api_service_user.go, master/user.go, proto/user_proto.go
- Auto create user while create volume if the owner user is not exists.
- Add a option for force transfer volume to target user.
NONE.
NONE.
NONE.
=> Enhancement: auto create user while create volume

docs/source/admin-api/master/volume.rst
Add token document
N/A
N/A
N/A
=> feature: add token document

master/user.go
Fix: transfer vol failed when transfer to owner after creating owner.
None.
None.
None.
=> Fix: transfer vol failed when transfer to owner after creating owner

cmd/master/scripts/manage_cluster_stat.sh, docs/source/admin-api/master/cluster.rst, master/api_service.go, master/api_service_test.go, master/cluster.go, master/cluster_stat.go, master/http_server.go, proto/admin_proto.go, proto/model.go
show cluster space statistics information by zone, help the cluster administrator expand the capacity of the machine reasonably
N/A
N/A
=> feature: provide cluster space statistics API

docker/conf/objectnode.json, docker/docker-compose.yml, objectnode/acl.go, objectnode/api_handler.go, objectnode/api_handler_bucket.go, objectnode/fs_manager.go, objectnode/fs_store_user.go, objectnode/fs_store_xattr.go, objectnode/fs_volume.go, objectnode/policy.go, objectnode/server.go
The blacklist mechanism has been added to the user store and volume manager in the object node to solve the adverse effect of a large number of invalid requests on system performance in a short period of time.
Stream requests to the user store and volume manager in the object node in a hash bucket manner, reducing the blocking caused by read and write locks under concurrency.
Abstracted the user store and added an implementation that does not cache user information. This is enabled through the `strict` configuration to provide sufficient real-time performance with cluster information during interface compatibility testing.
NONE.
NONE.
NONE.
=> Enhancement: reduce blocking under concurrency

master/api_service_test.go
Add test cases about user api.
None.
None.
None.
=> feature: add test cases about user api

sdk/meta/api.go
The BatchInodeGet will send requests to all the meta partitions.
However, as the number of meta partitions rises, the overhead for a *ls*
operation increases. So it is better to filter the target meta
partitions ahead. But this does not have to be very accurate since the
results of BatchInodeGet are used only for caches, and an InodeGet will
be issued upon cache miss.
```release-note
```
=> enhance: filter target meta partitions in batch iget

docker/conf/objectnode.json, docker/docker-compose.yml, docker/monitor/grafana/provisioning/dashboards/chubaofs.json, objectnode/api_middleware.go, objectnode/server.go, proto/perm_action.go, util/exporter/exporter.go
=> Enhancement: add prometheus metrics for objectnode

CHANGELOG.md
=> Update CHANGELOG from v1.5.1 to v2.0.0

objectnode/auth_signature_v4.go
The signature algorithm v4 uses the decoded path without escape characters as the resource data.
NONE.
NONE.
NONE.
=> Fix: signature calculation issue in continuous separators

.gitignore, docker/docker-compose.yml
=> Enhancement: add log map for docker-compose

master/api_service.go, master/cluster.go, master/cluster_stat.go, proto/model.go, sdk/master/api_admin.go
allow the zone name of vol to be updated
N/A
N/A
N/A
=> feature: allow the zone name of vol to be updated

datanode/server.go, master/api_service_test.go, master/cluster.go, master/const.go, master/vol_test.go, proto/model.go
=> fixed: the test case for vol which does not use a exist zone

sdk/meta/api.go
This commit filters the inode candidates that will be sent to a
partition to save memory used by json marshal, in case there are
so many inodes under a single directory.
```release-note
```
=> enhance: filter candidates in batch inode get

objectnode/auth.go, objectnode/auth_signature_v2.go, objectnode/auth_signature_v4.go, objectnode/policy.go, objectnode/policy_action.go, objectnode/policy_condition.go, objectnode/policy_statement.go
=> Fixed: update license

objectnode/stringset.go
=> Fix: update license file

client/fs/file.go, client/fs/super.go, client/fuse.go, proto/mount_options.go, util/config/config.go
Choose if close system call shall trigger fsync. The default value is
true.
```release-note
```
=> feature: introduce fsyncOnClose mount option

docker/docker-compose.yml, objectnode/api_handler_object.go, objectnode/util.go
=> Fix: using local time to replace UTC in S3 modify action

client/fuse.go
resolve that Crtl+C and umount command cannot stop cfs-client process
fixed #501 
Signed-off-by: chengyu-l <chengyu_l@126.com>
=> fix:  cannot stop cfs-client process

master/monitor_metrics.go, util/exporter/counter.go, util/exporter/gauge.go, util/exporter/util.go
=> Fix: modify master vol usedGB metrics collect bugs

sdk/meta/operation.go
=> fix: log level typo

client/fuse.go
Dump the version info in the output log for debug convenience.
```release-note
```
=> change: dump version in output log

objectnode/api_handler_object.go, objectnode/fs_volume.go
During the process of scanning the child nodes of the current
directory, there may be other parallel operations that may
delete the current directory.
If got the syscall.ENOENT error after invoked `readdir`, it means
that the above situation has occurred.
At this time, stops process this non-exists directory and returns success so that next item can be continue processed.
NONE.
Focus on checking the adjustment of the `recursiveScan` method.
NONE.
=> Fix: empty result due to file deletion during list operation

objectnode/api_handler_object.go, objectnode/fs_volume.go
- Remove useless log records and increase the information of valid log records.
- All operations related to file deletion and data release are recorded in detail. Such as unlink, evict, delete and so on.
NONE.
NONE.
NONE.
=> Enhancement: increase logging information

ecnode/disk.go, ecnode/ec_partition.go, ecnode/server.go, ecnode/server_handler.go, ecnode/space_manager.go, ecnode/stats.go, ecnode/wrap_operator.go, ecnode/wrap_post.go, ecnode/wrap_prepare.go, proto/admin_proto.go, proto/packet.go, repl/packet.go
…ition, createExtent, write and read interface with
unit test module
feature: add EcPartition, Extent and Disk module, complete createPartition, createExtent, write and read interface with unit test module
=> feature: complete write and read interface

objectnode/api_handler_object.go
Change the metadata of the object 'LastModified' time zone from local to UTC.
```release-note
```
=> Fix:change object last modified time zone to UTC

util/exporter/consul_register.go
=> Fix: ignore error when get local ip failed

client/fuse.go
=> feature: adjust rlimit config for client

docker/docker-compose.yml, docker/monitor/grafana/provisioning/dashboards/chubaofs.json
=> Update: add detailed vol info on grafana dashboard

docker/conf/nginx.conf, objectnode/api_handler_bucket.go, objectnode/api_middleware.go, objectnode/const.go, objectnode/fs_volume.go, objectnode/result.go
Fix create time format of list buckets API to
`2006-01-02T15:04:05.000Z` as UTC time.
NONE.
NONE.
NONE.
=> Fix: create time format of list buckets

client/fs/dir.go, client/fs/file.go
=> Enhancement: add performance monitor for client

objectnode/auth_signature_v2.go, objectnode/auth_signature_v4.go
Fix signature calculation issue when operating object which key contains Chinese character.
fixes #528 
NONE.
```Bug fix:
- Fix signature calculation issue when operating object which key contains Chinese character.
```
=> Fix: signature calculation with chinese character

objectnode/acl.go, objectnode/policy.go
=> Enhancement: allow volome owener policy check when not deny

vendor/bazil.org/fuse/fs/serve.go, vendor/bazil.org/fuse/fuse_linux.go
Optimize client memory consumption: decrease the size of max write since to align with the kernel; limit the rate of Forget requests.
```release-note
```
=> Optimize client memory consumption

objectnode/api_handler_multipart.go, objectnode/api_handler_object.go, objectnode/fs_volume.go, objectnode/result.go, sdk/meta/meta.go
- Fix xml element of `DeleteResult`.
- Improve marshaled xml size by adding `omitempty` option.
- Display bucket owner as user name.
NONE.
NONE.
NONE.
=> Fix: xml element of DeleteResult

client/fuse.go, clientv2/main.go, proto/mount_options.go, sdk/data/stream/extent_client.go, util/ump/ump.go
=> Enhancement: add max CPUs config for client

docker/conf/master1.json, docker/conf/master2.json, docker/conf/master3.json, docker/monitor/grafana/provisioning/dashboards/chubaofs.json, master/http_server.go, master/monitor_metrics.go, master/server.go, util/config/config.go, util/exporter/consul_register.go, util/exporter/exporter.go
=> Update: add exporter InitWithRouter for prometheus init with http router

sdk/meta/meta.go
optimize the retry process code about initializing cluster information in client
Signed-off-by: Chengyu Liu <liuchengyu@jd.com>
=> refactor: optimize the retry process code about initializing cluster info in client

docker/s3tests/test_transfer.py, objectnode/api_handler_object.go, objectnode/const.go
Signed-off-by: yuboLee <pangbolee@gmail.com>
Add support for parallel download.
fixes #466 
```release-note
```
=> Enhancement: add support for parallel download

docs/source/user-guide/datanode.rst, docs/source/user-guide/metanode.rst
=> Update: add constcfg notice for metanode and datanode config

client/fuse.go, util/log/log_get.go
=> Enhancement: add http api for client log view

sdk/data/stream/stream_conn.go
=> change: add warn log for sentToPartition

metanode/partition_fsmop_inode.go, metanode/partition_op_extent.go, metanode/partition_op_inode.go, metanode/stub_inode.go
=> enhance: optimize inode memory usage of metanode

objectnode/api_handler_object.go, objectnode/const.go, objectnode/fs_volume.go, objectnode/result_error.go, objectnode/util.go, proto/user_proto.go
Signed-off-by: yuboLee <pangbolee@gmail.com>
Fix:
Modify the logical of copy object.
Enhancement :
Add support for copying object cross bucket.
Add support for copying a folder existed.
Add support for modifying object metadata via copying object when the source file is same with the target file.
fixes #469 
```release-note
```
=> Fix: rewrite copy object function

sdk/data/stream/stream_conn.go, sdk/data/wrapper/data_partition.go, sdk/data/wrapper/wrapper.go
=> Enhancement: skip failed host when sendToPartition

client/fs/file.go
=> fix: attr for symlink can return correct size

docs/source/admin-api/master/user.rst, docs/source/admin-api/master/volume.rst, docs/source/faq.rst, docs/source/index.rst, docs/source/operations.rst
1. Update FAQ.
2. Add operations FAQ docs
None.
None.
None.
=> update docs FAQ

util/exporter/consul_register.go
=> Enhancement: refactor consul register req proc

util/exporter/exporter.go
=> Enhancement: add default consul register addr http prefix

objectnode/acl.go, objectnode/policy.go
=> Fix: allow for bucket acl owner operation

objectnode/api_handler_object.go, objectnode/fs.go, objectnode/fs_volume.go
Signed-off-by: yuboLee <pangbolee@gmail.com>
Add support for http header 'Content-Disposition' while putting object, get object and heading object. 
```release-note
```
=> Enhancement: Add support for header Content-Disposition

docker/conf/objectnode.json, objectnode/acl.go, objectnode/acl_handler.go, objectnode/api_middleware.go, objectnode/const.go, objectnode/cors.go, objectnode/cors_handler.go, objectnode/fs_store_xattr.go, objectnode/fs_volume.go, objectnode/policy_handler.go, objectnode/router.go, proto/perm_action.go
Support CORS access control.
fixes #463  
None.
None.
=> Feature: support CORS access control

sdk/meta/api.go
=> fix: evict target inode when overwrite rename

metanode/free_list.go, metanode/partition_free_list.go
=> Refactor: optimize delete speed

docs/source/admin-api/master/volume.rst, master/api_service.go, master/vol.go, master/vol_test.go
data partition has 3 replicas at least, if data partition has 2 replicas, it can't tolerate any one data node down
N/A
N/A
N/A
=> fix :  data partition has 3 replicas at least

README.md
update docs: update chubaofs-hem parts in README file
=> update docs: update chubaofs-hem parts in README file

util/conn_pool.go
Refactor: connectPool change Default connect TimeOut
=> Refactor: connectPool change Default connect TimeOut

docs/source/admin-api/cli/cli.rst, docs/source/admin-api/master/volume.rst, docs/source/design/client.rst, docs/source/design/master.rst, docs/source/faq.rst
Remove parameter 'replicaNum'.
```release-note
```
=> update docs: remove parameter 'replicaNum'

master/api_service_test.go, master/api_service_user.go, master/http_server.go, master/user.go, proto/admin_proto.go, proto/errors.go, proto/user_proto.go, sdk/master/api_user.go
1. Persistance when delete user.
2. Add master api "/vol/users" to view users of volume.
3. Fix errors when grant permission.
None.
None.
None.
=> fix: persistance when delete user, and add master api to view users of volume

metanode/partition_delete_extents.go, metanode/partition_free_list.go
=> Fix: metanode maybe painc on deleteMarkedInodes

datanode/partition_raft.go, datanode/partition_raftfsm.go
Refactor: dataPartition StartRaft add painc Log
=> Refactor: dataPartition StartRaft add painc Log

objectnode/fs_volume.go
Signed-off-by: yuboLee <pangbolee@gmail.com>
Enhancement: Sort the common prefix list.
```release-note
```
=> Enhancement: Sort the common prefix list

metanode/partition_free_list.go
1.Metanode gets all dataPartitions of vol more quickly
=> Refactor:Metanode gets all dataPartitions of vol more quickly

master/cluster.go, master/cluster_task.go, master/data_partition.go
add vol name and partition ID information to err message
N/A
N/A
N/A
=> enhancement :  add vol and partition information to err message

ADOPTERS.md, README.md
- Update adopter.
- Add WeChat group to community info.
None.
None.
None.
=> Update adopter and community info

proto/packet.go
=> Fix: datanode GetUniqueLogId show opcode wrong

datanode/partition.go, datanode/wrap_operator.go, datanode/wrap_prepare.go, metanode/packet.go, metanode/partition_free_list.go, proto/extent_key.go, proto/model.go, proto/packet.go, storage/extent_store.go, vendor/github.com/tiglabs/raft/raft_fsm.go
1. metanode can send batchDeleteCmd to datanode,it can speed datanode delete 
=> add batchDelete feature

datanode/wrap_operator.go
Fix: datanode wrap operator add batchDeleteExtentsv
=> Fix: datanode wrap operator add batchDeleteExtents

proto/packet.go
Fix: packet GetOpMsg add OpBatchDeleteExtent
=> Fix: packet GetOpMsg add OpBatchDeleteExtent

metanode/btree.go, metanode/const.go, metanode/dentry.go, metanode/inode.go, metanode/manager.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_fsm.go, metanode/partition_fsmop_dentry.go, metanode/partition_fsmop_inode.go, metanode/partition_op_dentry.go, metanode/partition_op_inode.go, proto/fs_proto.go, proto/packet.go
=> add batch delete inode unlink evict dentry

metanode/partition_delete_extents.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #617 
```release-note
```
=> Fix: #617 ignore corrupted file in delete extents routine

datanode/space_manager.go, metanode/partition_free_list.go, proto/packet.go, repl/packet.go, repl/repl_protocol.go
=> Log optimize

metanode/partition_delete_extents.go
=> Enhancement: ignore error when open file error of delete extents

docker/monitor/grafana/provisioning/dashboards/chubaofs.json
=> Enhancement: update some master metrics pql

master/api_service.go
validate volume if it is existed before validating user info 
Signed-off-by: chengyu-l <chengyu_l@126.com>
=> Enhancement: validate volume if it is existed before validating user info

docs/source/admin-api/master/volume.rst, docs/source/user-guide/datanode.rst, docs/source/user-guide/metanode.rst, master/api_service.go
1. Exchange the order of delete volume and policy when delete volume.
2. Some supplements about docs.
```release-note
```
=> fix: exchange the order of delete volume and policy

metanode/manager_op.go, metanode/partition_op_dentry.go, metanode/partition_op_extent.go, metanode/partition_op_inode.go, sdk/master/client.go
=> Enhancement: Optimize some logs level and fix some unreturned errors

docs/source/user-guide/client.rst
update docs: client configuration 'enableXattr'
```release-note
```
=> update docs: client configuration 'enableXattr'

docs/source/admin-api/master/cluster.rst, docs/source/user-guide/master.rst, docs/source/user-guide/metanode.rst, master/config.go, metanode/metanode.go
add some configuration item description
N/A
N/A
N/A
=> enhancement :  add some configuration item description

docs/source/user-guide/datanode.rst
=> doc: clarify a datanode deploy prerequisite

datanode/partition.go, datanode/wrap_operator.go
=> Refactor: add datanode delete log

datanode/metric.go, datanode/server.go, datanode/wrap_operator.go, docker/monitor/grafana/provisioning/dashboards/chubaofs.json, metanode/metanode.go, metanode/metrics.go, util/exporter/counter.go, util/exporter/gauge.go, util/exporter/timepoint.go
=> Enhancement: add io metrics

proto/packet.go, sdk/data/stream/packet.go, util/buf/buffer_pool.go
1. fix: failed to put tiny buffer pool
2. enhance: use total count limit for tiny buffer pool instead of rate limit
```release-note
```
=> Fix failed to put tiny buffer pool

util/exporter/consul_register.go, util/exporter/exporter.go
=> Fix: fix http post consul req error

master/operate_util.go
use exporter to record warning log
N/A
N/A
N/A
=> fix: use exporter to record warning log

metanode/raft_server.go
Refactor: metanode NumOfLogsToRetain set to  4w records
=> Refactor: metanode NumOfLogsToRetain set to  4w records

metanode/partition_delete_extents.go
=> Refactor: add log on batchDelete Extent

metanode/partition_fsmop_extend.go, metanode/partition_fsmop_multipart.go
**What this PR does / why we need it**
Using CopyGet instead Get while modify extend or multipart session data.
=> Fix: metadata modification

datanode/data_partition_repair.go, datanode/partition.go, datanode/server.go, datanode/server_handler.go
Refactor: datanode add setAutoRepair status api
=> Refactor: datanode add setAutoRepair status api

metanode/const.go
Improve metanode startup loading metaPartition speed
=> Enhancment:Improve metanode startup loading speed

metanode/partition_delete_extents.go
=> Revert "Refactor: add log on batchDelete Extent"

metanode/packet.go, metanode/partition_delete_extents.go, metanode/partition_free_list.go
=> Revert "Refactor: metaNode bachDelete extent on Overwrite"

metanode/const.go
=> Revert "Enhancment:Improve metanode startup loading speed"

metanode/const.go, metanode/dentry.go, metanode/extend.go, metanode/inode.go, metanode/partition.go, metanode/partition_fsm.go, metanode/partition_store.go, metanode/partition_store_ticket.go, metanode/sorted_extents.go, proto/extent_key.go
=> Revert "Enhancement: improve metadata persist"

cli/api/metaapi.go, cli/cmd/compatibility.go, cli/cmd/const.go, cli/cmd/root.go, docs/source/admin-api/cli/cli.rst, metanode/partition.go
provide data consistency verification tool for meta partition
N/A
N/A
N/A
=> feature: provide data consistency verification tool for meta partition

docker/monitor/grafana/provisioning/dashboards/chubaofs.json
Signed-off-by: justice <justice_103@126.com>
```release-note
```
=> Enhancement: update grafana chart with tips

master/cluster.go, master/cluster_task.go, master/data_node.go, master/meta_node.go
the partiton can't be allocate to the node which to be offline
N/A
N/A
N/A
=> fix: it allocated the partition to the node which to be offline

docs/source/overview.rst
Fix typo in documents.
None.
None.
None.
=> fix: docs typo

master/cluster.go, master/cluster_task.go, master/config.go, master/data_partition_check.go, master/meta_partition.go, master/vol.go
=> Parallel offline partition

datanode/nodeinfo.go, datanode/partition.go, datanode/server.go, datanode/wrap_operator.go, master/api_service.go, master/cluster.go, master/metadata_fsm_op.go, metanode/nodeinfo.go, metanode/partition_free_list.go, storage/extent_store.go
=> Update: update datanode extend delete rate limiter

cmd/master/scripts/manage_admin_setnodeinfo.sh, master/api_service.go, master/cluster.go, master/config.go, master/const.go, master/metadata_fsm_op.go, metanode/metanode.go, metanode/nodeinfo.go, metanode/partition_free_list.go, proto/admin_proto.go
=> Node info 20200703

master/data_partition_check.go, master/meta_partition.go, master/metadata_fsm_op.go
delete illegal replica synchronous
N/A
N/A
N/A
=> enhancement: delete illegal replica synchronous

docker/run_docker.sh
=> Fix: fix run_docker.sh check disk avail size incorrect on linux

console/cutil/handler.go, master/gapi_volume.go
- Fix: permission of volume graphql api
None.
None.
None.
=> Fix: permission of volume graphql api

console/service/file.go, docker/conf/nginx.conf
Refactor: using path style when signurl by console
None.
None.
None.
=> Refactor: using path style when signurl by console

client/fuse.go, cmd/cmd.go, proto/version.go
Refactor: cfs-server  and cfs-client -v add baseVersion 2.1.0
=> Refactor: cfs-server  and cfs-client -v add baseVersion 2.1.0

cmd/cfg/console.json, docker/conf/console.json, docs/source/manual-deploy.rst, docs/source/user-guide/console.rst
=> Update the web front end to fix some bugs

docs/source/user-guide/yum.rst
Support yum install Console and ObjectNodes
=> doc: update yum install documentation

CHANGELOG.md
```
Some optimization was done on memory, object storage, metanode and etc since last release in Apr 9, 2020. 
```
=> Update CHANGELOG from v2.0.0 to v2.1.0

docker/monitor/grafana/provisioning/dashboards/chubaofs.json
=> Update: update docker grafana data size unit from IEC to Metric

fsck/cmd/check.go, fsck/cmd/clean.go, fsck/cmd/common.go, fsck/cmd/root.go, fsck/usage.md
=> fix: use persistent flags instead of local flags

cli/cmd/compatibility.go, docker/conf/metanode.json, docker/docker-compose.yml, metanode/btree.go, metanode/btree_memory.go, metanode/btree_rocks.go, metanode/const.go, metanode/free_list.go, metanode/inode.go, metanode/manager.go, metanode/manager_proxy.go, metanode/metanode.go, metanode/partition.go, metanode/partition_fsm.go, metanode/partition_fsmop.go, metanode/partition_fsmop_dentry.go, metanode/partition_fsmop_inode.go, metanode/partition_item.go, metanode/partition_op_dentry.go, metanode/partition_op_extent.go, metanode/partition_store.go, metanode/partition_store_ticket.go
=> Fix: fix metanode btree rocksdb bugs

docker/s3tests/base.py, docker/s3tests/test_acl.py, docker/s3tests/test_bucket_policy.py, objectnode/acl.go, objectnode/acl_handler.go, objectnode/policy.go, objectnode/policy_handler.go, objectnode/stringset.go
1. Add objectnode api 'deleteBucketPolicy'.
2. Add test cases about bucket acl and bucket policy.
3. Fix some parse errors.
None.
None.
None.
=> Enhancement: Add objectnode api 'deleteBucketPolicy' and related test cases

cli/api/metaapi.go, cli/cli.go, cli/cmd/cluster.go, cli/cmd/compatibility.go, cli/cmd/config.go, cli/cmd/const.go, cli/cmd/datanode.go, cli/cmd/datapartition.go, cli/cmd/fmt.go, cli/cmd/http_service.go, cli/cmd/metanode.go, cli/cmd/metapartition.go, cli/cmd/root.go, cli/cmd/user.go, cli/cmd/valid.go, cli/cmd/vol.go, docker/script/start_client.sh, docs/source/admin-api/cli/cli.rst, master/api_service.go, master/api_service_test.go, master/cluster.go, master/http_server.go, master/vol_test.go, proto/admin_proto.go, sdk/master/api_admin.go, sdk/master/client.go
1. Added log in cli tool  which fix #718 
2. Added `expand` & `shrink` capacity interfaces whitch fix #720
=> add expand/shrink capacity interfaces; introduce log to cli tool

docker/s3tests/test_bucket_policy.py
Fix test case out of order error.
```release-note
```
=> fix: test case out of order error

cli/cmd/const.go, cli/cmd/vol.go, sdk/master/api_admin.go
=> Enhancement: add zonename flag to cli tool

build/build.sh, cli/build.sh, client/build.sh, cmd/build.sh
Fix the issue of obtaining the latest tag of the current branch during
build.
None.
None.
None.
=> Fix: build script issue

cli/cmd/compatibility.go, master/filecheck.go
modify verify message
N/A
N/A
N/A
=> fixed: modify verify message

cli/cli.go, cli/cmd/config.go, docs/source/admin-api/cli/cli.rst, sdk/master/client.go
Add command for configuring request timeout for cli tool. 
None.
None.
None.
=> enhancement: configurable request timeout for cli tool 

objectnode/api_context.go, objectnode/api_middleware.go, objectnode/result_error.go
Add ump monitor log when the exception occurred.
```release-note
```
=> Enhancement: add ump monitor log

build/build.sh
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #777 
```release-note
```
=> Fix: fix build.sh of zip package with no git info

README.md, security/README.md, security/email-templates.md, security/security-release-process.md
- Add security disclosure process
- fixes #654 
None.
None.
=> Add security disclosure process

client/fs/file.go
=> Fix: refreshExtentsCache when open file

objectnode/fs_volume.go
- Fix issue of update ETag when list files.
None.
None.
None.
=> Fix: issue of update etag when list files

metanode/partition.go, metanode/partition_fsmop_dentry.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #786 
```release-note
```
=> Fix: fix metanode delete dentry deadlock bug

master/admin_task_manager.go, master/cluster.go, master/cluster_task.go, master/data_partition.go, master/data_partition_check.go, master/disk_manager.go, master/filecheck.go, master/meta_partition_manager.go, master/metadata_fsm_op.go, master/mocktest/data_server.go, master/vol.go, util/conn_pool.go
=> Release 20200720

Makefile, build/build.sh, cli/build.sh
=> Fix: fix cli build bug

datanode/const.go, datanode/partition.go, datanode/wrap_operator.go, metanode/partition_delete_extents.go
metanode optimize checkBatchDeleteExtents 
```release-note
```
=> Refactor: metanode optimize checkBatchDeleteExtents

docker/s3tests/test_object_list.py, objectnode/fs_volume.go
- Fix update etag issue when listing objects
- Add test case for listing objects
None.
None.
None.
=> Fix: update etag issue when listing objects

datanode/partition.go, datanode/wrap_operator.go
=> Refactor: datanode ignore delete error

docker/s3tests/test_object_list.py
- Enhancement: add test for list objects v2 etag validation
None.
None.
None.
=> Enhancement: add test for list objects v2 ETag validation

metanode/partition_delete_extents.go, metanode/partition_free_list.go, metanode/partition_fsmop.go, metanode/partition_item.go, proto/extent_key.go
=> Fix: add EXTENT_DEL file extentKey header and checksum verify

metanode/partition_delete_extents.go
=> Enhancement: update invalid extentKey unmarsharl error

client/fs/file.go
=> Fix:refreshExtentsCache when open file

cli/build.sh, docker/conf/nginx.conf, objectnode/api_handler_multipart.go, objectnode/api_handler_object.go, objectnode/api_middleware.go, objectnode/fs_volume.go
- Response Http400 after got unexpected EOF error when reading data from
request connection.
- Fix ldflag issue from `cli/build.sh`.
- Do not write failure status code if request connect closed by peer.
None.
None.
None.
=> Enhancement: error handling of ObjectNode

docker/monitor/grafana/provisioning/dashboards/chubaofs.json, master/monitor_metrics.go, util/exporter/counter.go, util/exporter/exporter.go, util/exporter/gauge.go, util/exporter/timepoint.go
=> Fix: fix exporter vol usage ratio error

datanode/const.go, datanode/partition.go, datanode/partition_raft.go, datanode/partition_raftfsm.go, datanode/wrap_operator.go, metanode/manager.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_delete_extents.go, metanode/partition_fsm.go, metanode/partition_fsmop.go
Fix: when mp/dp loadding, apply raftlog about : delete it self, then ignore this raft mesg
=> Fix: when mp/dp loadding, apply raftlog about : delete it self, then ignore this raft mesg

util/exporter/exporter_test.go
=> Fix: ci failed on util/exporter/exporter_test.go

objectnode/fs_store_user.go
Add ump log while getting user info failed from master.
```release-note
```
=> Enhancement: Add ump log while getting user info failed from master

client/fs/super.go, client/fuse.go, proto/mount_options.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_conn.go, sdk/data/wrapper/data_partition.go, sdk/data/wrapper/wrapper.go, util/iputil/addrselect.go, util/iputil/ip.go
=> feature: add near read support

ADOPTERS.md
=> doc: update ADOPTERS

fsck/usage.md
=> Enhancement:modify fsck command usage

metanode/partition.go
=> Refactor: change metaPartition store msg chan length to 100

metanode/partition_free_list.go, metanode/partition_fsmop_inode.go
revert fsmunlink logic to 1245b21e6c93c89d58fb74d3115167ebb97522e5\
=> Refactor:change fsmunlink logic

sdk/data/stream/extent_client.go, sdk/data/stream/stream_reader.go, sdk/data/wrapper/wrapper.go
=> Enhancement: update volume follower read config from master periodicity

metanode/manager_op.go
=> fix: opMetaBatchInodeGet can correct forwarding to raft leader

datanode/data_partition_repair.go, datanode/disk.go, datanode/limit.go, datanode/nodeinfo.go, datanode/partition.go, datanode/space_manager.go, datanode/wrap_operator.go, storage/extent_store.go
add autoExtentRepair limit on datanode
=> Refactor: add autoRepair limit on datanode and autoRepairExtent skip unavali extent repair task

sdklib/build.sh, sdklib/sdklib.go
- Enhancement: C lib for meta and data operation.
None.
None.
None.
=> Enhancement: C lib for meta and data operation.

.travis.yml
=> Enhancement: move unit test ahead of ltptest

README.md
Change `meeting notes` to `meeting minutes`.
None.
None.
None.
=> Update README.md that change 'meeting notes' to 'meeting minutes'.

datanode/partition.go
=> Refactor: datanode delete unused log

sdk/data/stream/extent_handler.go, sdk/data/wrapper/wrapper.go
=> fix: checkAllHostsIsAvail when TinyExtentType extent get connect failed

sdk/data/stream/extent_handler.go, sdk/data/wrapper/wrapper.go
=> fix: remove dp from rwPartitions when dp have no space to create extent

client/fs/file.go, objectnode/fs_volume.go, proto/fs_proto.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_writer.go
=> feature: introduce O_APPEND flag to the extent client

datanode/partition_op_by_raft.go
=> Fix: datanode start failed

master/cluster.go, master/cluster_task.go
=> Fix: error message shadowed in defer function when remove raft member

master/cluster.go, master/cluster_task.go, master/data_partition.go, master/meta_partition.go
=> Fix: Ensure concurrency safety in removeRaftMember function

sdk/data/wrapper/wrapper.go
=> fix: fix panic error when concurrent remove datapartition

CHANGELOG.md
Modify the description of `v2.2.0` in the `CHANGELOG.md` to improve readability.
fixes #890 
None.
None.
=> Update CHANGELOG.md for v2.2.0

CHANGELOG.md
=> CHANGELOG 2.2.1

CHANGELOG.md
Update `CHANGELOG.md` and makes release note of version v2.2.1 more readable.
None.
None.
None.
=> Makes release note of version v2.2.1 more readable.

docs/source/csv/performance-volume.csv
Replaced Chinese content to English from EN documentation.
fixes #896
None.
None.
=> Replaced Chinese content to English from EN documentation.

master/api_service.go, master/cluster.go, master/cluster_task.go, master/data_partition.go, master/meta_partition.go
=> Fix: Enlarge the range of decommission lock

datanode/const.go, datanode/data_partition_repair.go, datanode/limit.go, datanode/partition.go, datanode/partition_op_by_raft.go, datanode/partition_raftfsm.go, storage/extent_store.go
=> Enhancement: datanode accelerate recovery rate

cli/cli.go, cli/cmd/config.go, cli/cmd/const.go, cli/cmd/datapartition.go, cli/cmd/fmt.go, cli/cmd/metapartition.go, cli/cmd/root.go, proto/model.go, sdk/master/api_node.go, sdk/master/client.go
=> Enhancement: Diagnose and auto repair the partitions lacking replicas

master/api_service.go, master/cluster.go, master/const.go, master/gapi_volume.go, master/metadata_fsm_op.go, master/vol.go, proto/admin_proto.go, sdk/data/stream/extent_handler.go, sdk/data/wrapper/data_partition.go, sdk/data/wrapper/data_partition_selector.go, sdk/data/wrapper/data_partition_test.go, sdk/data/wrapper/default_random_selector.go, sdk/data/wrapper/k_faster_random_selector.go, sdk/data/wrapper/wrapper.go
=> Feature: introduce data partition selector

datanode/partition_raft.go, datanode/space_manager.go, datanode/wrap_operator.go, metanode/manager.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_fsmop.go, raftstore/partition.go
Do not remove and keeps data for deleted data partitions and meta partitions.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
None.
None.
=> Keep data for deleted data partition

datanode/partition_raft.go, datanode/space_manager.go, datanode/wrap_operator.go, metanode/partition.go, raftstore/partition.go
- Marks as expired and keep data for deleted partitions.
None.
None.
None.
=> Refactor: marks as expired and keep data for deleted partition.

raftstore/log_test.go, vendor/github.com/tiglabs/raft/util/log/log.go
Delete raft logs 7 days ago.
None.
None.
None.
=> enhancement: only keep raft logs from the past 7 days

CHANGELOG.md
Update `CHANGELOG.md` for version `2.2.2`
fixes #940 
None.
None.
=> Update CHANGELOG.md for v2.2.2

metanode/api_handler.go, metanode/disk.go, metanode/metanode.go
=> [Enhancement] add getDiskStat api for metanode

metanode/manager.go, metanode/manager_op.go
Signed-off-by: ansjsun <ansj-sun@163.com>
```release-note
```
=> fix metapartition load panic about expired

util/config/config.go
Persist const config file with fsync and remove it when persistion failed.
None.
None.
None.
=> Fix: persist const config file with fsync

util/config/config.go
Refactor: const config validation and persistion process
None.
None.
None.
=> Refactor: const config validation and persistion process

master/cluster.go
=> Fix: master cpu too high

java/README.md, java/pom.xml, java/src/main/test/java/Test_CfsMount.java
1.add the CfsMount unit test
2.add a junit dependency to java/pom.xml
3.modify java/README.md about configure Junit environment
```release-note
```
=> ADD unit test

master/vol.go
Signed-off-by: yangqingyuan8 <yangqingyuan8@jd.com>
```release-note
```
=> fix:update nextStart's value in mp split

datanode/partition_raftfsm.go
- Fix the issue that Master report timeout error when executing data partition decommission operation.
None.
None.
None.
=> Fix: data partition decommission timeout issue

util/log/log.go
Change log file permission to '0666'.
None.
None.
```release-note
```
=> enhancement: change log file permission to '0666'

sdk/data/stream/extent_handler.go
=> fix: avoid streamer become unable to write

util/log/log.go, util/log/log_test.go, util/log/rotate.go
Rotate log and change log file permission.
```release-note
```
=> enhancement: rotate log and change log file permission

util/log/log.go, util/log/log_test.go, util/log/rotate.go
Rotate log and change log file permission.
```release-note
```
=> enhancement: rotate log and change log file permission [version: release-20200720]

datanode/data_partition_repair.go, proto/packet.go
=> Fix: set maxAutoRepair wait time to 30 min

datanode/partition.go, datanode/partition_raftfsm.go, vendor/github.com/tiglabs/raft/raft.go, vendor/github.com/tiglabs/raft/raft_fsm.go, vendor/github.com/tiglabs/raft/status.go
Signed-off-by: Mofei Zhang <mofei2816@gmail.com>
```release-note
```
=> Add some log for debuging

cli/cmd/const.go, cli/cmd/datapartition.go, cli/cmd/fmt.go, cli/cmd/metapartition.go, cli/cmd/vol.go, master/api_service.go, master/api_service_test.go, master/cluster.go, master/cluster_test.go, master/config.go, master/const.go, master/gapi_volume.go, master/metadata_fsm_op.go, master/server.go, master/topology_test.go, master/vol.go, master/vol_test.go, proto/admin_proto.go, proto/model.go, sdk/master/api_admin.go, sdk/master/api_node.go, sdk/master/client.go
1. concurrent balance distribution of partitions; 
2. enable setting autoRepair in volume level; 
3. list volume detail info in cli.
=> enhancements about multi-zone

datanode/partition_raft.go, datanode/server.go, docker/conf/datanode.json, docker/conf/datanode2.json, docker/conf/datanode3.json, docker/conf/metanode.json, docker/conf/metanode2.json, docker/conf/metanode3.json, metanode/const.go, metanode/metanode.go, metanode/raft_server.go
Signed-off-by: ansjsun <ansj-sun@163.com>
```release-note
```
=> add tickinterval for metanode and datanode

master/cluster.go
=> Fix: duplicate hosts in host selection

authnode/config.go, authnode/server.go, master/config.go, master/server.go, master/topology.go, metanode/manager.go, metanode/metanode.go, raftstore/raftstore.go
modify the way to print log info from fmt to log in daemon server
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #991
```release-note
```
=> fix: set output from fmt to log for server run in daemon

vendor/github.com/tiglabs/raft/raft_fsm.go
=> Remove unnecessary logging

master/api_service.go
=> Fix: add default zone name in volCreate

metanode/inode.go, metanode/partition_fsmop_dentry.go
Change the mtime of the directory when creating or deleting dentry.
None.
None.
```release-note
```
=> fix: change the mtime of the directory when creating or deleting dentry

metanode/partition_delete_extents.go
Signed-off-by: ansjsun <ansj-sun@163.com>
```release-note
```
=> fix delete extents goroutine to loop when panic

master/monitor_metrics.go, util/exporter/gauge.go
=> Enhancement: clear invalid vol metrics

master/api_service.go
=> Fix: implement volume expand/shrink capacity

master/api_service_test.go, master/cluster.go
=> fix: add default zone name

master/api_service_test.go, master/cluster_test.go
=> Fix: disable auto repair of common vol in unit test

cli/cli.go, cli/cmd/cluster.go, cli/cmd/compatibility.go, cli/cmd/datanode.go, cli/cmd/datapartition.go, cli/cmd/fmt.go, cli/cmd/metanode.go, cli/cmd/metapartition.go, cli/cmd/root.go, cli/cmd/user.go, cli/cmd/vol.go
=> Enhancement: check used size of datapartition

util/exporter/exporter.go
=> expose /metrics/prometheus interface

util/exporter/consul_register.go, util/exporter/exporter.go
=> add meta when register to consul

metanode/manager_op.go, proto/packet.go
=> Fix: if metapartition cannot find ,return op not exsit error to client

datanode/wrap_operator.go
Refactor: success when removing non-exist DP.
> Response success to Master when removing a non-exists Data Partition.
=> Refactor: success when removing non-exist DP

metanode/partition_delete_extents.go
Reverts chubaofs/chubaofs#1004
=> Revert "fix delete extents goroutine to loop when panic"

java/src/main/java/io/chubao/fs/CfsMount.java, java/src/main/java/io/chubao/fs/TestCfsClient.java
"add exception in java sdk"
```release-note
```
=> Add exception for java APIs.

sdk/data/stream/extent_handler.go
This reverts commit ff82898d69073d01a0aca89ab39b2e632d09a8fc.
ff82898d69073d01a0aca89ab39b2e632d09a8fc may lead to silence data loss.
```release-note
```
=> Revert "fix: avoid streamer become unable to write"

client/fs/dir.go, client/fs/file.go, client/fs/super.go, client/fuse.go, cmd/cmd.go, proto/mount_options.go, util/log/log.go, util/log/log_get.go, util/log/rotate.go, util/ump/ump.go, util/ump/ump_async_log.go
Signed-off-by: shijiesun <ssj280@gmail.com>
in order to monitor client performance and collection client alarm
```
add ump function and alarm log, update log rotate
```
=> Feature:add ump function and alarm log, update log rotate

client/fs/dir.go, proto/fs_proto.go
=> Fix ： warning mesg on remove

client/fs/super.go
Signed-off-by: shijiesun <ssj280@gmail.com>
fix: remove act type from ump alarm key
```
ump alarm key changed
```
=> fix: remove act type from ump alarm key

docs/source/admin-api/master/user.rst
"Modify the description of forced transfer volume"
```release-note
```
=> Modify user.rst

docs/source/design/objectnode.rst
=> fix: docs build error

master/user.go
**What this PR does / why we need it**:fix bug: update user type with invalid user type
```release-note
```
=> "fix: update user type with invalid user type"

docs/source/admin-api/master/volume.rst
Signed-off-by: Ulrica Zhang <1002432810@qq.com>
modify the document of stating volumes operation
modify the document of updating volume operation
```release-note
```
=> modify update volume docs

docs/source/admin-api/master/user.rst
**What this PR does / why we need it**:Add the usage of instruction:get users of volume
```release-note
```
=> "Add getUsersOfVol"

java/README.md, java/build.sh, java/src/main/java/io/chubao/fs/CfsMount.java, java/src/main/java/io/chubao/fs/TestCfsClient.java, java/src/main/resources/.gitkeep
**What this PR does / why we need it**:enhance:Pack libcfs.so into jar 
```release-note
```
=> enhance:pack libcfs.so into jar

test/userTest.sh
**What this PR does / why we need it**: Prepare test case for continuous integration.
```release-note
```
=> Add file test to store testcase and add userTest.sh under this file

java/src/main/java/io/chubao/fs/CfsMount.java
=> Add IsDIr() and IsRegular() in java sdk

master/api_service.go
=> fix:support returning usedRatio in searching volstat

test/volumeTest/deleteVol.sh, test/volumeTest/getVol.sh, test/volumeTest/listVol.sh, test/volumeTest/statVol.sh, test/volumeTest/test_basic.sh, test/volumeTest/test_volume.sh, test/volumeTest/updateVol.sh, test/volumeTest/volumeTest.md
Signed-off-by: Ulrica Zhang <1002432810@qq.com>
add testing script of volume operations
```release-note
```
=> add volume test to master

master/cluster.go, master/data_partition.go
Signed-off-by: yuxiaobo <yuxiaobo@oppo.com>
```release-note
```
=> fix: deadlock when add dp raft member

.travis.yml
=> fix: docker pull limit rate issue

sdk/data/wrapper/wrapper.go
=> fix: func sortHostsByDistance change dp's hosts

.gitignore, build.sh, build/build.sh, docker/script/build.sh
=> Fix libsdk make issue

docs/source/user-guide/monitor.rst, util/exporter/consul_register.go, util/exporter/exporter.go, util/exporter/exporter_test.go
=> add conusl meta & filter local ip

client/fs/dir.go, client/fs/file.go, datanode/metric.go, datanode/server.go, datanode/wrap_operator.go, docker/monitor/grafana/provisioning/dashboards/chubaofs.json, docs/source/user-guide/monitor.rst, metanode/manager.go, metanode/metanode.go, metanode/metrics.go, objectnode/api_middleware.go, sdk/meta/operation.go, util/exporter/counter.go, util/exporter/exporter.go, util/exporter/exporter_test.go, util/exporter/gauge.go, util/exporter/histogram.go, util/exporter/timepoint.go
=> enhance: add vol level & io monitor report

CHANGELOG.md
=> docs: update change log for v2.3.0

datanode/partition_raft.go, datanode/server.go, metanode/const.go, metanode/metanode.go, metanode/raft_server.go
**What this PR does / why we need it**:The network environment of different companies is different, it is better to make the TickInterval parameter configurable
```release-note
```
=> support TickInterval configurable

datanode/partition_raft.go
This commit fixes the issue which may an appied ID out of range error occurred if a datanode was closed abnormally.
=> Enhancement: persist applied ID before makes raft log truncating

CHANGELOG.md
docs: update changelog for v2.4.0
=> docs: update changelog for v2.4.0

ADOPTERS.md
=> docs: update adopters

ADOPTERS.md
=> docs: update link of club factory

sdk/data/wrapper/data_partition_selector.go
=> change: suppress init data selector warning

datanode/partition.go, metanode/manager_proxy.go
=> change: add logs for meta proxy

cli/cmd/gen_config.go
=> Add role and clusterName field for gencfg command config

cli/cmd/const.go, cli/cmd/vol.go, datanode/wrap_operator.go, master/api_service.go, master/api_service_test.go, master/cluster.go, master/cluster_task.go, master/cluster_test.go, master/config.go, master/const.go, master/data_node.go, master/data_partition_map.go, master/gapi_cluster.go, master/gapi_volume.go, master/http_server.go, master/master_manager.go, master/meta_partition.go, master/metadata_fsm_op.go, master/node_selector.go, master/server.go, master/topology.go, master/vol.go, master/vol_test.go, proto/admin_proto.go, proto/errors.go, proto/model.go, sdk/data/wrapper/wrapper.go, sdk/master/api_admin.go, util/log/log.go
=> Add feature domain for cross zone

cli/cmd/vol.go
fix: cli tool typo
Signed-off-by: Plomty.Li <vnline1202@gmail.com>
=> fix: cli tool typo

docker/monitor/grafana/provisioning/dashboards/chubaofs.json, master/monitor_metrics.go
vol_meta_count for inode/dentry/dp/mp metrics
Signed-off-by: Justice <zhengyi.zhu.hust@gmail.com>
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: enhancement #1190
=> Enhancement: add master metrics vol_meta_count to export vol

docker/script/run_test.sh
=> Enhancement: add ci check for ltptest result

docker/ltp/runtest/fs
Use the version corresponding "runtest/fs" and unlock some test cases.
```release-note
```
=> change: update and unlock ltp test cases

master/const.go, master/monitor_metrics.go
Signed-off-by: Justice <zhengyi.zhu.hust@gmail.com>
```release-note
```
=> Enhancement: add vol usedRatio warn log when usage > 90%

.gitlab-ci.yml
=> Enhancement: update gitlab-ci for docker

docker/script/run_test.sh
Signed-off-by: zhuzhengyi001 <zhuzhengyi001@ke.com>
```release-note
```
=> Fix: fix ltptest ci bug

master/filecheck.go
=> word correct

docker/monitor/grafana/provisioning/dashboards/chubaofs.json
Signed-off-by: zhuzhengyi001 <zhuzhengyi001@ke.com>
```release-note
```
=> Enhancement: change grafana volume used size rate from rate to deriv

util/exporter/exporter.go
problem: if `epxporterPort` not set, `pushAddr` is also not valid
**Which issue this PR fixes #1175**
=> make push addr valid if export is not set

metanode/partition_fsmop_inode.go, metanode/sorted_extents.go, vendor/github.com/tiglabs/raft/proto/codec.go, vendor/github.com/tiglabs/raft/transport_heartbeat.go
=> Cherry pick to release 2.4

java/src/main/java/io/chubao/fs/CfsLibrary.java, java/src/main/java/io/chubao/fs/CfsMount.java, java/src/main/java/io/chubao/fs/TestCfsClient.java, libsdk/libsdk.go
Signed-off-by: lixiang12407 <lixiang12407@gmail.com>
Refactor the libsdk to support standard interface.
=> support the posix standard interface

cli/cmd/user.go, cli/cmd/vol.go, proto/admin_proto.go, proto/model.go, proto/mount_options.go, sdk/master/api_admin.go
Cleanup redundant and dead code.
```release-note
```
=> cli: Cleanup redundant and dead code

cli/cmd/config.go
Cli allows setting multiple master addersses. But it does not split
them into slice correctly. This patch fixes it, so that we could
set master address like,
cfs-cli config set --addr IP1:PORT1,IP2:PORT2...
```release-note
```
=> cli: Fix handling option of config set --addr

MAINTAINERS.md
=> doc: update maintainers

metanode/raft_server.go
Signed-off-by: 李艳坤 <lioveni99@gmail.com>
```release-note
```
=> check whether the direcotry exists

client/fs/const.go, client/fs/file.go, sdk/data/stream/extent_client.go, sdk/meta/meta.go
=> Enhance pass through errno

sdk/master/request.go
=> Enhancement: Add version info into http req

metanode/manager.go
Signed-off-by: justice <justice_103@126.com>
This commit avoids the unlocked read access to "partitions" field.
```release-note
```
=> Fix: replace metanode log partitions map with err

metanode/manager.go
=> change: add log for loading meta partitions

metanode/api_handler.go
use `curl metaIp:17220/getRaftStatus?id=pid | python -m json.tool` to get mp's raft status info
=> enhance: add getRaftStatus for metanode

datanode/partition.go, datanode/wrap_operator.go, master/api_service.go, master/cluster.go, master/cluster_task.go, master/cluster_test.go, master/data_partition.go, master/data_partition_check.go, master/data_replica.go, master/disk_manager.go, master/meta_partition.go, master/meta_partition_manager.go, master/metadata_fsm_op.go, master/vol.go, metanode/manager.go, metanode/manager_op.go, proto/model.go, raftstore/raftstore.go, vendor/github.com/tiglabs/raft/raft_fsm.go, vendor/github.com/tiglabs/raft/server.go
this pr is used to avoid decommission failure in some case
=> fix: fix some decommission bug

build/build.sh
Signed-off-by: justice <justice_103@126.com>
```release-note
```
=> Enhancement: remove librocksdb find when build server

cli/cmd/config.go, cli/cmd/user.go, cli/cmd/vol.go, client/fs/const.go, client/fs/dir.go, client/fs/file.go, metanode/manager.go, metanode/metanode.go, metanode/partition_fsm.go, proto/admin_proto.go, proto/model.go, proto/mount_options.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_conn.go, sdk/master/api_admin.go, sdk/meta/meta.go, vendor/bazil.org/fuse/fs/serve.go, vendor/github.com/tiglabs/raft/raft_snapshot.go
=> Backport to release 2.4

objectnode/api_handler_object.go
=> fix: s3 get range zero to zero EOF

util/exporter/exporter.go
Signed-off-by: justice <justice_103@126.com>
```release-note
```
=> Enhance: use random port if exporterPort <=0

CHANGELOG.md
=> doc: update change log for v2.4.1

docker/s3tests/base.py, docker/s3tests/test_object_get_range.py, objectnode/api_handler_object.go
=> fix: fix objectnode get object range

ROADMAP.md
=> roadmap. update

client/fuse.go, cmd/cmd.go, util/log/log.go
=> fix: if server recive kill-signal before being running-state, server will can't be killed graceful

repl/packet.go
enhance. improve performance of write. data allocated didn't put back to buffer pool
=> enhance. improve performance of write. data allocated didn't put back to buffer pool

sdk/data/stream/stream_writer.go
=> fix: create new extent handler if storeMode changed

sdk/data/stream/stream_writer.go
When a handler sends packets failed, it forwards the failed packets to a
recover handler. However, the current open handler recorded in the
streamer remains the same. So when closing open handler, we need to
follow the recover handlers to flush.
Reported-by: bboyCH4 <hechi1014@126.com>
Signed-off-by: bboyCH4 <hechi1014@126.com>
```release-note
```
=> fix: follow recover handlers when closing open handler

datanode/server.go, datanode/wrap_operator.go, datanode/wrap_post.go, datanode/wrap_prepare.go
for better performance update module of exporter  report configuable with ratio
#1315
=> feature.config exporter output ratio to reduce cost

datanode/server.go, datanode/wrap_prepare.go
exporter report counter incr with atomic be more appropriate
=> fix. exporter report counter incr with atomic be more appropriate

regression/idempotent/main.go, regression/overlapping/main.go
=> test: add regression test case

CHANGELOG.md
=> doc: update change log for v2.5.0

datanode/server.go, datanode/server_handler.go, datanode/wrap_operator.go, datanode/wrap_post.go, datanode/wrap_prepare.go, repl/packet.go
Metrics Degrade Level
- minus value: turn off metrics collection.
- 0 or 1: full metrics.
- 2: 1/2 of the metrics will be collected.
- 3: 1/3 of the metrics will be collected.
- ...
```release-note
```
=> Feat support exporter degrade

datanode/limit.go, sdk/data/stream/extent_handler.go, sdk/data/wrapper/data_partition.go
=> enhance: clear exclude if no dp is selected

client/fuse.go, datanode/limit.go, datanode/server.go, datanode/server_handler.go, datanode/wrap_operator.go, datanode/wrap_post.go, datanode/wrap_prepare.go, regression/idempotent/main.go, regression/overlapping/main.go, repl/packet.go, sdk/data/stream/extent_handler.go, sdk/data/stream/stream_writer.go, sdk/data/wrapper/data_partition.go
=> Backport to 2.4

README.md, datanode/data_partition_repair.go, datanode/disk.go, docker/Dockerfile, docker/build_docker.sh, docker/docker-compose.yml, docker/script/build.sh, metanode/manager.go, metanode/partition_fsmop.go, metanode/partition_item.go, storage/extent_store.go
=> Enhance minor changes datanode

MAINTAINERS.md, datanode/data_partition_repair.go, datanode/server.go, datanode/server_handler.go, datanode/space_manager.go, datanode/wrap_operator.go, datanode/wrap_post.go, datanode/wrap_prepare.go, repl/packet.go, sdk/data/stream/stream_writer.go, storage/extent.go
=> backport to release 2.5

master/api_service.go, master/cluster.go
1. hold cluster lock when setting rdonly
2. refactor finding partitions to be offlined when migrating
=> Fix setting rdonly & migrating

docker/s3tests/test_object_list_page.py, objectnode/fs_volume.go
=> Fix s3 list objects skipped some objects

master/admin_task_manager.go, master/api_service_test.go, master/server.go
This commit uses dial connection instead of connection pool for
master's synced admin tasks.
```release-note
```
=> enhance: use dial conn for synced master admin tasks

datanode/const.go, datanode/data_partition_repair.go, datanode/disk.go, datanode/limit.go, datanode/metric.go, datanode/nodeinfo.go, datanode/partition_raft.go, datanode/server.go, datanode/server_handler.go, datanode/wrap_operator.go, datanode/wrap_post.go, datanode/wrap_prepare.go, raftstore/config.go, raftstore/raftstore.go, repl/packet.go, storage/extent.go, storage/extent_store.go, util/buf/buffer_pool.go, util/unit.go, vendor/github.com/tiglabs/raft/config.go
=> Upstream release 2.4 part.3

client/fs/dir.go, client/fs/super.go, docker/s3tests/env.py, docker/s3tests/test_object_list_page.py, docker/script/run_test.sh, objectnode/fs_volume.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_writer.go
=> Upstream release 2.4 part.5

ADOPTERS.md, README.md
=> update: add end user company information and update contact details

README.md
=> update: update contact details

sdk/data/stream/stream_writer.go
This reverts commit 8e1b4ec33f5ead30ee005f9f69fbfa28ffc07001.
Signed-off-by: 李艳坤 <liyankun01@58.com>
```release-note
```
=> Revert "fix: create new extent handler if storeMode changed"

build/build.sh, cli/cmd/vol.go, depends/rocksdb-5.9.2/Makefile, libsdk/libsdk.go, sdk/data/blobstore/writer.go, sdk/data/stream/stream_writer.go
additional bug fix related with v3.0.0 pull request
=> additional bug fix related with v3.0.0 pull request

build/build.sh, cli/cmd/vol.go, depends/rocksdb-5.9.2/Makefile, libsdk/libsdk.go, sdk/data/blobstore/writer.go, sdk/data/stream/stream_writer.go
=> merge to release3.0

master/api_service.go, master/cluster.go, master/data_partition_check.go, master/disk_manager.go, master/gapi_cluster.go, sdk/data/wrapper/wrapper.go, sdk/meta/api.go, util/conn_pool.go
1.fix migration hang bug 
2. update client route cache update period
=> fix bugs caused code merge

README.md
Update readme since cubefs moved from sandbox to incubate in cncf
=> update: Update readme since cubefs moved from sandbox to incubate in cncf

CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md, MAINTAINERS.md, README.md, ROADMAP.md, security/README.md, security/email-templates.md, security/security-release-process.md
Update md doc since cubefs moved from sandbox to incubate in cncf!
=> Update md doc since cubefs moved from sandbox to incubate in cncf!

storage/extent.go
=> fix: recover delete tiny code to avoid record tiny repeatedly

master/api_service.go, master/meta_partition.go, storage/extent.go
[several bug fix and feature](https://github.com/cubeFS/cubefs/pull/1435)
=> several bug fix and feature

README.md
Signed-off-by: zhangtianjiong <hanhanztj@sina.com>
```release-note
```
=> refactor:rename package name.

README.md, java/README.md, java/pom.xml, java/src/main/java/io/cubefs/fs/CfsLibrary.java, java/src/main/java/io/cubefs/fs/CfsMount.java, java/src/main/java/io/cubefs/fs/TestCfsClient.java
1) update: update main features introduction
2) refactor:rename package name.
=> update readme 

MAINTAINERS.md
Signed-off-by: slasher <mcq.sejust@gmail.com>
=> chore: add MAINTAINERS of blobstore

blobstore/api/proxy/lb_client.go, blobstore/api/scheduler/client.go, blobstore/scheduler/shard_repairer.go, blobstore/util/selector/selector.go, blobstore/util/selector/selector_test.go
#1483
Signed-off-by: slasher <mcq.sejust@gmail.com>
=> bugfix(blobstore): division by zero if getter returns nil on RoundRobin

build.sh
arm 64 cannot download zlib
Signed-off-by: zphj1987 <zphj1987@gmail.com>
=> fix #1484 arm 64 cannot download zlib

README.md
Signed-off-by: xiaochunhe<626148589@qq.com>
update the features description
=> update: feature in readme

blockcache/bcache/bcache_disk_store.go, client/fuse.go, datanode/disk.go, master/api_service.go, master/server.go, sdk/data/manager/limiter.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_reader.go, sdk/data/stream/stream_writer.go
enhance and fix v3.1.0 committed
v3.1.0
=> enhance and fix v3.1.0 committed

docs/source/faq.rst, master/admin_task_manager.go
=> FIX: correct an ambiguous typo mistake

storage/fallocate_linux.go, util/unit.go
Call fallocate, return code Interrupt error, should try again
Signed-off-by: YankunLi <liyankun01@58.com>
```release-note
```
=> storage: fallocate return interrupt err try again

ADOPTERS.md, depends/tiglabs/raft/raft_snapshot.go, docker/Dockerfile-dev, docs/source/faq.rst, master/admin_task_manager.go, master/cluster.go, metanode/manager.go, metanode/metrics.go, storage/fallocate_linux.go, util/unit.go
rebase master and release v3.1.1
=> rebase master and release v3.1.1

blobstore/api/clustermgr/volume.go
Signed-off-by: tangzhixiang <tangzhixiang@oppo.com>
=> blobstore: fix(clusterMgr): fix chunk report 502 error

INSTALL.md
Signed-off-by: leonrayang <changliang@oppo.com>
update: update rpm packe to 3.2.0
=> update: update rpm packe to 3.2.0

master/cluster.go, master/server.go
Signed-off-by: baijiaruo <baijiaruo@126.com>
master: delete some unused variables
#1579 
```release-note
```
=> master: delete some unused variables

master/config.go
Fix the configuration annotation.
=> Fix: update the config annotation

datanode/disk.go, datanode/nodeinfo.go, datanode/partition_raft.go, datanode/wrap_operator.go, datanode/wrap_prepare.go, master/api_service.go, master/cluster.go, master/data_partition.go, master/http_server.go, master/limiter.go, master/meta_partition.go, master/vol.go, proto/admin_proto.go, repl/repl_protocol.go, sdk/data/manager/limiter.go, util/buf/buffer_pool.go, util/log/log.go
enhance: split bufferPool into several channels to reduce cost of lock caused by channel select  #1585 
update: update vol replica 3 to 2 and take effect on the 3 replicas already be created  #1605 
update: disk limiter.update write limit take effect at prepare stage to prevent high memory cost #1607
add feature.master add interface to support change leader of meta partition and data partition #1606
update: two replicas.enable datapartition be dropped by raftForce update ReplicaNum and consistent with volume  #1608
update: qos use specified log file #1604
=> add some features and optimizations

datanode/nodeinfo.go, master/api_service.go, master/cluster.go, master/http_server.go, master/vol.go, proto/admin_proto.go, repl/repl_protocol.go, util/buf/buffer_pool.go
=> update:fmt code

blobstore/api/clustermgr/volume.go
Signed-off-by: tangzhixiang <tangzhixiang@oppo.com>
```release-note
```
=> fix(clusterMgr): fix chunk report 502 error

docs/source/user-guide/docker.rst
=> fix: fixed small error in docs

datanode/data_partition_repair.go, datanode/wrap_operator.go, master/data_replica.go, master/limiter.go, master/topology.go, proto/packet.go, sdk/data/manager/limiter.go, storage/extent_store.go, storage/persistence_crc.go
=> [BugFix] Fix some typos

blobstore/api/access/client.go, blobstore/api/access/client_test.go
fix access api of blobstore for status code is inconsistent with error.
=> Fix api of blobstore

datanode/metric.go, datanode/server.go
[Enhancement] add monitor for lackPartitions in datanode
=> [Enhancement] add monitor for lackPartitions in datanode

CHANGELOG.md
=> update: chang log update from 2.5.1 to 3.2.0

master/api_service.go, master/meta_partition.go, master/monitor_metrics.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_free_list.go, proto/admin_proto.go
add metric for freeList 
master get the freelist length of each mp from mp heartbeat
=> Enhancement: add metric for freeList

datanode/space_manager.go, master/api_args_parse.go, master/api_service.go, master/cluster.go, master/const.go, master/data_node.go, master/data_partition.go, master/disk_manager.go, master/http_server.go, master/metadata_fsm_op.go, master/operate_util.go, proto/admin_proto.go
[Enhancement] support exclude decommissioned disk when create data partition and add recommission disk api
=> [Enhancement] support exclude decommissioned disk when create data partition and add recommission disk api

datanode/server.go
We should remove connection after `SmuxConn` or `TcpConn` is closed.
=> [BugFix] Should remove connection after session is closed

master/monitor_metrics.go
Add not writable metanode/datanode metric
=> Enhancement: Add not writable mn/dn metric

master/monitor_metrics.go
=> update: go fmt

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
assign to xiaochunhe, leonrayang
Signed-off-by: slasher <shenjie1@oppo.com>
=> chore(doc): change default assignees in issue template

docs-zh/source/user-guide/csi-driver.rst
=> [doc] update the CSI guide document(zh)

INSTALL.md, docs-zh/source/user-guide/yum.rst, docs/source/user-guide/yum.rst
=> remove monitor from docs

blobstore/common/rpc/argument.go, blobstore/common/rpc/argument_test.go, blobstore/common/rpc/context.go, blobstore/common/rpc/proto.go
self-defined argument decoder with request body
=> self-defined argument decoder with request body

.github/workflows/release_test.yml
run ltp test when push or pull request to release branches
=> test(ci): run ltp test when push or pull request to release branches

util/stat/statistic.go, util/stat/statistic_test.go
reduced util stat testing duration
=> test(util): reduced util stat testing duration

docs-zh/source/deploy/docker.md
=> docs(docs-zh): add blobstore docker docs

datanode/metric.go, datanode/server.go, datanode/stat.go
[Enhancement] check data partition in memory match with those in disk and report lack data partition to the metric
=> [Enhancement] check data partition in memory match with those in disk and report lack data partition to the metric

datanode/partition_raftfsm.go, datanode/server.go, master/http_server.go, master/server.go, metanode/btree.go, metanode/const.go, metanode/metanode.go, metanode/partition_fsm.go, metanode/partition_fsmop_inode.go, metanode/server.go, shell/depoly.sh, shell/genConf.sh, shell/genIp.sh, shell/stop.sh, shell/tpl/client.tpl, shell/tpl/data.tpl, shell/tpl/master.tpl, shell/tpl/meta.tpl
1. support bind targetIp to start master&meta&data service
2. support depoly cluster at one node.
=> support bind targetIp to start service

fsck/cmd/common.go, fsck/cmd/getInfo.go, fsck/cmd/root.go, fsck/usage.md
add a fsck cmd to get the file/dir info conveniently
=> [Enhancement] add fsck cmd to get inode info

docs-zh/source/user-guide/file.md
=> [feature] add file system usage

blobstore/api/clustermgr/client.go, blobstore/blobnode/shard_test.go, blobstore/blobnode/worker_service_test.go, blobstore/common/rpc/config.go, blobstore/common/rpc/context_test.go, blobstore/common/rpc/lb.go, blobstore/common/rpc/simple.go, blobstore/common/rpc/simple_test.go
TransportConfig{
MaxConnsPerHost:     10,
MaxIdleConns:        1000,
MaxIdleConnsPerHost: 10,
IdleConnTimeoutMs:   10 * 1000,
}
closes #1683
=> feat(rpc): set default rpc transport config

docs-zh/source/deploy/k8s.md
improve k8s deployment documents
=> docs(docs-zh): improve k8s deployment documents

docs-zh/source/deploy/node.md
add docs to support start cluster by  shell in one node.
=> docs(docs-zh): add docs to start cubefs cluster by shell

docs-zh/source/maintenance/configs/blobstore/access.md
=> docs(docs-zh): add config of blobstore's access

docs-zh/source/faq/fuse.md, docs-zh/source/index.rst, docs-zh/source/sidebarConfig.js, docs-zh/source/user-guide/fuse.md
=> docs(docs-zh): add fuse usage

docs-zh/source/maintenance/admin-api/blobstore/clustermgr.md
add clustermgr mange disk and volume order in document
```release-note
```
=> docs(docs-zh): add clustermgr disk manage order

cli/cmd/vol.go
=> update: let followerRead set false while docker volume create

cli/cmd/vol.go, master/cluster.go, master/data_partition_map.go, master/metadata_fsm_op.go
There's some cases need to repair.
=> Fix bug in follower read dps from master

blobstore/common/rpc/context.go, blobstore/common/rpc/lb.go, blobstore/common/rpc/proto.go, blobstore/common/rpc/server_test.go, blobstore/common/rpc/simple.go
=> decode user defined type from response

.github/workflows/release_test.yml
=> chore: disable release ci checks

blobstore/api/proxy/allocator.go, blobstore/api/proxy/client.go, blobstore/api/proxy/client_test.go, blobstore/cli/access/access.go, blobstore/cli/access/cluster.go, blobstore/cli/app.go, blobstore/cli/blobnode/chunk.go, blobstore/cli/clustermgr/clustermgr.go, blobstore/cli/clustermgr/volumemgr.go, blobstore/cli/config/cache.go, blobstore/cli/config/cluster.go, blobstore/cli/proxy/allocator.go, blobstore/cli/proxy/proxy.go, blobstore/cli/scheduler/scheduler.go, blobstore/cli/toolbox/shard.go, blobstore/cli/toolbox/toolbox.go, blobstore/testing/mocks/api_proxy.go
1. show allocator's volume status. `proxy allocator list`
2. decode chuck id  `blobnode chunk id `
3. add shard tool for blobnode. `toolbox shard`
=> add some cli tools in blobstore

README.md
replace the Chinese document address
=> chore(README): replace the Chinese document address

blobstore/cli/clustermgr/clustermgr.go, blobstore/cli/clustermgr/raftdb.go
1. add cli tools for cm crash recovery
=> feat(blobstore): add raft db tools for clustermgr in cli

docs-zh/source/maintenance/admin-api/master/datanode.md
=>  docs(docs-zh): add api document for datnode/disk decommission

docs-zh/source/maintenance/admin-api/master/datanode.md
=> docs(docs-zh): add api document for datnode/disk decommission

docs-zh/source/maintenance/admin-api/blobstore/scheduler.md
fix leader stats path of scheduler
=> docs(docs-zh): fix leader stats path of scheduler

blobstore/Dockerfile, blobstore/Makefile, docs-zh/source/deploy/docker.md, docs-zh/source/deploy/verify.md, docs-zh/source/maintenance/tool.md, docs-zh/source/user-guide/blobstore.md
rename blobstore's cli to blobstore-cli
=> rename blobstore's cli to blobstore-cli

cli/cmd/fmt.go, master/api_args_parse.go, master/api_service.go, master/cluster.go, master/data_node.go, master/data_partition.go, master/meta_node.go, proto/model.go, util/unit.go
1、To manage cluster by cfs-cli tool conveniently, enable to show dn/mn info include domain addr or get dn/mn info by domain addr
2、To show metapartition replica repair progress, show MaxInodeID of metapartition replica when using command './cfs-cli  metapartition info'
=> [Enhancement] enable to show info include domain addr or get info by domain addr

master/api_service.go, master/cluster.go, master/data_partition.go, master/http_server.go, master/metadata_fsm_op.go, proto/admin_proto.go
automatically add data replica for data partition which lack replica
=> [Enhancement] automatically add data replica for data partitions which lack replica

docs-zh/source/community/overview.md, docs-zh/source/maintenance/code.md, docs-zh/source/maintenance/log.md, docs-zh/source/maintenance/tool.md, docs-zh/source/sidebarConfig.js
1. docs(docs-zh): fix some descriptions in the docs
2. docs(docs-zh): add error code description
=> add code for docs

storage/extent.go
1、The crc value is calculated repeatedly.
2、Call ExtentStore.checkOffsetAndSize and Extent.checkOffsetAndSize repeatedly in the read/write process.
=> [Enhancement] Remove some redundant code

master/api_service.go, master/cluster.go, master/vol.go, proto/errors.go
Add check if vol has available space before create data partition
so that creating new data partition manually or automatically is not allowed when vol usage reaches its capacity.
=> [Enhancement] add check if vol has available space before create data partition

docs/source/deploy/k8s.md, docs/source/deploy/manual-deploy.md, docs/source/deploy/node.md, docs/source/deploy/requirement.md, docs/source/deploy/yum.md, docs/source/evaluation/meta.md, docs/source/evaluation/tiny.md, docs/source/maintenance/admin-api/blobstore/base.md, docs/source/maintenance/admin-api/blobstore/blobnode.md, docs/source/maintenance/admin-api/master/cluster.md, docs/source/maintenance/admin-api/master/datanode.md, docs/source/maintenance/configs/blobstore/access.md, docs/source/maintenance/configs/blobstore/cm.md, docs/source/maintenance/configs/blobstore/scheduler.md, docs/source/maintenance/tool.md, docs/source/user-guide/blobstore.md, docs/source/user-guide/k8s.md
1. migrate from k8s.gcr.io to registry.k8s.io
2. update the title of documents
=> Updata docs

.github/workflows/ci.yml
=> chore(ci): fixup ci checks with gofmt

master/api_service.go
=> fix(master): add datapartition size check when create volume

datanode/disk.go
Release routine which has deleted expired partition successfully
=> [BugFix] release routine which has deleted expired partition successfully

master/cluster.go
prohibit adding data replica automatically during data partition decommission
=> [Enhancement] prohibit adding data replica automatically during data partition decommission

CHANGELOG.md, INSTALL.md, README.md, SECURITY.md, blobstore/README.md, security/email-templates.md
1. Replace the document address
2. Add security policy
=> chore: replace the document address

docs-zh/source/community/article.md, docs/source/community/article.md
=> docs: add articles

docs-zh/source/community/article.md, docs/source/community/article.md
need update the community article docs
=> docs(docs-zh/docs): update the community article docs

docs-zh/source/user-guide/objectnode.md, docs/source/user-guide/objectnode.md
=> fix(docs): fix objectnode user-guide doc

docs-zh/source/community/overview.md, docs/source/community/overview.md
- Add coding style
- Add commit message guidelines
=> docs: update the development guide

CONTRIBUTING.md
- chore: add development guide
=> chore: add development guide
