cubefs/cubefs

metanode/partition_fsmop_inode.go
Update atime in inode get operation, so that temporary file validation
can be extended.
A temporary file is defined as file which is created and removed
immediately by a process, and only the one who is holding the file
descriptor can manipulate the file. However, metanode has difficulties
telling whether a zero-nlink inode is orphan or some user is still holding
the fd. In order to eliminate dirty orphan inode, there is a mechanism to
evict expired zero-nlink inode.
This patch avoids the wrong eviction of read-only temporary files.
=> meta: update atime in inode get operation

sdk/meta/conn.go
It is unacceptable for sendToMetaPatition to return nil resp packet and
no error, which may lead to callers to panic.
=> fix: potential panic if send returns nil resp and no error

client/fs/dir.go
Invalidate inode cache after successful Remove and Rename since Attr
might get stale nlink value.
=> client: delete inode cache in Remove and Rename

docker/docker-compose.yml, docker/ltp/runtest/fs
Disable ftest0* test cases since they will cause docker container to
hang forever, no matter what file system they are running on.
=> docker: update selected ltp test cases

sdk/data/stream/extent_handler.go, sdk/data/wrapper/data_partition.go, sdk/data/wrapper/wrapper.go
use ip address instead of partition id to rule out unavailable data partitions
In sequential write protocol, a write is considered successful only if
all of the partition members reply success. So using ip address instead
of partition id to rule out unavailable data partitions would be more
appropriate, i.e. any member in a data partition should not be in the
exclude list.
=> data sdk: use ip addressto rule out unavailadata partitions

metanode/partition_fsmop_dentry.go
In the following scenario,
-> client issues a create dentry request to metanode;
-> meta node receives the request and applies the raft log;
-> meta node gets killed before sending a response to client;
-> client get a EOF error and retries to the new raft leader;
-> the new meta raft leader send a dentry exist error to client;
This error happens if create dentry request is applied but metanode is
not managed to response to client.
So if the create dentry request has the same parent inode id, name and
inode id, then we can treat it as successful.
=> metanode: fix create dentry exist error

util/master_helper.go
When the amount of partitions are very large, some requests to master
such as obtaining all partitions info may take several seconds to
complete. So increase timeout for now and will optimize master later.
=> util: increase request timeout to master

sdk/data/wrapper/wrapper.go
If there is no writable data partition, updateDataPartition will return
an error which leads to mount fail.
=> data sdk: check amount of writable data partitions when mount

clientv2/fs/dcache.go, clientv2/fs/dir.go, clientv2/fs/inode.go
Add dentry cache to mitigate the LookUpInode request flood if there are
many dentries in a directory.
=> clientv2: add dentry cache

datanode/wrap_operator.go, datanode/wrap_post.go, datanode/wrap_prepare.go, master/data_partition.go, repl/packet.go, sdk/data/stream/extent_handler.go, sdk/data/wrapper/data_partition.go, storage/extent_store.go, util/conn_pool.go, util/ump/ump.go, util/ump/ump_async_log.go
1. rename the isReadOperator to packet.isReadOperator
2. rename the isLeaderPacket to packet.isLeaderPacket
3. rename the isWriteOperation to packet.IsWriteOperation
4. rename the isCreateExtentOperation to packet.IsCreateExtentOperation
5. rename the isMarkDeleteExtentOperation to packet.IsMarkDeleteExtentOperation
6. change the handlePacketToReadTinyDelete func error log
7. fix bug: when read tinyDeleteFile return eof error  …
8. fix bug: when create dataPartition failed,exclude the dp hosts
Signed-off-by: awzhgw guowl18702995996@gmail.com
=> Change packet attr and if dp create failed,check all host if the host is alive

metanode/partition_delete_extents.go
Deleted extent is written to a local file without fsync, and might get
corrupted if the process is killed. Since this file does not affect
responses to users, just skip corrupted files for now.
=> metanode: skip corrupted file which records deleted extent

metanode/partition.go
When deleting a meta partition, stopRaft() is invoked and raftPartition
is set to nil, then invoking DeleteRaft() would cause a panic. Actually
there is no need to set raftPartition to nil in stopRaft().
=> fix: metanode panic when deleting meta partition

clientv2/fs/file.go
File handle is not removed from the handle map during ReleaseFileHandle.
=> fix: clientv2 file handle memory leak

client/fs/super.go, client/fuse.go, clientv2/fs/super.go, clientv2/main.go, proto/mount_options.go
This commit introduces the "writecache" mount option which enables the
FUSE writecache feature to improve async small writes performance.
=> feature: introduce writecache mount option

client/fs/dir.go, client/fs/file.go, client/fs/super.go, client/fuse.go, clientv2/fs/file.go, clientv2/fs/super.go, clientv2/main.go, proto/mount_options.go
The "OpenKeepCache" flag tells the FUSE kernel to keep page cache
when opening an existing file to improve read performance, in exchange
of weaker data consistency among multiple nodes.
=> feature: introduce keepcache mount option

client/fuse.go, clientv2/main.go
Since the client is started as a daemon, it is necessary to redirect
stderr to an output file to capture panic messages.
=> fix: redirect stderr to an output file in daemon

vendor/github.com/jacobsa/fuse/connection.go
Enable FUSE async read feature by default, so that readahead can take
effect to improve sequential read performance.
=> enhancement: enable async read by default

sdk/data/stream/extent_handler.go, sdk/data/wrapper/data_partition.go
When choosing data partition to create extent, client will mark a dp as
exception if it gets an error response so that next time the dp will not
be selected. However, sometimes this failure is temporal due to heavy
network workload, and should not be excluded in the next selection.
=> fix: exclude data partition only when connection refused

util/config/config.go
Right now certain client mount options require bool type inputs,
which have no double quotation marks, i.e. true instead of "true".
However, this is a little bit confusing, and some customers might
have used string type by mistake.
This commit can deal with a string-typed bool config such as "true".
=> enhancement: compatible with string when get bool config

vendor/github.com/jacobsa/fuse/connection.go, vendor/github.com/jacobsa/fuse/internal/buffer/out_message_linux.go
Set out message buffer size to max read size, since we won't be needing
such a big buffer if it is larger than max read size.
=> enhancement: align out message buffer size with max read size

client/fs/dir.go
Directory inode should not be added to the orphan list, since it does
not need to be evicted.
=> fix: exclude dir inode in the orphan list

clientv2/fs/dir.go
This commit evicts the inode cache after file or directory is deleted.
=> fix: evict inode cache after successful deletion

metanode/inode.go, metanode/partition_fsmop_inode.go
If a directory is empty, the nlink of the dir inode is 2. And metanode
may mistakenly delete the inode upon receiving an iunlink request.
For example, if we are renaming a directory, the client will send ilink
and iunlink requests to the dir inode during the Rename process, and
this inode will be wrongly deleted after iunlink.
=> fix: metanode mistakenly delete empty dir inode

vendor/github.com/jacobsa/fuse/mount_linux.go
Since jacobasa fuse package uses a fixed-size memory pool for out
messages, it is important to tell fuse kernel module what the maximum
read size is. Otherwise, a large read will cause a panic.
However, max readahead size can only affect buffered read. The kernel
might still send a large directIO read in spite of the max readahead
size. We need to specify "max_read" option during mount.
=> fix: fuse directIO read size can exceeds buffer size

datanode/const.go, datanode/data_partition_repair.go, datanode/disk.go, datanode/partition.go, datanode/partition_op_by_raft.go, datanode/wrap_operator.go, repl/packet.go, storage/extent.go, storage/extent_store.go
Fix: Datanode Repair time out and  tinyExtentRepair flow execlude Write flow
=> Fix: Datanode Repair time out and if tinyExtentRepair execlude Write

client/fuse.go, clientv2/main.go
This commit will keep the mount point directory in error status when
client is killed, so the successive writes to this directory will not be
written to local disk. And the writer knows client is down as soon as
possible.
=> refactor: keep mount point in error stataus when client is killed

client/fs/file.go, clientv2/fs/dir.go, clientv2/fs/file.go, clientv2/fs/misc.go, sdk/data/stream/extent_client.go
If streamer is auto evicted, then extent client FileSize() will return a
generation of 0 and there is a chance for GetAttr system call to get
stale file size. So in such case, client should not trust inode cache
and send an iget request to metanode explicitly.
=> fix: client gets stale file size if streamer is auto evicted

datanode/server.go, sdk/data/wrapper/wrapper.go
1.if master only create DataPartitionCnt is 10,then cannnot mount 
2.Increase the judgment condition of disk error,add syscall.EROFS
=> Fix: then client cannnot mount (if dp only has 10) and add disk error condition

datanode/const.go, datanode/data_partition_repair.go, datanode/disk.go, datanode/partition.go, datanode/partition_raft.go, datanode/partition_raftfsm.go, datanode/server.go, datanode/wrap_operator.go, raftstore/partition.go, storage/extent.go, storage/extent_store.go, vendor/github.com/tiglabs/raft/server.go
if dataPartition disk error ,master can new dataParittion on new Host, the snapshot recovery fininsh ,then start raftPartition, but not recovery raftLog
=> Fix: dataPartition disk error ,not recvoery raft log on new datanode

sdk/data/stream/stream_reader.go, sdk/data/stream/stream_writer.go
When a user opens a file and writes few bytes to it without fsync
and close, the traverse process will never get triggered because the
written bytes cached in buffer are less than the threshold to be
flushed.
So if there is no writes for a period of time, traverse should
flush the buffer and update metadata.
=> fix: stream traverse process never gets triggered in some situation

client/fs/super.go, client/fuse.go, clientv2/fs/super.go, clientv2/main.go, proto/mount_options.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_reader.go, sdk/data/stream/stream_writer.go, vendor/golang.org/x/time/LICENSE, vendor/golang.org/x/time/PATENTS, vendor/golang.org/x/time/rate/rate.go
Introduce read and write IOPS rate limit feature which can be changed
during runtime with the following http requests through "profPort"
specified in the config file. For example:
curl -s "http://localhost:10095/rate/get"
curl -s "http://localhost:10095/rage/set?write=800&read=800"
curl -s "http://localhost:10095/rage/set?write=-1"
curl -s "http://localhost:10095/rage/set?read=-1"
Note that write and read rate limit can be set together or seperately,
and a negative value indicates that rate limit is unlimited. By default
it is unlimited if not specified.
=> feature: introduce read and write iops rate limit

docker/conf/master1.json, docker/conf/master2.json, docker/conf/master3.json, docker/conf/metanode.json
Change several config parameters when using docker compose so that the
demo cluster can be deployed in a node with limited memory.
=> enhance: adjust demo config parameters

raftstore/raftstore.go, raftstore/resolver.go
The interface NodeManager involves method DeleteNode, so there is no
need to define a DeleteNode function with NodeManager as an input
parameter. Note that the prerequisite is that raftStore.resolver is
guarenteed to be non-nil in NewRaftStore.
=> refactor: remove unnecessary function in raftstore

master/const.go, master/meta_partition_manager.go, master/mocktest/meta_server.go, metanode/manager_op.go, metanode/partition.go, proto/admin_proto.go
When metanode receives loadmetapartition command, it returns applyid and inodeCnt and dentryCnt as Check consistency between  metaPartition replicas
=> refactor: change metaPartition verification method

master/meta_partition_manager.go, master/mocktest/meta_server.go, metanode/partition.go, proto/admin_proto.go
When metanode receives loadmetapartition command, it returns applyid and MaxInode and dentryCnt as Check consistency between metaPartition replicas
=> Fix: use MaxInode and DentryCnt verify metaPartition

cmd/cfg/meta.json, docker/conf/metanode.json, docs/source/quick-start-guide.rst, docs/source/user-guide/metanode.rst, metanode/const.go, metanode/metanode.go
Change config label name of meta node from *masterAddrs* to *masterAddr*
to align with config labels of master and client.
=> change: meta node config label name

client/fs/dir.go, metanode/inode.go
The mtime of parent inode is not updated when create or delete a dentry.
This commit fixes the issue by updating mtime of parent inode in server
side and evict inode cache in client side.
=> fix: broken directory mtime

docker/run_docker.sh, metanode/partition_fsm.go, metanode/partition_item.go
- Fix: the `Next` method in `MetaItemIterator` returns unexpected value after it closed. 
- Fix: the `MetaItemIterator` should be transfer `ApplyID` at first.
- Fix: invalid docker compose `objectnode`.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #327
```release-note
```
=> Fix several raft snapshot issue in meta subsystem

metanode/btree.go, metanode/manager.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_free_list.go, metanode/partition_fsm.go, metanode/partition_fsmop.go, vendor/github.com/tiglabs/raft/raft.go, vendor/github.com/tiglabs/raft/raft_fsm.go
when delete vol by admin,the metanode do deleteMetaPartition ,because the raftPartition cannot exit doRandom goroutine,so the inodeTree and dentryTree cannot auto free memory
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #333 
```release-note
```
=> Fix: metanode leak memory on DeleteMetaPartition operator

docs/source/user-guide/objectnode.rst
- fix: inaccurate document content in ObjectNode user guide
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #351
```release-note
```
=> fix: inaccurate document content in ObjectNode user guide

master/api_service.go
The replica num of data partition can only be 2 and 3
N/A
N/A
N/A
```release-note
```
=> enhancement: the replica num of data partition can only be 2 and 3

metanode/partition_fsmop_dentry.go, proto/fs_proto.go
Meta node checks the dentry file mode when dealing with CreateDentry
request if the target dentry already exists to avoid files replacement
with different types, i.e. rename a regular file to overwrite a
directory. However, file mode contains permission bits as well as file
type bits. And we certainly do not want permissions involved in such
situation. So mask the file mode to compare file type bits only.
Fix inappropriate file mode checks in meta node when dealing with create dentry requests.
N/A
Compare …
=> fix: checks only file type instead of the whole mode

client/fs/super.go, client/fuse.go, clientv2/fs/super.go, clientv2/main.go, objectnode/fs_volume.go, proto/mount_options.go, sdk/data/stream/extent_client.go, sdk/data/wrapper/wrapper.go, sdk/meta/meta.go
Make followerRead a client specific option, so we don't need to set this
option during volume creation. Besides, various clients can have a more
flexible behavioral read pattern in one volume.
Make "followeRead" a client specific option.
N/A
N/A
```release-note
```
=> feature: make followerRead a client specific option

client/fuse.go, clientv2/main.go, cmd/cmd.go
The Dup2 syscall doesn't seem to be supported on all architectures on Linux. The newer Dup3 syscall however seems to have a much wider architecture support. This PR replaces all occurences of Dup2 with Dup3 to help push #393 forward.
Unfortunately the file `vendor/github.com/tiglabs/raft/util/log/log_crash_unix.go` still contains a call to Dup2 which isn't behind a build flag. So either this vendored dependency needs to be patched locally in the vendor folder (bad), or this is fixed upstream or the dependency is replaced by something else.
=> Replaced Dup2 syscall with Dup3

sdk/meta/api.go
When creating a file, the client will create inode first and then send a
create dentry request. If create dentry request fails due to a net
error (e.g. send the request to metanode but timed out when getting
response), there is a tiny chance that the dentry is created
successfully on metanode. Thus we cannot unlink the inode created
previously because we would rather leave the orphan inode than create
an orphan dentry.
The principle is orphan inode rather than orphan dentry. The PR tries to avoid the tiny chance of orphan dentry.
**Special …
=> fix: avoid inode unlink due to net error

sdk/data/stream/extent_client.go, sdk/data/wrapper/wrapper.go
The followerRead option is decided by both client configuration and
volume configuration.
```release-note
```
=> change: take followerRead config from master as well

master/api_service.go, master/data_partition.go
A object with a map field type are locked during serialization
N/A
N/A
N/A
=> fix: a object with a map field type are locked during serialization

master/mocktest/data_server.go, master/mocktest/meta_server.go, objectnode/auth_signature_v4.go
Unbinding regions in signature algorithm v4. 
ObjectNode uses the region in the request to calculate the signature in the signature algorithm v4.
=> Refactor: unbinding regions in signature algorithm v4

client/fuse.go, clientv2/main.go, proto/mount_options.go
The client mount options can be obtained from both config file and
command line arguments. Note that the priority of command line argument is
higher than that of config file, and will overwrite the corresponding
field.
```release-note
```
=> feature: support client command line argument

client/fs/file.go
The Linux *close* syscall invokes the fuse Flush method which is not
implemented before. So the data might still in client's buffer after a
file is closed. Although there is no data persistence requirement for
the *close* syscall, we'd better wait for data to be synced so that
other clients can see the latest data after the file is closed in this
client.
```release-note
```
=> fix: wait for data sync in close syscall

master/server.go, objectnode/fs_volume.go
Fix the issue when there was file that exactly matched the prefix
then the results were not consistent with the expected results.
fixes #421 
NONE.
NONE.
=> Fix: issue of expect result wile list objects

objectnode/fs_volume.go, objectnode/result.go
- Fix issue that server respond incorrect result when using ListObjects with
delimiter parameter.
- Fix compatibility issue on ListObjects interface when using java SDK v1.
- fixes #426
- fixes #427
NONE.
```release-note
Bug Fixes:
- Fix a bug that server respond incorrect result when using ListObjects with
delimiter parameter.
- Fix a compatibility issue on ListObjects interface when using java SDK v1.
```
=> Fix: issue on list objects with delimiter

objectnode/api_handler_object.go, objectnode/fs_volume.go, objectnode/router.go
- Fix empty result when list files by ListObjects interface with delimiter and prefix specified.
- Fix incorrect content length when read file data by GetObject interface with range option.
- fixes #430
- fixes #432 
NONE.
```release-note
Bug Fixes:
- Fix empty result when list files by ListObjects interface with delimiter and prefix specified.
- Fix incorrect content length when read file data by GetObject interface with range option.
```
=> Fix empty result on list objects

client/fs/super.go, client/fuse.go, clientv2/fs/super.go, clientv2/main.go, cmd/master/scripts/manage_token_add.sh, cmd/master/scripts/manage_token_delete.sh, cmd/master/scripts/manage_token_get.sh, cmd/master/scripts/manage_token_update.sh, cmd/master/scripts/manage_vol_create.sh, cmd/master/scripts/manage_vol_update.sh, master/api_service.go, master/api_service_test.go, master/cluster.go, master/cluster_stat.go, master/cluster_test.go, master/const.go, master/http_server.go, master/master_manager.go, master/metadata_fsm.go, master/metadata_fsm_op.go, master/token.go, master/vol.go, master/vol_test.go, proto/admin_proto.go, proto/errors.go, proto/model.go, proto/mount_options.go, sdk/master/api_client.go, sdk/meta/meta.go, sdk/meta/view.go
- Implemented token-based client permissions control.
Use token to distinguish the cabilities of client, readonly or readwrite
- fixes #436 
N/A
```release-note
Features:
- Token-based permissions control for mountable client.
```
=> Enhancement: use tokens to distinguish read and write permissions for clients

client/fs/dir.go
Set the dentry valid duration in the create file process. Otherwise the newly
crated dentry will be using a default value instead of the specified
value in the config file, although the latter dentries generated by
lookup requests remains configurable.
```release-note
```
=> fix: set lookup valid duration for newly created file

sdk/data/stream/extent_client.go
Fixed a logical defect that caused ExtentClient not to update the volume topology.
fixes #443 
NONE.
NONE.
=> Fix: defective code in NewExtentClient method

objectnode/api_handler_object.go, objectnode/fs_volume.go, objectnode/server.go
When the object storage HeadObject and GetObject have no `ETag` information in the extended attributes of the file, the `ETag` header is not included in response header. 
This solves the problem of data verification failure when reading files written through the file system interface using the AWS S3 SDK through the object storage interface to a certain extent.
NONE.
NONE.
NONE.
=> Enhancement: optional not including ETag

objectnode/acl_handler.go, objectnode/api_handler.go, objectnode/api_handler_bucket.go, objectnode/api_handler_multipart.go, objectnode/api_handler_object.go, objectnode/api_middleware.go, objectnode/const.go, objectnode/fs.go, objectnode/fs_volume.go, objectnode/policy.go, objectnode/policy_handler.go, objectnode/result.go, objectnode/result_error.go, objectnode/util.go
Supports folder operations in the same way as Amazon AWS S3.
- Get folder meta info by HeadObject interface.
- Create folder when header specifies Content-Type as
application/directory and Content-Length as 0 on PutObject interface.
- Delete an empty folder by DeleteObject interface.
- The GetObject interface responds normally when the target is an
existing directory.
- Differentiate folders and files on the ListObject interface through the
CommonPrefix property (already supported).
Following object storage interface haven been implemented folder operations:
- HeadObject
- GetObject
- DeleteObject
- DeleteObjects
- ListObjects
- ListObjectsV2
- fixes #429 
NONE. …
=> Enhancement: folder operations in object storage interface

client/fuse.go, clientv2/main.go
Fix: if user set rdonly is true or token is readonly token, then client use readonly mount
=> Fix: if user set rdonly is true or token is readonly token, then client

client/fs/dir.go, client/fs/super.go, client/fuse.go, proto/mount_options.go, sdk/data/wrapper/wrapper.go
- Feature: introduce `disableDcache` client option
- Fix: fails when mounting a volume that is already full
fixes #452 
None.
None.
=> many fixes and features

master/api_service_user.go, proto/errors.go
The user name (ID) is verified when the user is created.
Do not verify user name parameters when viewing user information,
deleting users, modifying authorization, etc. for specific users.
fixes #464 
NONE.
NONE.
=> Fix: user name verification issues

client/fs/super.go, client/fuse.go, proto/mount_options.go, sdk/meta/api.go
This commit introduces the capability of mounting subdirectory in a
volume. Instead of using the default root ino, we use the ino of
specified subdir as root. The subdir can be defined in the client config
file like below:
"subdir": "path/to/subdir",
```release-note
```
=> feature: introduce subdir mount option

CHANGELOG.md
The release notes for v2.0.0 in changelog contain redundant and
useless information. These changes are not adjustments relative
to v1.5.1. Removed this useless information from changelog to
make release notes clearer.
NONE.
NONE.
NONE.
=> Fix: remove useless information from changelog

client/fs/super.go, client/fuse.go, clientv2/fs/super.go, clientv2/main.go, sdk/meta/meta.go, sdk/meta/view.go
Replace process of token validation from meta wrapper to client.
Meta wrapper is now a basic metadata operation component shared by multiple functional modules. 
Permission verification should not be placed in the meta wrapper. 
Otherwise, modules which operates the metadata without permission validation will not work correctly.
fixes #497 
NONE.
```release-note
Bug fix:
- Fixed the problem that the token-enabled volume cannot be operated through the object storage interface.
```
=> Refactor: proccess on token validation

objectnode/auth_signature_v2.go, objectnode/auth_signature_v4.go, objectnode/policy.go, proto/user_proto.go
Added compatibility with 1.5 version of credential information for
signature verification and policy check of s3 interface.
In version 1.5, each volume has its own access key, which is stored
in the view information center of the volume to which it belongs.
In version 2.0, user security and authorization are added. Each user
has their own access key, and users can use this access key to operate
all their own volumes.
Increase the compatibility with the old version authentication method
to reduce the impact of online version 1.5 cluster upgrade to 2.0 on
online services.
Adjusted signature verification process:
**Step 1.** Attempt to obtain the user information that matches the requested access key, and use the secret key information of the user for …
=> Enhancement: compatible with older version S3 credential

sdk/data/stream/stream_reader.go
This commit decreases the size of one file's request channel, since
there is no need for such a large value. Besides, this commit saves the
memory usage when tons of files are written just once.
```release-note
```
=> enhance: decrease request channel size to save memory

objectnode/api_handler.go, objectnode/api_handler_bucket.go, objectnode/api_handler_object.go, objectnode/fs_volume.go, objectnode/result.go, objectnode/result_test.go
Fix the parsing issue of the two preconditions of **If-Match** and
**If-None-Match**.
We found that the request sent through the AWS S3 SDK included
double quotes for the values of these two preconditions.
This part is not specified in the AWS S3 API Reference.
Affected APIs: 
- **HeadObject**
- **GetObject**
NONE
NONE.
NONE.
=> Fix: precondition parsing issue

client/fs/file.go
Sometimes the read request is beyond file length, so the read size is 0.
This does not have to be an error, and we can change the log level from
error to warn.
```release-note
```
=> change: suppress read zero length error

client/fs/dir.go, client/fs/file.go
Evict the inode cache upon receiving Forget request, just in case the
background expire eviction is not as fast as file creation and memory
consumption keeps going up.
```release-note
```
=> fix: evict inode cache when dealing with Forget

objectnode/api_handler_object.go, sdk/master/client.go
We found thousands of http transport goroutines in a process that has
been running for several weeks.
The master client creates a new http client instance every time it sends
an http request, and these instances do not call the method provided by
them to release the restricted connection after use. Try to use
singleton http client to solve this problem.
NONE. 
NONE.
NONE.
=> Fix: too many http transport goroutine in process

client/fuse.go, clientv2/main.go
Let the client daemon inherit all the environment variables
but not just *PATH*.
```release-note
```
=> change: client daemon inherits all the env variables

docker/s3tests/test_put_object.py, objectnode/const.go, objectnode/fs_volume.go
At the same time, get etag information from the two extended attributes `oss:etag` and `oss:tag`.
NONE.
NONE.
NONE.
=> Fix: issue on fetching etag data

docker/conf/nginx.conf, docker/s3tests/test_put_object.py, docker/script/run_test.sh, objectnode/api_middleware.go, objectnode/auth_signature_v4.go, objectnode/const.go, objectnode/server.go
1. **Fix: datestamp validation on signature v4.**
Refer to the description of the calculation process of the signature
algorithm v4 in the API Reference document of AWS S3. Each signature is
valid for 7 days.
> Scope binds the resulting signature to a specific date, an AWS Region, and a service. Thus, your resulting signature will work only in the specific Region and for a specific service. The signature is valid for seven days after the specified date.
Reference:
[Signature Calculations for the Authorization Header: Transferring Payload in a Single Chunk (AWS Signature Version 4) - Amazon Simple Storage Service](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html)
2. **Improve compatibility with nginx.**
The `Expect` …
=> Fix: datestamp validation on signature v4

util/buf/buffer_pool.go
Memory optimization, if there are more than 256 concurrent small files written, bufferPool is no longer used
=> Refactor: BufferPool optimize

client/fuse.go
This commit introduces a debug interface "/debug/freeosmemory" to trigger
garbage collection manually.
```release-note
```
=> feature: introduce debug freeosmemory

client/fs/dir.go, client/fs/file.go, client/fs/icache.go, client/fs/inode.go, proto/fs_proto.go
This commit eliminates the unnecessary memory allocations for Inode
struct by using proto InodeInfo struct directly.
```release-note
```
=> enhance: eliminate redundant Inode memory usage

docker/s3tests/test_object_put.py, docker/script/run_test.sh, metanode/manager.go, metanode/manager_op.go, metanode/manager_proxy.go, metanode/multipart.go, metanode/partition_fsmop_multipart.go, metanode/server.go, objectnode/api_handler_bucket.go, objectnode/api_handler_multipart.go, objectnode/api_handler_object.go, objectnode/api_middleware.go, objectnode/auth_signature_v4.go, objectnode/const.go, objectnode/fs_volume.go, objectnode/result.go, objectnode/result_error.go, objectnode/router.go, objectnode/signer.go, objectnode/util.go, proto/packet.go, sdk/meta/conn.go, util/conn_pool.go
There are several enhancements and fixes included in this pull request.
1. Fix: parallel-safe issue in conn pool and metanode conn serve. (**High-priority**)
2. Fix: nil pointer issue when list parts for non-exist uploadId.
3. Enhancement: validate read size while read from connect.
4. Enhancement: clean up useless data on failure while upload part. (**High-priority**)
5. Enhancement: generate `ETag` if do not exist when listing.
6. Enhancement: include error message when formatting packet to string.
7. Enhancement: improve compatile with old version SDK.
8. Enhancement:  success when retry add exist multipart part.
=> Fix: parallel-safe issue in conn pool and metanode conn serve

metanode/partition_op_inode.go
The inode of the part in multipart upload is not consistent with the serialization and deserialization logic used when submitting and applying through raft when it is released. 
This results in the inability to successfully clean up useless part inode data structures after users have passed the `CompleteMultipartUpload` via S3-compatible interface.
None.
Focus on the process of the `InodeDelete_ll` operation in the **SDK** and **MetaNode**.
None.
=> Fix: multipart part inode release issue

vendor/github.com/tiglabs/raft/util/log/log.go
Redirect os.Stderr to log file in the main fuction, other code should not redirect os.Stderr to log file again
N/A
N/A
N/A
=> fix :  Redirect error log to file

metanode/free_list.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_free_list.go, proto/admin_proto.go
1. When metanode is in freeInode, use tcp protocol to notify follower, there is a serious bug, if follower is down and restarted at this time, a part of freeInodes is lost, so here is changed to use raft protocol
2. optimize metanode delete inode speed 
```release-note
```
=> Fix: metanode freeInode bug and optimize delete speed

objectnode/api_handler_object.go, objectnode/const.go, objectnode/fs.go, objectnode/fs_volume.go, objectnode/result_error.go, objectnode/util.go
Add 'Expires' and 'Cache-Control' when putObject/copyObject/getObject/headObject.
```release-note
```
=> enhancement: add 'Expires' and 'Cache-Control' when putObject

metanode/partition_delete_extents.go, util/synclist/synclist.go, util/synclist/synclist_test.go
=> Fix: use synclist to replace list for partition_delete_extents to avoid list concurrent access panic

util/log/log.go, util/log/log_test.go, util/log/rotate.go
In some scenarios, the log file is not cleared in time and the disk is full,This pr made the following optimizations.
1. Reduce log file size and headroom size, ensure log files are carried forward and cleared in time
2. The log file 7 days ago will be deleted
3. Intelligently adjust the rolling size during initialization
N/A
N/A
N/A
=> fix :  log doesn't clean

proto/packet.go, sdk/data/stream/packet.go, util/buf/buffer_pool.go
Use sync Pool and rate limiter to limit the memory usage.
```release-note
```
=> enhance: limit the tiny buffer pool memory consumption

metanode/const.go, metanode/dentry.go, metanode/extend.go, metanode/inode.go, metanode/partition.go, metanode/partition_fsm.go, metanode/partition_store.go, metanode/partition_store_ticket.go, metanode/sorted_extents.go, proto/extent_key.go
1. Reduce the number of heap memory applications by reusing buffers when
persisting metadata.
2. Before persisting, compare the current ApplyID with the last successfully
persisted ApplyID, and then trigger the persistence when the gap exceeds 1000.
=> Enhancement: improve metadata persist

datanode/partition_raftfsm.go, metanode/partition_fsm.go
Fix: dataPartition or metaPartition HandleLeaderChange event, async call tryToLeader
If the server port is not opened, dataPartition raft will call tryToLeader synchronously, which may block the entire raft group。。 so change to async call TryToLeader
=> Fix: dataPartition HandleLeaderChange event, async call tryToLeader

metanode/packet.go, metanode/partition_delete_extents.go, metanode/partition_free_list.go
In the scenario of overWrite, metanode adopts a sequential deletion method for old extents, so optimize here and use batch to delete extents in this scenario.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)`
=> Refactor: metaNode bachDelete extent on Overwrite

metanode/partition_fsm.go
Fix the problem that metapartion does not switch extend and multipart to
the latest valid data after applying raft snapshot.
=> Fix: isssue in metapartition apply raft snapshot

master/cluster.go
Fix unexpected failure when creating volume.
>Since the creation of DataPartition has a retry mechanism, it will automatically try again after the creation fails, so there is no need for the user to return an error due to the failure of DataPartition during the creation of the Volume.
None.
None.
=> Fix: unexpected failure when creating volume

cli/cli.go, cli/cmd/datanode.go, sdk/master/api_admin.go, sdk/master/api_node.go, sdk/master/client.go
Some actions such as decommission datanode may spend more than 30 seconds, remove the limit on these actions.
=> Fix: Remove timeout limits in master client sdk

docker/s3tests/base.py, docker/s3tests/test_cors.py, objectnode/acl.go, objectnode/acl_handler.go, objectnode/api_middleware.go, objectnode/cors_handler.go, objectnode/fs_manager.go, objectnode/fs_volume.go, objectnode/fs_volume_meta.go, objectnode/policy.go, objectnode/policy_handler.go, objectnode/server.go
1. Whether to cache volume oss meta is determined by the configuration parameter 'strict'.
2. Add cors test cases.
None.
None.
None.
=> refactor: whether to cache volume oss meta is determined by the configuration parameter 'strict'

objectnode/api_handler_bucket.go, objectnode/const.go
1. ListBuckets result is empty when buckets has existed via using java sdk.
2. HeadBucket result is empty, expect bucket region.
```release-note
```
=> Fix: ListBuckets and headBucket result is empty using java sdk

objectnode/auth_signature_v4.go
Fix: Put object return 403 if key contain double slash.
```release-note
```
=> Fix: putObject the key with double slash return 403

objectnode/api_handler_bucket.go, objectnode/api_handler_object.go, objectnode/const.go, objectnode/fs_store_xattr.go, objectnode/fs_volume.go, objectnode/result.go, objectnode/result_error.go
Fix:
1. No limit to the number of object tagging and bucket tagging.
2. Return an empty tagging when bucket has no tagging.
3. getObject Api has no tagging numbers in header when object has one or more tags.
4. setObjectTagging return success when object not exist. 
```release-note
```
=> Fix: some bugs about object tagging and bucket tagging

sdk/data/stream/stream_writer.go
Break the loop if PrepareWriteRequests is invoked again, or it will
result in unnecessary loops and invocations.
```release-note
```
=> fix: lack of break

fsck/cmd/check.go, fsck/cmd/clean.go, fsck/cmd/common.go, fsck/cmd/root.go, fsck/main.go, fsck/usage.md
This tool can scan the specified volume, perform filesystem
consistency checks and dump obsolete inodes and dentries. It can also
deal with dumped inodes and dentry, like evict inodes whose nlink equals
zero.
```release-note
```
=> fsck: introduce fsck

build/build.sh, cli/build.sh, cli/cmd/root.go, client/build.sh, client/fuse.go, cmd/build.sh, cmd/cmd.go, proto/version.go
When using the build script to compile the program, it automatically uses the latest git tag as the program version number information.
Using the `-v` argument will output version information like this:
```
ChubaoFS CLI
Version : v2.1.0-rc.1
Branch  : mervinkid/unified_version_info
Commit  : c458dd6409d22aca4c968c5028d3423dbf95b0da
Build   : go1.13.1 darwin amd64 2020-07-16 19:39
```
None.
None.
None.
=> Enhancement: unified version information

objectnode/fs.go, objectnode/fs_volume.go
Fix: 
1. listObjects and listObjectsV2 list result is incorrect.
2. listObjects and listObjectsV2 pagination information is incorrect.
3. Add directory to result (Contents or CommonPrefixes in response) if the directory is eligible.
```release-note
```
=> Fix: listObjects and listObjectsV2 list result is not expected

metanode/btree_rocks.go, metanode/partition_fsmop_dentry.go
=> Update: recover prefix valid for rockstree range iter

build/build.sh
Fix the issue of obtaining the latest tag of the current branch during build when using main build script under the `build` directory.
None.
None.
None.
=> Fix: main build script issue

build/build.sh
./cfs-cli -v                                                                                                                           
ChubaoFS CLI
Version : 
Branch  : 
Commit  : 
Build   : go1.13.11 linux amd64 
I uncommented the line of go build,and commented the line of cli/build.sh.
./cfs-cli -v
ChubaoFS CLI
Version : v2.1.0
Branch  : master
Commit  : 85b36b54724e866d62c9cf3be0f28a78a93eb704
Build   : go1.13.11 linux amd64 2020-07-30 18:45
```release-note
```
=> Fix blank version when cfs-cli -v

objectnode/api_handler_multipart.go, objectnode/api_middleware.go, sdk/master/client.go
1. Modify to touch off ump warning when status code more then 500.
2.Modify access key not exist log level from error to warn.
3.Catch unexpected EOF error, not return internal error yet.
```release-note
```
=> Enhancement: handle ump warnning and "access not exist" error log info

master/admin_task_manager.go, master/api_service.go, master/cluster.go, master/cluster_task.go, master/data_partition.go, master/data_partition_check.go, master/disk_manager.go, master/http_server.go, master/meta_partition_manager.go, master/metadata_fsm_op.go, master/mocktest/data_server.go, master/vol.go, metanode/manager_op.go, metanode/partition_delete_extents.go, metanode/partition_free_list.go, metanode/partition_fsmop.go, metanode/partition_item.go, proto/admin_proto.go, proto/extent_key.go, proto/packet.go, util/conn_pool.go, vendor/github.com/tiglabs/raft/raft.go, vendor/github.com/tiglabs/raft/raft_fsm.go, vendor/github.com/tiglabs/raft/raft_fsm_candidate.go
1. Add log on raftFSM ignored mesg 
2. Modify warn message when the difference used usage between all…
3. Check whether the used space between the replicas is consistent when performing the load partition operation
4. Persist `isRecover` status to rocksDB
5. Connection pool with connect timeout
6. Provide update datanode API and check invalid nodes API
7. Update invalid extentKey unmarsharl error
8. Add extentKey header into `EXTENT_DEL` file with checksum verification process.
9. Modify metanode log 
10. MetaMode uses `handleMarkDeleteExtent` command to delete extent if it is a truncate extent.
None.
None.
```release-note
```
=> Some Optimize and bug fix

datanode/disk.go, datanode/partition.go
Refactor: datanode syncTinyDeleteRecordFromLeader limit to 5 on every disk
Refactor: datanode syncTinyDeleteRecordFromLeader limit to 5 on every
=> Refactor: datanode syncTinyDeleteRecordFromLeader limit to 5 on every

master/metadata_fsm_op.go
1.Fix: if metanode or datanode id has multi,then use min node id to overwrite 
2.Fix: if load mp,dp ,the peerid is not in cluster topo,then use right peer id
```release-note
```
=> Fix: if metanode or datanode id has multi,then use min node id to overwrite 

sdk/meta/meta.go
During mount phase, the main routine will not get an error message when
max retry limit is reached. So return an explicit error message after
max retry.
```release-note
```
=> fix: return explicit error after max retry

client/fs/super.go
A non-owner user can be authorized to mount with rw/ro permission.
However, the auth key is generated according to the user name which
leads to mount failure when getting volume info from master.
To reproduce:
1. create a volume named V with owner A.
2. authorize user B the rw permission to V.
3. mount V using user B with access and secret key.
The mount would fail.
This commit will not check owner auth key when using access key to
mount.
```release-note
```
=> fix: mount failure for authorized user

cli/cmd/user.go, client/fuse.go, objectnode/api_handler_object.go, objectnode/policy.go, proto/perm_action.go, proto/user_proto.go
Originally the permission control for users are in volume level. This
commit introduces subdir level permission control.
```release-note
```
=> feature: introduce subdir permissions

metanode/partition_fsmop_inode.go
Fix: when metanode restart,the temp file not insert to freelist
=> Fix: when metanode restart,the temp file not insert to freelist

metanode/partition_free_list.go, metanode/partition_fsmop_inode.go
When the metanode fails to send the delete command to the datanode, the inodes that failed should be put back into the freelist list.
=> Fix: metanode may not  Immediately free space 

datanode/partition.go, datanode/wrap_operator.go, storage/extent_store.go
1. When using elatiseach to pressure test chubaofs, when writing and deleting continuously, a large number of extents will be generated under each dp, and these extents will be deleted continuously, the length of extentcache is only 40, when each extent is deleted , LoadExtentWithHeader will be loaded from the disk. When reading the header, it will read the 4096-byte header from the extentcrc file, thus causing some random reads. This pr is to optimize this phenomenon.
2. When there are many extents ，dataPartition computeUseSize  A lot of random IO was wasted, so The memory method is used to calculate the space used by dataPartition。
3. tinyExtentRepair donnot use limit by autoRepairLimit parameter
=> Enhance: datanode optmize performance  When there are many extents

datanode/partition_raftfsm.go
Fix: dp snapshot function use current applyid   prevent raft painc
=> Fix: dp snapshot function use current applyid   prevent raft painc

client/fs/file.go, client/fs/super.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_writer.go
Right now the batch inode get mechanism does not work since in when
getting attr, the inode cache is evicted every time the underlying extent
streamer does not exist. To eliminate the eviction in getAttr, we have
to trigger an active eviction when the underlying streamer quits
silently.
```release-note
```
=> fix: batch inode get mechanism is out of service

objectnode/auth_signature_v2.go, objectnode/auth_signature_v4.go
- Fix no such bucket issue when using S3 CreateBucket API.
fixes #869 
Focus on the v2 and v4 signature verification process.
```release-note
Bugfix:
- Fix no such bucket issue when using S3 CreateBucket API.
```
=> Fix: no such bucket when create bucket using S3 API

objectnode/fs_volume.go
-  Fix the issue that recursive making directory concurrent with sample multi-layer path prefix.
fixes #902 
None.
```release-note
Bugfix
- Fix the issue that recursive making directory concurrent with sample multi-layer path prefix.
```
=>  Fix the issue that recursive making directory concurrent with sample multi-layer path prefix.

objectnode/fs_volume.go
Fix the issue that recursive making directory concurrent with sample multi-layer path prefix.
fixes #902
None.
=> Fix bug when recursive making directory

client/fuse.go, proto/mount_options.go, vendor/bazil.org/fuse/fuse_kernel.go, vendor/bazil.org/fuse/options.go
- Fix `CFS-01-004 WP1: Linux file permissions ineffective for ACL (High)`
None.
None.
```release-note
Security
- Fix CFS-01-004 WP1: Linux file permissions ineffective for ACL (High)
```
=> Add configuration to enable POSIX ACL for client

raftstore/log_test.go, vendor/github.com/tiglabs/raft/util/log/log.go
Limit name of deleted raft logs.
None.
None.
None.
=> fix: limit name of deleted raft logs

master/topology.go, master/topology_test.go
Signed-off-by: yangqingyuan8 <yangqingyuan8@jd.com>
to solve the warning info below:
dataNodeOfflineErr clusterID[spark] partitionID:5985 on Node:XXXX Then Fix It on newHost: Err:action[getAvailHosts] no enough writable hosts,replicaNum:1 MatchNodeCount:0 ,
```release-note
```
=> Fix:exclude hosts when alloc node set for data node

storage/extent_store.go
Fix: datapartition on delete normalextent action,forget remove it from storage.extentInfoMap, so some dp can change to readonly status,now fix
this bug
=> Fix: datapartition on delete normalextent action,forget remove it from

datanode/server_handler.go, raftstore/partition.go
Expose raft peers info in get partition info API of data node.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
None.
None.
None.
=> Expose raft peers info in data node api.

datanode/disk.go, metanode/manager.go
Refactor validation process of expired partition on DataNode and MetaNode launch process.
When node start and launch in prograss, it will fetch partition information from Master and check if every partiton is valid.
If a partition found in local but do not exists in node view fetched from Master, then remove (rename and backup) from local.
None.
None.
None.
=> Refactor: expired partition validation

objectnode/api_handler_object.go, objectnode/const.go, objectnode/etag.go, objectnode/fs_store_user.go, objectnode/fs_volume.go, objectnode/util.go
Parse parameter `encoding-type` from request. It this parameter specified and match with constant string `url`, then encode content keys by using url encoding function.
fixes #954 
None.
```release-note
Bugfix
Fix object key encoding issue of S3 ListObjects API.
```
=> Fix: key encoding issue of S3 ListObjects API.

util/log/log.go, util/log/log_test.go
1. Clean old logs 7 days ago.
2. Rotate critical logs.
None.
None.
```release-note
```
=> fix: clean old logs 7 days ago; rotate critical logs [version: release-20200412]

util/log/log.go, util/log/rotate.go
Replace 'os.Open' with 'ioutil.ReadDir' when check to clean logs.
None.
None.
```release-note
```
=> fix: replace 'os.Open' with 'ioutil.ReadDir'

datanode/server.go
Judge null pointer when get datanode info from master.
**Which issue this PR fixes** *(optional, in `fixes #<971>(, fixes #<971>, ...)` format, will close that issue when PR gets merged)*: 
fixes #971
```release-note
```
=> Judge null pointer when get datanode info from master

metanode/partition_op_inode.go
Fix: deadlock issue when convert `metanode.Inode` to `proto.InodeInfo`.
https://github.com/chubaofs/chubaofs/blob/d259d3fcf366dda9a4e3fd75017631947336dde2/metanode/partition_op_inode.go#L25-L46
If the specified inode object have been marked as deleted, then the `replyInfo` method returns without unlock the readwrite mutex.
None.
None.
```release-note
Bugfix:
- Fix deadlock issue when get an deleted inode info.
```
=> Fix: deadlock issue when convert Inode to InodeInfo

raftstore/log_test.go, util/log/log.go, util/log/rotate.go, vendor/github.com/tiglabs/raft/util/log/log.go
1. Clean up the raft log when the remaining space is insufficient or 7 days ago.
2. Limit the size of raft log and rotate.
None.
None.
```release-note
```
=> [release-0720]enhancement: clean up the raft log; limit size of raft logs and rotate

cmd/cmd.go, datanode/partition.go, datanode/partition_raft.go, datanode/server.go, datanode/space_manager.go
Improve the DataNode shutdown process, and make the raft apply ID information of all data partitions persistent after receiving the stop signal.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
None.
None.
None.
=> Enhancement: shutdown process of DataNode

datanode/disk.go
I found it's better to use (total space - free space) to get used space, because I think that may be much better know how much space used by chubaofs sytem. And by this way, the used sapce will be same both ext4 and xfs system
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1029
=> use statfs's bfree to caclute used size

storage/persistence_crc.go
It has been clear that the following code has a logical problem. 
https://github.com/chubaofs/chubaofs/blob/5fa1f6995d8c0b5268ed61361ac9b95b01c3a90f/storage/persistence_crc.go#L68-L76
The logic here should be read, not write.
This logical problem will not affect system functions and data integrity.
fixes #1046
None.
None.
=> Fix: logic issue when read persisted prealloc space extent ID

proto/perm_action.go
Multiple subdirs are separated by colons. For example:
perm:builtin:/a/b:/a:Writable
```release-note
```
=> feature: support multiple subdir permissions

docs/source/admin-api/master/user.rst
“There is an error in the transfer volume”
Error in the transfer volume command in the user command management section.
When unmarshal, "true" will be thought as astring instead of a bool
```release-note
```
=> Modify user.rst

vendor/github.com/tiglabs/raft/raft_fsm_leader.go
before, replica's status is not initate when replica change to raft leader, so when raft replica change to leader, set  it's status ``active=true``
**Which issue this PR fixes: fixes #1054
```release-note
```
=> fix data node raftstatus's active value #1054

master/user.go
In the process of updating users, once the wrong sk value to be updated is detected, the updated ak value should be rolled back
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1061 
```release-note
```
=> fix: update user secret key failed without rolling back access key

.travis.yml, docker/Dockerfile, docker/build_docker.sh, docker/docker-compose.yml
This commit changes the ci process from docker pull to docker build
since docker hub limits the image pulling rate. Also change the base
image from golang:1.12 to golang:1.15
```release-note
```
=> change: docker pull to docker build

proto/perm_action.go
In the old subdir mount authentication, `perm:builtin:[dir]:(Readonly|Writable)` only allows a single directory `[dir]` to be mounted.
This PR will make `perm:builtin:[dir]:(Readonly|Writable)` allow `[dir]` and all dir under it (`[dir]/a`, `[dir]/b`...)to be mounted
=> support subdir match

raftstore/monitor.go, raftstore/raftstore.go, vendor/github.com/tiglabs/raft/config.go, vendor/github.com/tiglabs/raft/monitor.go, vendor/github.com/tiglabs/raft/raft.go, vendor/github.com/tiglabs/raft/raft_fsm.go, vendor/github.com/tiglabs/raft/raft_fsm_candidate.go, vendor/github.com/tiglabs/raft/raft_fsm_leader.go, vendor/github.com/tiglabs/raft/raft_replica.go
`raft.monitor` and `raft.run` will compete for variables such as `raft.raftFsm.replicas`, `raft.raftFsm.leader`, and concurrent access to the non-reentrant function `raft.raftFsm.peers()`
`raft.monitor` does not belong to the native raft library, it is an additional function, mainly used to monitor:
1. Whether a peer in the raft group is disconnected for a long time.
2. Whether the raft group has been unable to elect the leader for a long time.
To fix this problem, we introduce the interface `Monitor`. The functions of `Monitor` are:
1. `Monitor.MonitorZombie` monitors peers that cannot be dialed for a long time  (3min).
2. `Monitor.MonitorElection` monitors the long-term failure of election (30s) .
The above two correspond to the two functions of …
=> Bugfix/fix raft monitor panic error#1069

sdk/data/wrapper/wrapper.go
`to avoid changing hosts of dp by use a copy of hosts`
**Which issue this PR fixes** : fixes #1105
```release-note
```
=> fix: func sortHostsByDistance change dp's hosts

docker/Dockerfile, docker/build_docker.sh
This commit contains the following changes:
1. Updated the version of the ltp program and use case on the basis to
20210121.
2. On top of the foundation, the dependencies required for the s3
compatibility test are added, so that the efficiency of each CI
execution test can be improved.
=> Enhancement: update dockerfile

sdk/data/stream/extent_handler.go
The ek stored in the extent cache may be inaccurate with dpid 0,
especially when eh failed and is doing a recovery.
Reported-by: bboyCH4 <hechi1014@126.com>
Signed-off-by: bboyCH4 <hechi1014@126.com>
```release-note
```
=> fix: update extent cache no matter whether eh is dirty or not

util/exporter/consul_register.go
when consulMeta not set, there has warn log "meta no use"
```release-note
```
=> metanode: fix meta not use warn when consulMeta not set

sdk/data/stream/extent_cache.go, sdk/meta/api.go
There might be stale discard extents records left in the stream writer.
When a file is truncated less than the discard extents, those discard
extents records are not removed from the stream writer's extent cache.
So next time, when you write to this file range, the client will get a
"conflict extents error", because the client is expecting to overwrite
and discard these extent keys, but actually they are no such extent keys
in meta node since they were already truncated.
```release-note …
```
=> fix: broken test case ftest01

client/fs/super.go, master/api_service.go, proto/model.go, sdk/meta/api.go, sdk/meta/meta.go, sdk/meta/view.go
This patch adds f_files and f_ffree fields for statfs. Since free
file nodes is not limited, so the default max inode ID is used to
calculate free file nodes.
```release-note
```
=> fix: return file nodes for statfs

Makefile, build/build.sh, fsck/cmd/root.go
1. add `-v, --version` for fsck.
To avoid conflicting with host fsck, the target is named to **cfs-fsck**.
`-v` conflicts with `--vol`. Because `-v` is used for other cfs tools to show version, the short option of `--vol` is changed to `-V`. 
2. Update Makefile & build/build.sh to build fsck.
3. Update Makefile to track modification of objectnode code.
=> Trivial fixes

sdk/data/stream/stream_conn.go
If followerRead is enabled and there is no preferred currAddr, it can be
picked arbitrarily from one of the dp hosts.
This commit avoids IO error during the period when volume is just created
due to the empty currAddr.
```release-note
```
=> fix: currAddr of stream conn is empty

vendor/github.com/tiglabs/raft/proto/codec.go, vendor/github.com/tiglabs/raft/transport_heartbeat.go
add check for msg size when decode raft msg
**Which issue this PR fixes** : fixes #1168
```release-note
```
=> check size when read data from heartbeat port

metanode/partition_fsmop_inode.go, metanode/sorted_extents.go
This commit makes AppendExtentKeyWithCheck request idempotent to avoid
conflict extents error when client retries.
For example,
-> client writes [0, 100) to extent 25,
-> send AppendExtentKeyWithCheck to metanode (offset: 0, size: 100, extentID:
25, discard extent: nil),
-> client overwrites [0, 100) to extent 30,
-> send AppendExtentKeyWithCheck to metanode (offset: 0, size:
100, extentID: 30, discard extent: 25),
Think about the following scenario: metanode managed to deal with the request,
but failed to respond to the client, and client retries with the same request.
Since AppendExtentKeyWithCheck is not idempotent, this will lead to
conflict extents error.
-> client send AppendExtentKeyWithCheck to metanode (offset: 0,
size: 100, extentID: 30, discard extent: 25),
-> when metanode is …
=> fix: makes AppendExtentKeyWithCheck request idempotent

vendor/github.com/tiglabs/raft/raft_snapshot.go
This commit removes the redundant memcopy when reading raft snapshot.
The redundant memcopy makes reading snapshot very slow which leads to
snapshot send failure.
Reviewd-by: Shuoran Liu <shuoranliu@gmail.com>
```release-note
```
=> fix: remove redundant memcopy when reading raft snapshot

raftstore/partition.go
when meta start, maybe raft is still not start, and startFreeList when check raftLeader with `LeaderTerm()`, so, need to add nil pointer check in `leaderTerm()` function
=> check nil when get leader term info

master/data_partition_map.go
when dp's count is bigger, copy dpResponseCache frequently may produce too much garbage data, casue gc busy
=> enhance: return response cache directly, not copy again

master/api_service.go, master/cluster.go, master/cluster_task.go, master/const.go, sdk/data/wrapper/wrapper.go
1. update.interval for client fetch data partition need enlarged because client count
2.enhance. meta replica force delete take effect and ignore status of missing and recovery
3.fix. meta node migration be recorded in badmetapartitions concurrently without lock which lead to mp id miss
4.add feature.del replica with force if decommission hang
=> add feature.del replica with force if decommission hang 

metanode/metanode.go
This commit starts the TCP listen port before starting raft. Because
otherwise there is a gap between raft started and TCP port listened. If
current node is selected as raft leader but TCP port listening is not
up, the whole partition will be unavailable due to "connnection reset
error".
```release-note
```
=> fix: start tcp listen before starting raft

master/admin_task_manager.go, master/api_service.go, master/cluster.go, master/cluster_task.go, metanode/manager.go, metanode/manager_op.go, proto/admin_task.go, vendor/github.com/tiglabs/raft/transport_replicate.go
support decommission disk, datanode or metanode target limit cnt once, so it can be used to control decommission speed to avoid cluster too busy
eg:
```
decomMetaNode: curl 'masterIp:17010/metaNode/decommission?addr=meta:17210&count=2'
decomDataNode: curl 'masterIp:17010/dataNode/decommission?addr=dataIp:17310&count=2'
decomDisk: curl 'masterIp:17010/disk/decommission?addr=dataIp:17310&disk=/cfs/disk&count=2'
```
=> enhance: support disk, datanode, metanode decommission limit cnt partition

sdk/data/stream/stream_conn.go
This commit uses dp.Hosts if NearHosts is empty so all the hosts get a
chance to be retried to avoid client IO error.
```release-note
```
=> fix: use dp.Hosts if NearHosts is empty

objectnode/api_handler_object.go
Some clients (e.g. docker registry) send a get to fetch the whole file
by specifying `bytes=0-` as the range. In this case, ChubaoFS will set
the range to 0-0 and the `Content-Length` to 1 (upper - lower + 1). It
will then error out when writing the object, since it will write more
than the specified `Content-Length`.
As a simple fix, we can treat a rangeUpper of 0 the same as max, which
should result in correct behavior.
**Special notes for your reviewer**: I'm not able to build chubaofs locally (errors while building rocksdb), so I haven't been able to test this change.
```release-note
objectnode: handle `Range: bytes=0-` correctly
```
=> fix: handle `bytes=0-` correctly in objectnode

sdk/data/stream/extent_cache.go, sdk/data/stream/extent_handler.go, sdk/data/stream/stream_writer.go, sdk/meta/conn.go, storage/extent.go
This commit mitigates the pain of extents fragmentation by reusing
existing extents as much as possible.
```release-note
```
=> enhance: mitigate the pain of extents fragmentation

datanode/data_partition_repair.go, storage/extent.go
This commit reduces datanode cpu usage significantly by eliminating
unnecessary file seeks operations since they consume a lot of cpu time.
```release-note
```
=> enhance: reduce datanode cpu usage

datanode/server.go, datanode/space_manager.go
Avoide failure of creation of datapartition when disk's left size less than 5G
=> fix: remove 5 GB left limit for disk to create datapartition

client/fuse.go
daemonize uses `SignalOutcome' to pass child's error to parent.
=> fuse: Tell parent error message if error occurs in child

client/fuse.go
When multi client mount on one machine, one client log will be
overwritten by another. To avoid this, we should separate the log path
of each client. To implement this, i attach volume name to the logDir in
the config file.
Besides, previous default logDir is root. I set the default logDir to
/var/log
Signed-off-by: wanglei469 <wanglei469@ke.com>
```release-note
```
=> change: append volume to client log path

sdk/data/stream/extent_handler.go, sdk/data/stream/stream_writer.go
traverse() marks streamer's ExtentHandler as closed periodically to
write cached data back. However, if the current handler is closed,
new write request has to create a new one and that prevents writing
data to the previous extent continously if possible.
Instead of marking ExtentHandler closed, this patch flush handler
directly.
=> client: Flush streamer's handler instead of marking it closed

metanode/partition_free_list.go
Slice `allDeleteExtents' is never used. Let's remove it.
=> metanode: Cleanup dead code

build/build.sh
When compiling cubefs using a newer version gcc (version 10.2.1), it
complains that:
```
./db/version_edit.h:156:33: error: implicitly-declared ‘constexpr rocksdb::FileDescriptor::FileDescriptor(const rocksdb::FileDescriptor&)’ is deprecated [-Werror=deprecated-copy]
76 | struct FileMetaData {
|        ^~~~~~~~~~~~
./memtable/inlineskiplist.h:282:11: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct std::atomic<rocksdb::InlineSkipList<const rocksdb::MemTableRep::KeyComparator&>::Node*>’ with no trivial copy-assignment [-Werror=class-memaccess]
282 |     memcpy(&next_[0], &height, sizeof(int));
|     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./utilities/persistent_cache/persistent_cache_util.h:51:23: error: moving a local object in a return statement …
```
=> build: Workaround for rocksdb compiling errors

vendor/github.com/tiglabs/raft/transport_heartbeat.go
Fix the following error message:
```
2022-02-18 12:35:22,026 transport_heartbeat.go:100: [ERROR] [heartbeatTransport] recive message from conn error
%!(EXTRA string=read tcp 192.168.0.31:17330->192.168.0.34:39830: read: connection reset by peer)
^^^^^^^^
```
=> fix: Fix logger.Error format

datanode/disk.go, datanode/partition.go, datanode/server.go, datanode/server_handler.go, datanode/space_manager.go, datanode/wrap_operator.go, master/data_partition_check.go
preReserveSpace is used to avoid writeOp failed when disk is rdonly:
eg: client try to write data on a rw dp, when request arrive datanode server and
find disk is already rdonly, which will cause writeOp failed and have to retry other dp,
once many disks are going to be rdonly(cluster used factor is too bigger), which will casue
a lot retry in clients, make writeOp become slow.
diskRdonlySpace is bigger than reservedSpace,
if reservedSpace < freeSpace < diskRdonlySpace, writeOp is ok, but disk or dp will be rdonly,
if freeSpace < reservedSpace, writeOp will also failed.
=> enhance: add cfg diskRdonlySpace for datanode

master/cluster.go
Fixes: 740743119d865 ("master: Remove condition check that is always false")
=> metanode: Fix variable scope in migrateMetaNode

metanode/manager_op.go
If current metanode is not the leader, `serveProxy` is called and
conntion is responsed in serveProxy. So caller should not response
again. Otherwise, we may get the following error:
```
2022/02/23 07:03:25.491884 [ERROR] conn.go:139: send: the response packet mismatch with request: conn(A.B.C.D:49774 to E.F.G.H:17210) req(ReqID(529314752)Op(OpMetaLookup)PartitionID(152)ResultCode(Unknown ResultCode(0))) resp(ReqID(529314745)Op(OpAddMultipartPart)PartitionID(150)ResultCode(Ok))
```
Reported-by: wanglei469 <wanglei469@ke.com>
=> metanode: Fix extra response to connection

docker/s3tests/env.py, docker/script/run_test.sh
We found a bug when multi bucket were operated.
The s3-tests case now only support single bucket tests.
So I add a bucket named 's3test'.
Signed-off-by: wanglei469 <wanglei469@ke.com>
```release-note
```
=> test: change s3-tests from single bucket to double buckets

util/synclist/synclist_test.go
If the `wg.Add(1)` is called inside a goroutine, there is no guarantee
that `wg.Wait` is called before all `wg.Add(1)`. So `wg.Add(1)` should
be called before goroutine starts. Otherwise, the following error
occurs:
```
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
panic: sync: WaitGroup is reused before previous Wait has returned
goroutine 18 [running]:
testing.tRunner.func1.2(0x51cac0, 0x56ebb0)
/usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc00009e300)
/usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0x51cac0, 0x56ebb0)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
sync.(*WaitGroup).Wait(0xc000098080)
/usr/local/go/src/sync/waitgroup.go:132 +0xae
github.com/cubefs/cubefs/util/synclist.TestSyncPushBach(0xc00009e300) …
```
=> unin test: Add WaitGroup before goroutine starts

datanode/partition.go, datanode/partition_raft.go, datanode/space_manager.go, datanode/wrap_operator.go, depends/tiglabs/raft/server.go, master/api_args_parse.go, master/api_service.go, master/cluster.go, master/const.go, master/data_partition.go, master/data_partition_check.go, master/disk_manager.go, master/http_server.go, master/meta_partition.go, master/metadata_fsm_op.go, master/operate_util.go, master/vol.go, proto/admin_proto.go, proto/model.go, repl/packet.go
notice：two replicas can support modify and write(use other dp and it's extent) normally
features:
1. support 3replics volume already created to set 2replicas and take effect while create new dp but not including old dp
2. improve meta partition status check
3. add interface to set dp readonly
4. enable force del dataReplica without strict check
5. enable force raft del while 2replicas volume have one replica crash then no leader happend
abnormal scenario in two replicas names A and B
1) migration dst names C
we realize the process as add replica C first,delete src A later
abnormal resolve ways: if B crash, raft will not eabled,delete B first,wait migration finished,delete A,add another one
2) B crash
no leader, and B cann't be deleted according to raft rules first commit then apply …
=> update. support two replicas(data) volume

ADOPTERS.md, master/cluster.go
it's a tool used by abnormal senario that nodeid not consistent between datanode or metanode meta and master, we need use this interface update the master
the process of "/dataNode/update" and "/metaNode/update" should drop the old one and set the new one. or else would exist two different version of node id info
it's not a common interface be used,should get advice from the commutnity if need.
=> update: 1) update metanode or datanode id need drop old one before 2)update adopters

docker/Dockerfile-dev
fix the base images name in DockerFile-dev from "ghcr.io/chubaofs/cbfs-base:latest" to "ghcr.io/cubefs/cbfs-base:1.0-golang-1.16.12"
as it was updated in [https://github.com/cubefs/cubefs/pull/1520](https://github.com/cubefs/cubefs/pull/1520)
=> FIX: fix the base images name in Dockerfile-dev

metanode/manager.go
When loading an mp, initialize `MetaPartitionConfig.PartitionID`
correctly. Otherwise, if something goes wrong in `mp.onStart`,
we can only get "id=0".
=> metanode: Show metapartition id correctly

metanode/metrics.go
Currently we have metric `mdInodeCount`, but not `mdDentryCount`. Adding this metric will help us monitor `metanode`.
```release-note
```
=> Metric: add metric mpDentryCount

authnode/server.go, datanode/partition_raft.go, master/server.go, metanode/metanode.go, metanode/raft_server.go, raftstore/monitor.go, raftstore/raftstore.go
Signed-off-by: true1064 <true1063@163.com>
now we have raftstore.monitor to check raft health status periodically and print specific log when abnormal.
raftstore.monitor can be optimized:
1. make abnormal threshold configurable
2. distinguish between an anomaly that has just been detected and that has persisted for a long time，such as print different logs for the two cases. Then users can configure different alarm levels for the two cases by monitoring log files.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1543
```release-note
```
=> enhance: Optimize raft health monitoring policies.

.github/workflows/ci.yml, blobstore/Dockerfile, blobstore/Makefile, blobstore/build.sh, blobstore/init.sh, blobstore/start_docker.sh
closes: #1571
Signed-off-by: slasher <shenjie1@oppo.com>
zlib 1.2.12 404 Not Found.
https://zlib.net/  
Due to the first bug fix, any installations of 1.2.12 or earlier should be replaced with 1.2.13.
=> build(cli): make cli with module name

cli/cmd/cluster.go, cli/cmd/const.go, docs/source/admin-api/master/cluster.rst, sdk/master/api_admin.go
We can set node info by cfs-cli. But `MaxDpCntLimit` cannot be set by cfs-cli at present. We should support this.
Before the change:
After the change:
=> Feature: support setting MaxDpCntLimit by cfs-cli

datanode/partition_op_by_raft.go, datanode/wrap_prepare.go
We advance the check of disk limiter to `checkPartition()` for random write, which can improve the efficiency of disk limiter. Also consistent with the logic of `sequential write`.
=> [Enhancement] Optimize the qos for random write

datanode/partition.go, datanode/space_manager.go
In datanode doShutdown(), we stop extentStore before raftStore. But stopping extentStore will take a long time. This will delay triggering the data partitions to elect the leader, causing the client task to fail.
=> [BugFix] The datanode shutdown logic affected data partitions unable to elect the leader

cli/cmd/cluster.go, cli/cmd/fmt.go, sdk/master/api_admin.go
When run `cfs-cli cluster info`, the result losts `MaxDpCntLimit`. We should add it.
=> Enhancement: Cluster info lost MaxDpCntLimit

master/api_service.go, master/cluster_stat.go, master/gapi_cluster.go
Fix: InodeCount is shown to be inconsistent in /admin/getCluster and /client/volStat
InodeCount is shown to be inconsistent in /admin/getCluster **(always 0)** and /client/volStat.
/admin/getCluster:
/client/volStat:
=> Fix: InodeCount is shown to be inconsistent in /admin/getCluster and /client/volStat

cli/cmd/fmt.go
Format the print info of metanode and datanode in fmt.go
=> FIX: format the code of fmt.go

client/fuse.go
fix the wrong fuse subtype from "cubes" to "cubefs"
=> FIX: fix the wrong fuse subtype

datanode/partition_raft.go
we test the cubefs by the following step:
1. delete one replica of a dp from the host(dn1)
#cli del-replica dn1 info dp 
2. add the replica of this dp back to the host in step 1
#cli add-replica dn1 info dp 
and found that the meta info of this dp lack of dn1.
The reason is that the dp.replicas was not updated after #removeRaftNode, and cause bad judgment in #handlePacketToAddDataPartitionRaftMember
=> [BugFix] update dp replicas after removing a raft node

master/limiter.go
QosCtrlManager uses wrong type when update `LastMagnify` for flowWVal.
=> [BugFix] QosCtrlManager uses wrong type when update limit

metanode/api_handler.go
The interface `getPartitionById` should return more detail message to facilitate trace. Otherwise, after the mp is queried, `VolName`, `PartitionType` and the `Range` of the mp need to be queried through other interfaces.
After the change:
=> Enhancement: Add more info for mp to facilitate trace

util/exporter/exporter.go
remove the redundant condition for enablePush
=> FIX: remove redundant condition for enablePush

master/cluster.go
When we freeze the cluster, then create volume. There is an error `initDataPartition failed, less than 3`. However, the volume was created successfully. 
Because after freeze the cluster, `DisableAutoAllocate` would be set to true, and would not auto allocate dataPartitions for new volume. So the number of dataPartitions is 0. So we should not check the dp number in this scenario.
The related code:
```
func (c *Cluster) batchCreateDataPartition(vol *Vol, reqCount int) (err error) {
for i := 0; i < reqCount; i++ {
if c.DisableAutoAllocate { // After freeze the cluster, c.DisableAutoAllocate would be set to true
log.LogWarn("disable auto allocate dataPartition")
return fmt.Errorf("cluster is disable auto …
```
=> [BugFix] Creating vol when the cluster is frozen should not check the dp number

cli/cmd/compatibility.go, metanode/manager_op.go, metanode/metrics.go, metanode/partition.go, metanode/partition_free_list.go, metanode/partition_fsm.go, metanode/partition_fsmop_dentry.go, metanode/partition_fsmop_inode.go, metanode/partition_op_dentry.go, metanode/partition_op_inode.go
1. reduce btree copy when get btree length, this optimization can reduce copy on write times
2. get inode in deleteWorker is readonly, there is no need use CopyGet.  When bulk delete, CopyGet in deleteWork will lead to too many inodes COW. if snapshot is slow, these lazy to delete inodes will have 2 copies in memory, which may cause oom.
=> Fix: metanode: reduce btree cow times and change copyGet in deleteWorker to Get

objectnode/api_handler_object.go
Signed-off-by: Huweicai <i@huweicai.com>
According to AWS S3 specification: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html
The value of header 'x-amz-copy-source' must be URL encoded, so the Copy() interface may works bad if the source path contains Chinese or other non-ASCII character.
=> fix: header 'x-amz-copy-source' may be url encoded

metanode/inode.go
Recently, we add the metrics for **freeList** and found that the length of freelist on the follower did not decrease when we deleted a dir.
The reason is that the leader may ignore the dir inode, not send **opFSMInternalDeleteInode** to follower which will remove the dir from the freelist.
As the freelist is used to delete the extent file async, the dir inode.id is no need to push into freelist.
=>  [BugFix] dir inode.id can not be removed from follower freeList

metanode/metanode.go, metanode/metrics.go, metanode/server.go
Add metric `connectionCnt` for metanode.
=> [Metric] Add connectionCnt metric for metanode

master/meta_node.go
MaxMemAvailWeight overflow when metanode used mem larger than config.total mem
=> BugFix: MaxMemAvailWeight overflow when metanode used mem larger than config.total mem

datanode/metric.go, datanode/stat.go
Add metrics for datanode. Include `CapacityToCreateDp`, `ConnectionCnt`, `DpCount`, `TotalDpSize`, `Capacity`.
=> [Metric] Add metrics for datanode

metanode/manager.go, metanode/partition.go, metanode/partition_store.go
In metanode startup process, the files in snapshotDir will loaded into memory to build the metadata.
If the files lost for some reason, the metanode should stop loading the metapartition instead of building the wrong metadata.
=> [Bugfix] fix snapshot files stat error in metanode startup process

.github/workflows/ci.yml
paths-ignore:
- '.github/**'
- 'docs/**'
- 'docs-zh/**'
- '**.md'
Signed-off-by: slasher <shenjie1@oppo.com>
=> chore(docs): ignore cfs ci when matching those paths

docs-zh/source/admin-api/master/volume.rst
update doc for volume usage, user need pay attention on raftForceDel param, it's used in  interface of /dataReplica/delete, and can only be used when replica cann't be avaliable any more.
=> update: update volume doc

metanode/partition_store.go
The problem:
In a previous commit which intended to strengthen the check when metanode loading metapartitions，the checking  has been  modified as reporting error if dir 'snapshot ' not exists in the metapartition's dir. But this may cause problems if the some metapartitions are newly created and has not generated  dir 'snapshot ' yet，in this senario metanode can't restart for it will failed to load sunch metapartitions .
The fix:
Rollback codes of checking dir 'snapshot ' to before the above commit，just sikp it if  dir 'snapshot ' not exists.
=> fix: allow meta partition to start when snapshot directory not exists

cli/cmd/const.go, cli/cmd/fmt.go, cli/cmd/vol.go, master/api_args_parse.go, master/api_service.go, master/cluster.go, master/const.go, master/metadata_fsm_op.go, master/vol.go, proto/admin_proto.go, proto/model.go, sdk/master/api_admin.go
The background:
Recent versions have enhanced checking of volume uese space, if a volume's used space >= capacity, all its datapartitions will be changed to readonly status, to make it can't be written any more. But this enhancement will cause write op failed when upgrading elder versions if volumes's used space have been exceeds capacity.
So, a configurable switch to control checking of volume's used space is needed.
The enhancement:
Add a configurable switch to control checking of volume's used space. when a volume's used space >= capacity, all its datapartitions will be changed to readonly status only if the switch is on.
The switch is off by default.
The switch can be set in /admin/createVol cmd. example: `cfs-cli volume create ${VolName} ${Owner}  --readonly-when-full=true -y`
The …
=> enhance: add a configurable switch to control whether the volume's dataparitions become read-only when the volume is full

.github/workflows/release_test.yml
disable release ci checks. (cherry pick from branch release-3.2.1)
=> chore: disable release ci checks

client/fuse.go, depends/bazil.org/fuse/examples/clockfs/clockfs.go, depends/bazil.org/fuse/examples/hellofs/hello.go, depends/bazil.org/fuse/fs/fstestutil/mounted.go, depends/bazil.org/fuse/fs/serve.go, depends/bazil.org/fuse/fuse.go, depends/bazil.org/fuse/options.go, proto/mount_options.go
A fuse client can hang due to a server exception or hardware failure. We have implemented a timeout mechanism for fuse clients, which is not enabled by default but is enabled by configuring `requestTimeout`. Currently, this feature works well in our cluster.
=> [Enhancemant] Support fuse request timeout, add client metrics

util/log/log.go
We found that the size of client log dir in abnormal which was cause by qos.log
We set the logLevel to info, the size of qos.log keeps growing.
=> [BugFix] change QosWriteDebugf log level to debug

docs-zh/source/user-guide/k8s.md
Kubernetes is migrating its image registry from [[k8s.gcr.io](http://k8s.gcr.io/)](http://k8s.gcr.io/) to [[registry.k8s.io](http://registry.k8s.io/)](http://registry.k8s.io/).
Part of kubernetes/k8s.io#4780.
This is only a documentation change.
```release-note
NONE
```
=> chore: migrate from k8s.gcr.io to registry.k8s.io

blobstore/cli/blobnode/chunk.go, blobstore/cli/blobnode/chunk_data.go, blobstore/cli/blobnode/chunk_meta.go
_**meta**_
```
$>  blobnode chunk dump meta -h
dump shards of blobnode meta in rocksdb
Usage:
meta [flags]
Flags:
--chunk  string    chunk name
--dbpath string    rocksdb path dir
-h, --help             display help
```
_**data**_
```
$>  blobnode chunk dump data -h
dump shards in blobnode static chunk file
Usage:
data [flags]
Flags:
--bid       int       dump bid (default: 0)
--chunkfile string    chunk file path
--datadir   string    write data of bids to dir
-h, --help                display help
--metafile  string    write meta of bids to file
```
=> add blobnode chunk dump tools

master/api_service.go, master/cluster.go, master/http_server.go, master/meta_node.go, master/metadata_fsm_op.go, metanode/manager.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_file_stats.go, metanode/partition_store.go, proto/admin_proto.go
Adding the file stats function to analyse the files for each volume. 
It will read the inode file from snapshot dir and count the files for several size range.
We can view the file distribution for each volume on grafana.
We also add a cmd to control the file stats function enable, the default value is false.
=> [Feature] add file statistics function

master/api_service.go, master/http_server.go, proto/admin_proto.go
Sometimes, we want to get the status of the cluster, especially for functions that are enabled through dynamic configuration, such as DiskQos, DecommissionLimit, FileStats, etc. 
We want to add an interface that can view the values of these configurations, rather than looking them up one by one
=> Enhance: add a http request to get cluster persist configuration

blobstore/access/stream_get.go
=> fix(access): getting next shard when connection refused of blobnode

blobstore/cli/scheduler/migrate.go, blobstore/common/errors/scheduler.go
* Support showing offline or repair task progress with blobstore-cli
The final result is displayed below:
```
[===========================>                      ] MigratedTasksCnt: 2/TotalTasksCnt: 4
```
fixes #1900
=> [Feature]: support showing migrating process

datanode/partition_raft.go, datanode/server.go, datanode/server_handler.go, master/api_service.go, master/cluster.go, master/http_server.go, master/metadata_fsm_op.go, metanode/api_handler.go, metanode/metanode.go, metanode/raft_server.go, proto/admin_proto.go, util/config/config.go
Currently, metanode/datanode may be added to other clusters due to the incorrect configuration during mn/dn restart.
If more than two metanode are mistakenly added to other clusters, some metapartition may be missing two replicas, resulting in client access errors.
We add the cluster identification function, which generates the unique cluster ID through commands and persists it in the master rocksdb. When metanode and datanode start for the first time, the ID will be obtained from the master and persists to the data directory, and will be checked when the metanode and datanode restart. 
We add a few new commands in this pr:
1. Command to generate uuid;
2. Command to query clusterUUID;
3. Command to enable metanode/datanode to check clusterUUID during startup, the default value is false; …
=>  Feature: add ClusterUUID for mn/dn to identify a cluster upon restart

build/build.sh, master/api_service.go, master/api_service_test.go, master/cluster.go, master/config.go, master/data_node.go, master/dp_count_limiter.go, master/metadata_fsm_op.go, master/server.go, proto/model.go
cfs-cli supports setting the maximum number of dp on datanode.
fixes #1897 
@Victor1319 
```release-note
```
=> [Feature]: The cfs-cli supports setting the maximum number of dp on datanode

blobstore/build.sh
To re-use source tarballs if exists to decrease build time.
With this enhancement, developers can download 3rd-party source tarballs to `.deps/` to accelerate the build process if there is a poor network to GitHub.
```release-note
```
=> [Enhancement]reuse 3rd-party source tarballs if exists on building blobstore

build/build.sh, docs-zh/source/faq/build.md, docs/source/faq/build.md
To make it effective, just add `export CXXFLAGS=-Wno-error` at the end of `env.sh` before executing `source env.sh`.
```release-note
```
=> [Enhancement]Add faq & customize CXXFLAGS support on building `rocksdb`

datanode/partition_raftfsm.go, metanode/partition_fsm.go, metanode/partition_store_ticket.go
1. fix HandleLeaderChange trytoleader wrong use: 
metanode's tcp server is started before start raft (fixed here: https://github.com/cubefs/cubefs/pull/1256/commits/38fb340311781ba9d7cacad34a3fcd765bccea84) , so there is no need to dail server port, what's more trytoleader is wrong used, trytoleader will let this node force compagin and try to become leader , it will do nothing because this node is already became leader. L:407 returned after trytoleader will cause startStoreTick never be triggered....
2. scheduleState should use atomic
we met one region didn't dump snapshot, but other regions(include leader) could dump regularly.  i found scheduleState has race condition, which may cause  if condition always false. detail here: …
=> [Fix] metanode snapshot not scheduled

metanode/inode.go, metanode/partition.go, metanode/partition_fsmop_inode.go, metanode/time.go, metanode/time_test.go
GetCurrentTimeUnix use atomic is much quicker
**benchmark**
```
$ go test -bench="^BenchmarkGet" -run=none
goos: linux
goarch: amd64
pkg: github.com/cubefs/cubefs/metanode
cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
BenchmarkGetCurrentTimeUnix-16    	1000000000	         0.3317 ns/op
BenchmarkGetCurrentTime-16        	100000000	        10.98 ns/op
BenchmarkGetNowTime-16            	43397809	        27.76 ns/op
PASS
ok  	github.com/cubefs/cubefs/metanode	2.796s
```
```release-note
```
=> [Enhancement] metanode: GetCurrentTimeUnix use atomic

autofs/README.md, autofs/main.go
fix(cfsauto): fix build time for cfsauto -V option
for example:
```bash
go build -v -ldflags="-X main.buildVersion=1.1 -X 'main.buildDate=$(date '+%Y-%m-%d %H:%M:%S')'"
./cfsauto -V
```
Please check the README.md file under autofs direction for more details.
=> fix(cfsauto): fix build time for cfsauto -V option

master/cluster.go, master/http_server.go, master/metadata_fsm_op.go
close: #2051
Do not consider the issue of cold volume anymore, relax the check for empty DP quantity, and assume the master-follower dps synchronization logic is normal by default, which can reduce the complexity of processing reads. Solve the error log caused by datanode requesting cold volume information from the follower. Although retrying can solve the problem, it is not user-friendly
=> enhance: only deleted volume be ignored when do dps cache transfer

master/cluster_task.go, master/data_partition_check.go, master/monitor_metrics.go
Optimized some dp/mp error query and metrics report:
(1) [Bug]: the metrics dp_missing_Leader_count and dp_no_leader not condsider cold volume's data partition #2050
(2) [Feature]: the cmd "cfs-cli metapartition check" should not involve markDelete volumes #2053 
fixes #2053 
fixes #2050
=> [Develop 3.3.0] Optimized some dp/mp error query and metrics report

master/cluster.go, master/monitor_metrics.go
fix(master): for data partition view cache of follower master, cancel metrics and warn log when volume is deleted
this bug is introduced when developing br develop-3.3.0  previousely
=> [Develop 3.3.0] fix(master): for data partition view cache of follower master, cancel metrics and warn log when volume is deleted

docs-zh/source/design/metanode.md
I noticed that there was a missing closing parenthesis in the design document . This PR fixes the issue by adding the missing parenthesis.
- Add missing closing parenthesis to the design document in the relevant section.
Please let me know if there are any additional changes required or if you have any questions.
Thank you for considering my contribution!
=> docs: Fix missing closing parenthesis in design document

blobstore/common/rpc/auditlog/auditlog.go, blobstore/common/rpc/auditlog/auditlog_test.go, blobstore/common/rpc/auditlog/proto.go
return noop log closer if not config log dir
close #2116
=> fix(rpc): fixup panic if auditlog bodylimit is negative

master/monitor_metrics.go
Obsolete VolNames should not include normal volume, all normal vols in followerReadManager be deleted and lead to read dps request failed.
=> fix(master):Obsolete VolNames should not include normal volume

master/api_service_test.go, master/meta_node_test.go
When I run `go test` it failed.
My shell code is:
```shell
cd master
go test -run "^(TestSetMetaNodeThreshold|TestSetDisableAutoAlloc|TestGetCluster|TestGetIpAndClusterName|TestDisk|TestMarkDeleteVol|TestSetVolCapacity|TestPreloadDp|TestUpdateVol|TestGetVolSimpleInfo|TestCreateVol|TestCreateMetaPartition|TestCreateDataPartition|TestGetDataPartition|TestLoadDataPartition|TestDataPartitionDecommission|TestGetMetaPartitions|TestGetDataPartitions|TestGetTopo|TestGetMetaNode|TestGetNodeInfo|TestSetNodeMaxDpCntLimit|TestAddDataReplica|TestRemoveDataReplica|TestAddMetaReplica|TestRemoveMetaReplica|TestClusterStat|TestListVols|TestCreateUser|TestGetUser|TestUpdateUser|TestGetAKInfo|TestUpdatePolicy|TestRemovePolicy|TestTransferVol|TestDeleteVolPolicy|TestLis …
```
=> fix(master): fix api_service_test.go

master/master_manager_test.go, master/metadata_fsm.go, master/server.go, raftstore/store_rocksdb.go, util/fileutil/exists.go, util/fileutil/exists_test.go
* Optimize raft snapshot in master.
* Expose the rocksdb `close` interface.
The Benchmark Code:
```go
const volForSnapshot = "snapshtVol"
const volForSnapshotCount = 300
func BenchmarkSnapshot(b *testing.B) {
var err error
// perpare status
req := &createVolReq{
name:             "",
owner:            "cfs",
size:             1,
mpCount:          1,
dpReplicaNum:     3,
capacity:         300,
followerRead:     false,
authenticate:     false,
crossZone:        false,
normalZonesFirst: false,
zoneName:         testZone2,
description:      "",
qosLimitArgs:     &qosArgs{},
}
for i := 0; i != volForSnapshotCount; i++ {
req.name = fmt.Sprintf("%v_%v", volForSnapshot, i)
server.cluster.createVol(req)
}
time.Sleep(5 * time.Second)
mdSnapshot, err := …
```
=> [Feature]: Master does snapshot optimization

metanode/partition_free_list.go, repl/repl_protocol.go, util/smux_conn_pool.go
1. not use connect pool when delete extent in metanode.
2. fix smux connect close check bug.
fixes #2134, #2133
=> Add some optimized code

master/id_allocator.go, master/id_allocator_test.go
* This pull request optimize the allocation of `qosClientId`.
* ~~The allocation of `qosClientId` doesn't require raft to persist data.~~
* ~~Compatibility with older versions of code.~~
* ~~Conflict check for low bits overflow is supported.~~
fixes #1918 
* ~~This pull request assuming it's impossible for `qosClientId` from `0` to grow to max value of `uint32` in one term.~~
* ~~This pull request assuming it's impossible for raft term grow to max value of `uint32`.~~
* Please contract me if this pull request have passed your review, then I will rebase and …
=> [Feature]: Master qosClientId allocation optimization

storage/extent.go
offset have already aligned to PageSize, so never mod PageSize !=0， so delete the redundancy code
=> cleanup(datanode):  storage/extent.go

client/fuse.go, master/api_service.go, master/cluster.go, master/config.go, master/http_server.go, master/server.go, proto/admin_proto.go, sdk/master/api_admin.go
We can configure the push gateway address in the master, and and when the client starts, if they didn't have configuration in it's file, they will try to pull the configuration from master.
Edit master's configuration file, add this line:
```json
{
"monitorPushAddr": "http://192.168.0.101:8500"
}
```
After master starts, you can get the push gateway address by this option:
```shell
$ curl http://192.168.0.11:17010/admin/getMonitorPushAddr
{"code":0,"msg":"success","data":"http://192.168.0.101:8500"}
```
When client starts, in its log file:
```
2023/06/09 07:54:51 use remote push addr http://192.168.0.101:8500
```
That means the master successfully obtained the configuration from master
fixes #1912
=> feat: support the master to uniformly configure the push gateway address of the data reported by the client

master/cluster.go, metanode/partition.go, metanode/partition_fsm.go
1)deleted volume should not load datapartitions
2)need lock while update data of followerReadManager
3)fix: follower read not take effect while on apply snapshot
4)clean unused uid space manager log
=> update several proecess 1)deleted volume 2)lock issue 3）metadata follower read manager

metanode/partition.go, storage/extent_cache.go
1. use rlock to avoid map panic when stop dp.
2. remove updateSize() goroutine.
fixes #2150,  fixes #2153
```release-note
```
=> fix datanode panic and remove update size goroutine.

blobstore/run.sh
After executing INIT, the current directory is located at the root directory of the project. So the target log directory is `./blobstore/run/logs` instead of `./run/logs`
If we use `./run/logs`, errors will occur during the installation of the Erasure Code Subsystem.
(script from https://cubefs.io/docs/master/deploy/node.html#install-erasure-code-subsystem)
```shell
$ cd cubefs/blobstore
$ ./run.sh --consul
build blobstore    success
./run.sh: line 15: ../blobstore/run/logs/consul.log: No such file or directory
```
=> fix(blobstore): fix build error when run directory not exits

master/cluster.go, master/master_manager.go, master/metadata_fsm_op.go, master/vol.go
1. set dp status readwrite
2. not update datapartition cache before load meta from disk ready.
```release-note
```
=> set dp status readwrite when load from disk.

metanode/const.go, metanode/metanode.go, metanode/partition_fsm.go, metanode/partition_item.go, metanode/raft_server.go, metanode/transaction.go, util/config/config.go
(1) add a configuration item for raft retainLogs, for metaNode; 
(2) add a configuration item to set which format version to use when mp raft leader send snapshot to follower; 
(3) when follower apply snapshot, won't fail if format snapshot version not match, just handle the part of fields it can recognize;
(2 )and (3) are the  focus of this revision，to handle the compatibility of snapshot format of meta partitifion when upgrading. 
=> feat(metanode): optimize mp leader send snapshot to follower

master/cluster.go
vols info not protect with lock in partition create processse-note
=> fix(master): vols info not protect with lock in partition create process

metanode/partition_item.go
optimization: meta partition raft leader send snapshot includes txInfo, txRbInode, txRbDentry only when snapshot format version is v1.
=> feat(metanode):  meta partition raft leader send snapshot includes txInfo, txRbInode, txRbDentry only when snapshot format version is v1

metanode/transaction.go, proto/transaction.go
add concurrency cnt limit when process transaction
Closes #2205
```release-note
```
=> refactor(meta): add concurrency cnt limit when process transaction

client/fs/super.go, client/fuse.go, master/metadata_fsm_op.go, proto/mount_options.go, sdk/data/stream/extent_client.go, sdk/data/wrapper/wrapper.go
(1) on master: NOT set all data partitions's status to ReadWrite when becaming a leader;
(2) on client: when periodically update data partition view in the background, revert the condition of whether to refresh dpSelector as "writable dp count should >= minWriteAbleDataPartitionCnt"; and the param minWriteAbleDataPartitionCnt is changed to configurable now, and the config should be updated accordingly.
=> feat(master, client): optimize data partition status management:

depends/tiglabs/raft/monitor.go, depends/tiglabs/raft/raft.go, depends/tiglabs/raft/raft_fsm.go, raftstore/monitor.go
…them from raft monitor accordingly
the bug: 
when raft replicas or raft partitions are deleted, them are still in raft monitor and the error log is still printing.
fix:
when raft replicas or raft partitions are deleted, delete them from raft monitor accordingly
=> fix(raft): when raft replicas or raft partitions are deleted, delete them from raft monitor accordingly

datanode/wrap_post.go, datanode/wrap_prepare.go, repl/packet.go
When data processing cannot be accessed, read requests may be suspended for an extended period of time.
close:#2237
```release-note
```
=> When data processing cannot be accessed, read requests may be suspended for an extended period of time.

blockcache/bcache/client.go, client/fs/file.go
close:#2242
Client would check cache path received from bcache service, in case   cache path belongs to other file
=> bugfix(client):check bcache cache file path

metanode/partition_fsmop_inode.go, metanode/partition_op_extent.go
1.move fsm uid quota to api handler for performance
2.refactor code of uid quota and dir quota to reduce duplicated code
3.uid add space in extentappend should not drop extent
=> refactor(metanode): refactor quota check and uid check

client/fs/file.go, libsdk/libsdk.go, sdk/data/blobstore/writer.go
1.In cold volume scenario, fwriter is not released when file is opened in write mode first and then opened in read-only mode.So when file is closed, fwriter's buf is returned to cache pool twice. This will result in subsequent write operations obtaining two identical buffer addresses from the cache pool. 2.CloseStream function will return fileWriter's buf to cache pool to avoid OOM.
close: #2258 #2257
=> bugfix(client): Fix the logic of returning the cache to the cache pool

client/fs/file.go, libsdk/libsdk.go, sdk/data/blobstore/writer.go
close: #2258 #2257
1.In cold volume scenario, fwriter is not released when file is opened in write mode first and then opened in read-only mode.So when file is closed, fwriter's buf is returned to cache pool twice. This will result in subsequent write operations obtaining two identical buffer addresses from the cache pool. 2. closeStream function will return fileWriter's buf to cache pool to avoid OOM.
=> bugfix(client):fix the logic of returning the cache to the cache pool. 

README.md
OpenSSF Scorecard tool can bring the following benefits to open-source software projects:
1.Evaluating project security and sustainability
2.Improving the quality and credibility of open-source software projects
3.Promoting the development of the open-source software community
4.Enhancing developers' security awareness and skills
=> doc: add OpenSSF Scorecard

.github/dependabot.yml
Using Dependabot can bring several benefits, such as:
1.Ensuring that dependencies are up-to-date
2.Saving time and effort
3.Improving security
=> doc: add dependabot

metanode/partition.go, metanode/partition_fsm.go, metanode/partition_fsmop_dentry.go, metanode/partition_fsmop_inode.go, metanode/partition_item.go
1. fix newMetaItemIterator nonidempotent bug when it is running concurrently with fsm apply
2. use sync.Mutex much better than RWMutex, there is no concurrency reads
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2222 #1580
=> fix(metanode):  newMetaItemIterator nonidempotent with lock

blobstore/scheduler/base/kafka_consumer_group.go, blobstore/scheduler/base/kafka_consumer_group_test.go, blobstore/scheduler/base_mock_test.go, blobstore/scheduler/blob_deleter.go, blobstore/scheduler/blob_deleter_test.go, blobstore/scheduler/config.go, blobstore/scheduler/shard_repairer.go, blobstore/scheduler/shard_repairer_test.go, blobstore/scheduler/startup.go, docs-zh/source/maintenance/configs/blobstore/scheduler.md, docs-zh/source/user-guide/blobstore.md, docs/source/maintenance/configs/blobstore/scheduler.md, docs/source/user-guide/blobstore.md
1. add batch consume kafka msg for scheduler, to solve handle blob delete msg too slow.
2. remove kafka client manage offset local, let kafka server manage offset.
=> feature(scheduler): batch consume kafka msg, kafka server manages offset

objectnode/api_handler_multipart.go, objectnode/api_handler_object.go
Fixed saving the ACL when the non-volume owner uploaded the object.
**Which issue this PR fixes**: fixes #2318
=> fix(objectnode): save the ACL of the object uploaded by the non-volume owner

cli/cmd/vol.go
close: #2310
Signed-off-by: baijiaruo <baijiaruo@126.com>
When updating the volume operation and modifying other parameters of the volume, the quota will be set to false
=> fix(cli): update volume operation cause quota switch to be off

blobstore/common/kafka/monitor.go, blobstore/common/kafka/monitor_test.go, blobstore/scheduler/base/base_test.go, blobstore/scheduler/base/kafka_consumer_group.go, blobstore/scheduler/base/kafka_consumer_group_test.go, blobstore/scheduler/base/kafka_monitor.go, blobstore/scheduler/base/kafka_monitor_test.go, blobstore/scheduler/blob_deleter.go, blobstore/scheduler/blob_deleter_test.go, blobstore/scheduler/config.go, blobstore/scheduler/startup.go, blobstore/scheduler/startup_test.go
**What this PR does / why we need it:**
1. The original version was ok, and it summarized all kafka partitions on CM, and the master scheduler node could get the offset/latency of all partitions at once
2. A bug was introduced in the previous version, which was that scheduler only recorded a few partitions in its own node consumption group and could not get all partition information. In this way, the master scheduler cannot be reported in aggregate, if the offset records of other partitions are through http get, or if each scheduler is reported metric separately: the Kafka consumption group will be reassigned when the node restarts, resulting in an inaccurate offset.
3. If kafka messages are consumed too quickly, resulting in a blobnode disk overload error, speed limits are required
- …
=> fix(scheduler): kafka offset metric is not accurate,update kafka offset getter

metanode/partition_op_inode.go
Fix bug that func `TxUnlinkInode` return result code is wrong when submit raft failed.
**Which issue this PR fixes**: fixes #2366
```release-note
```
=> Fix bug that func `TxUnlinkInode` return result code is wrong when submit raft failed.

.github/workflows/issue_inactive.yml, .github/workflows/issue_similarity.yml
When github action executes these two files, an error will be reported:
```
The workflow is not valid. .github/workflows/issue_similarity.yml (Line: 8, Col: 11): Unexpected value 'read|write'
The workflow is not valid. .github/workflows/issue_inactive.yml (Line: 10, Col: 11): Unexpected value 'read|write'
```
`read|write` is not a valid permission setting, you need to specify `read` or `write` for each permission. We have to change it to the following code:
```
permissions:
issues: write
```
This means that this GitHub Action has the right to write (and read) issues. The `write` permission will include the `read` permission
=> fix(workflow): issue permission changes to `write`

depends/tiglabs/raft/config.go, depends/tiglabs/raft/diff_test.go, depends/tiglabs/raft/proto/proto.go, depends/tiglabs/raft/raft_fsm.go, depends/tiglabs/raft/raft_fsm_candidate.go, depends/tiglabs/raft/raft_fsm_candidate_test.go, depends/tiglabs/raft/raft_fsm_follower.go, depends/tiglabs/raft/raft_fsm_leader.go, depends/tiglabs/raft/raft_fsm_leader_test.go, depends/tiglabs/raft/raft_fsm_state.go, depends/tiglabs/raft/raft_fsm_test.go, depends/tiglabs/raft/raft_log_test.go, depends/tiglabs/raft/raft_log_unstable_test.go, depends/tiglabs/raft/raft_paper_test.go, depends/tiglabs/raft/server_test.go, metanode/api_handler.go, metanode/partition.go, raftstore/raftstore.go
CubeFS's MetaNode, DataNode, and Master components all use Raft. However, in exceptional situations such as network partitioning, the communication between nodes may be hindered, resulting in unnecessary leader election processes .
To address this issue, we use pre-Vote which involves conducting a preliminary round of voting before the formal election. Only when the candidate receives the support of the majority of nodes in the pre-vote can it participate in the formal election. This can reduce unnecessary leader election processes, improve system efficiency, and reliability.
add pre
fixes：#2383
```release-note
```
When upgrading versions, it is important to ensure that the Raft service runs …
=> [Feature]: add Pre-vote capability to CubeFS Raft 

client/fuse.go, master/cluster_task.go, master/config.go, master/server.go, master/vol.go, metanode/manager.go, metanode/manager_op.go, metanode/partition_op_transaction.go, metanode/transaction.go, proto/fs_proto.go, proto/packet.go, proto/transaction.go, sdk/master/client.go
1. fix the bug that update volume tast exit because of request master error once.
2. add switch to control whether enable automatic create partition.
3. support clear orphan tx in rm caused by network problem.
4. update the return err msg to avoid return empty msg.
fixes #2411 
fixes #2410
```release-note
```
=> support to clear orphan tx info.

cli/cmd/fmt.go, cli/cmd/nodeset.go, cli/cmd/root.go, master/api_service.go, master/api_service_test.go, master/http_server.go, master/operate_util.go, master/topology.go, proto/admin_proto.go, proto/errors.go, proto/model.go, sdk/master/api_admin.go
support listing nodesets and displaying space capacity
The third point of issue #1894: **The total amount of nodeset, space, etc.**
request: `http://127.0.0.1:8080/nodeSet/list`
```json
{
"code": 0,
"msg": "success",
"data": [
{
"ID": 1,
"Capacity": 18,
"Zone": "zone1",
"MetaNodeNum": 2,
"DataNodeNum": 2
},
{
"ID": 4,
"Capacity": 18,
"Zone": "zone2",
"MetaNodeNum": 4,
"DataNodeNum": 4
}
]
}
```
request: `http://127.0.0.1:8080/nodeSet/list?zoneName=zone2`
```json
{
"code": 0,
"msg": "success",
"data": [
{
"ID": 4,
"Capacity": 18,
"Zone": "zone2",
"MetaNodeNum": 4,
"DataNodeNum": 4
}
]
}
```
request: `http://127.0.0.1:8080/nodeSet/get?nodesetId=1`
```json
{
"code": 0,
"msg": "success",
"data": {
"ID": 1,
"Capacity": 18, …
```
=> feat(master): support listing nodesets and displaying space capacity

metanode/metanode.go, metanode/partition_fsmop_transaction.go, metanode/partition_op_inode.go
check error fisrt to avoid panic when metanode request master. fixes #2421
when unlink dir ino, return ino info in rbInode. fixes #2422 
```release-note
```
=> fix retry unlink dir inode failed bug.

cli/cmd/fmt.go, master/api_service.go, master/data_partition.go, proto/model.go
partition command support displaying in which nodeSet
The first point of issue #1894: **realize the display of dp and mp across nodeset**
```shell
$ cfs-cli datapartition info 1
...
Hosts :
[172.16.1.101:17310]  [172.16.1.104:17310]  [172.16.1.102:17310]
Zones :
[default]  [default]  [default]
NodeSets :
[1]  [1]  [1]
...
```
```shell
$ cfs-cli metapartition info 1
...
Hosts :
[172.16.1.101:17310]  [172.16.1.104:17310]  [172.16.1.102:17310]
Zones :
[default]  [default]  [default]
NodeSets :
[1]  [1]  [1]
...
```
=> feat(master): partitions support displaying in which nodeSet

shell/depoly.sh, shell/genConf.sh, shell/genIp.sh, shell/stop.sh
When I am trying [Install Basic Cluster](https://cubefs.io/docs/master/deploy/node.html#install-basic-cluster) in Standalone Mode, I discovered when I running this command:
```bash
sh ./shell/depoly.sh /home/data bond0
```
the configuration file in `/home/data/conf` will be overwrited.
So this pr is to ensure that if there is a configuration file in this directory, it will not continue to generate. In this way, we can easily test deployments **under different configuration files** by modifying these configuration files.
=> fix(shell): do not overwrite configuration file if file exists

docs-zh/source/user-guide/file.md, docs/source/user-guide/file.md
fix(doc): the value of "profPort" in client's configuration file example should be port instead of IP
=> fix(doc): the value of "profPort" in client's configuration file example should be port instead of IP

Makefile, build/build.sh
* Use GNU `-j` option to speed up make dependencies.
* The default value of `threads` option is half of cores, (e.g. You get `6` when running on a 12 cores machine).
**Usage:**
```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs-master-dev]
└─$ make threads=10
```
See also:
* [5.4 Parallel Execution(GNU Make)](https://www.gnu.org/software/make/manual/html_node/Parallel.html)
```release-note
```
=> [Feature]: Support parallel compile to speed up `pre_build`

cmd/cmd.go, util/log/log.go
* Print the content of  `*_warn.log`, `*_error.log`, `*_fatal.log` and `*_critical.log` in the startup process to the output.
**Before:**
```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/disk/master1/logs/master]
└─$ cat output.log | grep "Hello world"
┌──(nature㉿LAPTOP-9TS0FG11)-[~/disk/master1/logs/master]
└─$ cat master_error.log | grep "Hello world"
2023/07/26 16:30:59.669993 [ERROR] cmd.go:288: Hello world
```
**After:**
```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/disk/master1/logs/master]
└─$ cat master_error.log | grep "Hello world"
2023/07/26 16:34:41.333471 [ERROR] cmd.go:297: Hello world
┌──(nature㉿LAPTOP-9TS0FG11)-[~/disk/master1/logs/master]
└─$ cat output.log | grep "Hello world"
2023/07/26 16:34:41 [ERROR] cmd.go:297: Hello world
```
**Which issue this …
=> [Feature]: Master/DataNode/MetaNode start log optimization

client/fuse.go, proto/mount_options.go
Client support change the explicit name of the filesystem.
The default is still `"cubefs-" + [volume name]`
**configuration file:**
``` json
{
"masterAddr": "172.16.1.101:17010,172.16.1.102:17010,172.16.1.103:17010",
"mountPoint": "/home/data/client/mnt",
"volName": "vol_cross5",
"owner": "cfs",
"logDir": "/home/data/client/log",
"logLevel": "debug",
"fileSystemName": "testfs"
}
```
**mount the volume:**
```bash
cfs-client -c client.json
```
**result:**
```bash
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
testfs         1000G     0 1000G   0% /home/data/client/mnt
```
```bash
$ mount
testfs on /home/data/client/mnt type fuse.cubefs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
```
=> [Feature]: client support change the explicit name of the filesystem

authnode/api_service.go, authtool/authtool.go, cli/cli.go, cli/cmd/cluster.go, cli/cmd/config.go, cli/cmd/const.go, cli/cmd/datanode.go, cli/cmd/datapartition.go, cli/cmd/http_service.go, cli/cmd/metanode.go, cli/cmd/metapartition.go, cli/cmd/user.go, cli/cmd/vol.go, datanode/server.go, master/api_args_parse.go, master/cluster.go, master/const.go, master/http_server.go, master/server.go, metanode/const.go, metanode/metanode.go, proto/auth_proto.go, proto/errors.go, sdk/auth/client.go, sdk/master/api_admin.go, sdk/master/api_node.go, sdk/master/api_user.go, sdk/master/client.go, util/keystore/keystore.go
Currently, the config of the fuse client has the master address, and some body can send http requests to the master through this address, including deleting mp/dp whitout permission control.
We should add more permission control to the following http requests which can manage cluster:
//Master API cluster management
proto.AdminClusterFreeze
proto.AddRaftNode
proto.RemoveRaftNode
proto.AdminSetNodeInfo
proto.AdminSetNodeRdOnly
// Master API volume management
proto.AdminCreateVol
proto.AdminDeleteVol
proto.AdminUpdateVol
proto.AdminVolShrink
proto.AdminVolExpand
// Master API meta partition management
proto.AdminLoadMetaPartition
proto.AdminDecommissionMetaPartition
proto.AdminChangeMetaPartitionLeader
proto.AdminCreateMetaPartition
proto.AdminAddMetaReplica
proto.AdminDeleteMetaReplica …
=> [Enhancement] add authentication for master admin api

cli/cmd/fmt.go, datanode/server.go, docker/conf/datanode.json, master/api_args_parse.go, master/api_service.go, master/cluster.go, master/const.go, master/data_node.go, master/metadata_fsm_op.go, master/mocktest/data_server.go, master/topology_test.go, proto/admin_proto.go, proto/model.go, sdk/master/api_node.go
Add mediaType(SSD or HDD) property for datanode:
(1) add "mediaType" item in the config file of datanode, and it carries mediaType when it registers to master
(2) add "mediaType" field in master's datanode struct.
(3) the cmd 'cfs-cli datanode info' shows datanode's mediaType
=> feat(master/datanode/client):Add mediaType(SSD or HDD) property for datanode

.gitattributes
Developers are using different OSes (Windows and MacOS) the default for the line ending will differ. On the Windows machine the default for the line ending is CRLF, whereas on Linux/MacOS it's a LF.
After adding .gitattributes, any changes or new changes will automatically use the line endings specified.
fixes #
```release-note
```
=> add .gitattributes to enforce LF line endings

master/multi_ver_snapshot.go, metanode/inode.go, metanode/manager_op.go, metanode/sorted_extents.go
enhance(metanode): check version no need to reset all mask euqual towq MultiVersionFlag
fix(master):snapshot.make WaitGroup usage clear in aync job in 2phase version managment in case of wrong number counter
fix(metanode):snapshot.Extent append by diff verseq need consider as split key and add to refMap,or else the ek drop caused by modification and be considered as normal discard , the whole extent would be dropped
fixes #
```release-note
```
=> fix some bugs related to snapshot

cli/cmd/fmt.go, datanode/server.go, docker/conf/datanode.json, master/api_args_parse.go, master/api_service.go, master/cluster.go, master/const.go, master/data_node.go, master/metadata_fsm_op.go, master/mocktest/data_server.go, master/topology_test.go, proto/admin_proto.go, proto/model.go, sdk/master/api_node.go
Using new branch to develop hybrid cloud project, so cherry-pick the commits of the already merged pr #2463 to new branch 
develop-hybridcloud-frommaster
What this PR does / why we need it:
Add mediaType(SSD or HDD) property for datanode:
(1) add "mediaType" item in the config file of datanode, and it carries mediaType when it registers to master
(2) add "mediaType" field in master's datanode struct.
(3) the cmd 'cfs-cli datanode info' shows datanode's mediaType
=> feat(master/datanode/client):Add mediaType(SSD or HDD) property for datanode (to branch develop-hybridcloud-frommaster)

master/api_service.go, master/api_service_test.go, master/data_partition_check.go, master/meta_partition.go, master/vol.go, master/vol_test.go, metanode/partition.go
* Set dp and mp's Status to ReadOnly when forbid volume write.
* `splitMetaPartition` returns error when cluster disable and volume is forbidden.
* ~Datanode/Metanode persist config, when volume's forbidden changed.~
```release-note
```
=> [Fix]: For compatibility, set dp and mp's Status to ReadOnly when forbid volume write

master/multi_ver_snapshot.go, proto/model.go, sdk/data/stream/stream_writer.go
1) try append forget the discards process and check failed in metanode
write request cover the old ek and do append write for performace and discard old ek in the flush stage,
but the try append(client viewpoint don't know whether the extent right neighbor exist or not,need to try write,
but the async process of do append write need async dealing, which not easy to manage,
so use direct write append by raft submit in datanode for simple)
process use sync way but forget the discard process lead to inconsistent in metanode check
2) defer unlock is stale code and clean or else lead to deadlock
=> fix(client): snapshot.try append ek process forget the discards process and check failed in metanode

blobstore/common/rpc/auditlog/auditlog.go, blobstore/common/rpc/auditlog/auditlog_test.go, blobstore/common/rpc/auditlog/proto.go, blobstore/common/rpc/auditlog/response.go, blobstore/common/trace/tracer.go
In order to support the audit log of objectnode, certain modifications need to be made to the audit log of blobstore. For example:
1. Additional information needs to be printed in the audit log, but these fields cannot be passed to the user.
2. For the successful response of 2xx, it is completely unnecessary to print the data read by the user. Here, add a configuration item to disable body printing.
3. Fix the problem that the original context cannot be assigned by kv.
fixes #
=> feat(blobstore): to support objectnode auditlog

master/multi_ver_snapshot.go
the last commit clean the defer lock ,but forget release at the end if condition not satisfied and lead to deadlock
=> fix(master):last deadlock not complete

metanode/manager_op.go
What this PR does / why we need it:
problem of determination of meta partition replica status when reporting heartbeat, in func (m *metadataManager) opMasterHeartbeat(...):
1、no leader，set status as Unavailable
2、created inodeId reaches the end of MP，or MN mem usage exeeds threshold, change status as ReadOnly
but we expect the stauts should be Unavailable if no leader
=> fix(meta): Correct the determination of meta partition replica status when metaNode report heart beat, the status must be Unavailable if no leader.

master/cluster.go
What this PR does / why we need it:
currently, if initDataPartitions() failed in the creating vol procedure, the vol info is not cleaned, so it can be found in the master but can't be used.
should clean the vol info if initDataPartitions() failed when creating.
Which issue this PR fixes:
fixes https://github.com/cubefs/cubefs/issues/2019
=> fix(master): if init data partitions failed when create volume, mark volume status as delete to trigger background deletion.

.github/workflows/ci.yml
github action always fails because the disk is not enough
this pr removed Android SDKs and free up 14GB of space
There is actually more useless pre-installed software, such as .NET SDKs. But at present, the space is very enough after removing the android SDKs.
References：
[Ubuntu 22.04 github runner image](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md)
[Maximize available disk space for build tasks](https://github.com/easimon/maximize-build-space/blob/test-report/README.md)
=> feat(workflow): remove pre-installed android sdk to free up disk space

sdk/data/wrapper/data_partition_selector.go, sdk/data/wrapper/default_random_selector.go, sdk/data/wrapper/k_faster_random_selector.go
if request datanode to create extent failed, not remove the datapartition form dpSelector if it is the last one，
to avoid the dpSelector has no datapartition .
if any dn host of the dp can not be connected, it will be add to the exclude map and not retry:
```
func (dp *DataPartition) CheckAllHostsIsAvail(exclude map[string]struct{}) {
var (
conn net.Conn
err  error
)
for i := 0; i < len(dp.Hosts); i++ {
host := dp.Hosts[i]
if conn, err = util.DailTimeOut(host, proto.ReadDeadlineTime*time.Second); err != nil {
log.LogWarnf("CheckAllHostsIsAvail: dial host (%v) err(%v)", host, err)
if strings.Contains(err.Error(), syscall.ECONNREFUSED.Error()) {
exclude[host] = struct{}{}
}
continue
}
conn.Close()
}
}
```
=> refactor(client): if request datanode to create extent failed, not remove the datapartition form dpSelector if it is the last one.

metanode/dentry.go, metanode/extend.go, metanode/inode.go, metanode/manager_op.go, metanode/multi_ver_test.go, metanode/partition.go, metanode/partition_fsm.go, metanode/partition_fsmop_extend.go, metanode/partition_op_extend.go, metanode/partition_op_extent.go, proto/fs_proto.go, proto/model.go
enhance(metanode):snapshot.clean tempory snapshot by inner periodic check
Adopting a one-phase commit means that the master processor (MP) considers the prepared version as valid, and during the operation, it treats it as a version. This means that the MP may have partial temporary version information. However, the final valid version is on the master, which means that the dependency for reading historical versions on the edge side is the version list of the master, not the version list of the MP. When attempting versions in the form of 0, 100, 150, 200, with 150 being a temporary version, the version 100 is read, and it needs to include 150; otherwise, some data cannot be read due to the temporary version 150. Therefore, on the client side, it is …
=> snapshot.clean tempory snapshot by inner periodic check

master/cluster.go, master/multi_ver_snapshot.go, master/vol.go, metanode/inode.go, metanode/multi_ver_test.go, metanode/partition.go, metanode/partition_free_list.go, metanode/partition_op_extent.go, metanode/partition_store.go
enhance(master):Allow the periodic snapshot check strategy for volumes to run on a per-volume basis, utilizing routines
fix(metanode):snapshot.multiver meta store uniq with other snapshot meta
fix(master):snapshot.master persist snapshot info after creation as soon as possible
=> enhance snapshot 1)optimize master enable volumes parrellel strategy check  2) enhance snapshot verlist meta storage and consistent with other meta

cli/cmd/fmt.go, datanode/disk.go, datanode/partition.go, datanode/partition_raftfsm.go, datanode/server.go, datanode/space_manager.go, datanode/wrap_operator.go, master/api_service.go, master/data_node.go, proto/admin_proto.go, proto/model.go
feat(master/datanode/cli):
(1)datanode bad disk report to master adds: TotalPartititionCnt and DiskErrPartitionList
(2)cfs-cli display bad disk adds TotalPartititionCnt and DiskErrPartitionList accordingly
(3)datanode's data partition add disk err count record and log print
=> feat(master/datanode/cli):datanode bad disk report to master adds IoErrPartititionCnt and TotalPartititionCnt

datanode/partition_op_by_raft.go, datanode/wrap_operator.go, metanode/dentry.go, metanode/inode.go, metanode/partition.go, sdk/data/stream/extent_cache.go, storage/extent.go
snapshot.multiVersion's snapshot loading needs to be loaded before inode and detry because it depends on it
snapshot. need dp space manager lock protect during range in version commit
=> snapshot.multiVersion's snapshot loading needs to be loaded before inode and detry because it depends on it

master/cluster.go, master/cluster_task.go, master/config.go, master/meta_partition.go, master/vol.go
1. support max mp split when max mp is no leader.
2. modify lowerLimitRWMetaPartition to 3，which equal defaultReplicaNum when volume was created.
=> feat(master): support max mp split when max mp is no leader

client/fs/dir.go, client/fs/file.go, client/fs/super.go, cmd/cmd.go, fsck/cmd/clean.go, lcnode/lc_scanner.go, lcnode/meta.go, lcnode/meta_test.go, lcnode/snapshot_scanner.go, libsdk/libsdk.go, metanode/manager_op.go, metanode/multi_ver_test.go, metanode/partition.go, metanode/partition_op_dentry.go, metanode/partition_op_extent.go, metanode/partition_op_inode.go, metanode/partition_op_transaction.go, objectnode/fs_volume.go, proto/fs_proto.go, sdk/data/stream/extent_client.go, sdk/data/stream/stream_writer.go, sdk/meta/api.go, sdk/meta/operation.go, snapshot/cmd/clean.go, util/auditlog/auditlog.go, util/auditlog/auditlog_test.go, util/caps/caps.go
* Support metadata operations back-end audit log:
*  Inode write operations.
* Dentry write operations.
* Transaction commit and rollback.
* Snapshot tool doesn't support audit log full path.
* Rename `auditlog.FormatLog` to `auditlog.LogClientOp`, for distinguish back-end log from client log.
* Refactor `util/auditlog` and fix path bug.
* Add `util/auditlog.go` unit test.
**Test Command:**
```sh
$ mdtest -z 3 -b 4 -I 10
```
**Audit log in [here](https://github.com/NaturalSelect/logs/tree/main/cubefs/audit).**
```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs]
└─$ bash cp_audit.sh 
Create dentry count:
1787
Delete dentry count:
1786
Create inode count:
1787
Delete inode count:
1786
Create /out dentry:
2023-09-27 20:36:20 CST, 172.16.1.103:56186, ltptest, …
```
=> [Feature]: Support back-end audit log

blobstore/access/server.go
see more in cubefs advisories:
https://github.com/cubefs/cubefs/security/advisories/GHSA-8h2x-gr2c-c275
CubeFS leaks magic secret key when starting blobstore access service.
fixes # security/advisories/GHSA-8h2x-gr2c-c275
```release-note
```
=> fix(security): leaks magic secret key when starting blobstore access service

proto/packet.go, sdk/data/stream/stream_writer.go, util/string.go
refer fo [https://github.com/cubefs/cubefs/security/advisories/GHSA-4248-p65p-hcrm](https://github.com/cubefs/cubefs/security/advisories/GHSA-4248-p65p-hcrml)
function RandomString in util/string.go is insecure，for it is using pseudorandom generator and time stamp as random seed, this could allow an attacker to predict and/or guess the generated string.
shuold replace the pseudorandom  generator withTrue Random Number Generator.
fixes  #2696
=> [Enhancement]: Optimize insecure random number generation in function … util/string.go:RandomString

master/metadata_fsm.go, master/server.go
Bug: master applied data into closed rocksdb instance while shutting down, which caused panic.
close fsm.raftstore before closing rocksdb when master shutdown.
fixes #
```release-note
```
=> fix(master): close fsm.raftstore before closing rocksdb when master shutdown

datanode/partition.go, master/cluster.go
1.Apply will be initialized when new datapartition is created.
2.Only sync up metadate of datapartitons when the creation of the datapartitions fails in the decommission process.
=> fix(master,datanode):Initialize Apply file and add a check condition for dp rollback during dp creation

sdk/data/stream/stream_writer.go
to avoid connection leak: in function tryInitExtentHandlerByLastEk(), close old s.handler before assigning new instance
=> fix(client): to avoid connection leak: in function tryInitExtentHandlerByLastEk(), close old s.handler before assigning new instance

master/api_args_parse.go, master/api_service.go, master/api_service_test.go, master/cluster.go, master/cluster_test.go, master/gapi_volume.go, master/master_manager_test.go
refactor(master): For code readability and maintainability, rename field "size" of struct createVolReq to "dpSize"
=> refactor(master): For code readability and maintainability, rename field "size" of struct createVolReq to "dpSize"

cli/cmd/root.go, master/topology.go
panic when concurrent read/write decommissiondatapartition list
=> fix(master): panic when concurrent read/write map

cli/cmd/datapartition.go, datanode/data_partition_repair.go, datanode/partition.go, datanode/partition_raft.go, datanode/partition_raftfsm.go, datanode/wrap_operator.go, master/cluster.go, master/data_node.go, master/data_partition.go, master/data_partition_check.go, master/disk_manager.go, master/master_manager.go, master/meta_partition.go, master/metadata_fsm_op.go, master/topology.go, sdk/master/client.go, util/buf/bcache_pool_test.go
1.remove logic of fetching replica from master after adding raft member
2.cli show error msg when decommission failed 3.keep disk original decommission status when load from rocksdb
3. if no disk to decommission,datanode reset to initial 2. if dp reach max retry times, delete the added replica and add the source replica.
=> bugfix(datanode,cli,datanode): fix some logic for dp decommission

cli/cmd/disk.go, cli/cmd/fmt.go, datanode/disk.go, datanode/partition.go, datanode/server.go
refactor(data): optimize the determination of datanode disk's unavailable status:
(1) add 2 conf item: diskUnavailableErrorCount and diskUnavailablePartitionErrorCount. 
(2) when encounter disk error, set disk as unavailable if disk error count reaches diskUnavailableErrorCount or partition count with disk error reaches diskUnavailablePartitionErrorCount. 
(3) if a partition encounter 1 disk error, set the partition's status as unavailable.
=> refactor(data): optimize the determination of datanode disk's unavailable status:

objectnode/api_context.go, objectnode/api_handler.go, objectnode/api_middleware.go, objectnode/api_response.go, objectnode/audit.go, objectnode/audit_kafka.go, objectnode/audit_kafka_test.go, objectnode/audit_webhook.go, objectnode/audit_webhook_test.go, objectnode/auth.go, objectnode/const.go, objectnode/http_transport.go, objectnode/kafka.go, objectnode/result.go, objectnode/server.go, objectnode/util.go, objectnode/webhook.go, util/config/config.go, vendor/github.com/Shopify/sarama/mocks/README.md, vendor/github.com/Shopify/sarama/mocks/async_producer.go, vendor/github.com/Shopify/sarama/mocks/consumer.go, vendor/github.com/Shopify/sarama/mocks/mocks.go, vendor/github.com/Shopify/sarama/mocks/sync_producer.go
Add ObjectNode to support the audit log feature, mainly for two points:
1. Local file, write the information requested by the user into the local file.
2. External services, mainly Kafka and Webhook, parse the information requested by the user into a specific AuditEntry and then write it to the external service in the service configuration. This step may increase the time required for the user's request.
Local audit log：
```text
REQ	OBJECT	16977050372829952	PUT	/cfs-bucket/cfs-object-key.json	{"Accept-Encoding":"gzip","BodySize":20,"Content-Length":"20","Content-Type":"application/json","Host":"127.0.0.1:17410","IP":"127.0.0.1","User-Agent":"aws-sdk-go/1.45.3 (go1.17.13; linux; amd64)"}		0	{"Api":"PutObject","Connection":"keep-alive","ETag":"\"e9c6a6 …
```
=> feat(objectnode): support local and external audit log

datanode/server.go, metanode/manager.go, util/loadutil/cpu.go, util/loadutil/cpu_test.go
fix(util): check if err occurred when get CPU percent, to avoid panic if got nil result.
=> fix(util): check if err occurred when get CPU percent, to avoid panic if got nil result.

master/cluster.go, master/const.go, master/multi_ver_snapshot.go, master/vol.go, master/vol_test.go, metanode/inode.go, metanode/manager_op.go, metanode/multi_ver_test.go, metanode/partition.go, metanode/partition_op_extent.go
fix(client): An abnormal condition occurs when the metanode triggers clients to make verlist requests again.
update(master):disable print stack of mps lock for dead lock debug
fix(metanode):enable metanode ttl clear tempory snapshot
enhance(master): mp migrate need limit the parrallel count
=> enable metanode ttl clear tempory snapshot and some other issues

cli/cmd/fmt.go, cli/cmd/vol.go, master/api_service.go, master/api_service_test.go, master/cluster.go, master/http_server.go, master/metadata_fsm_op.go, master/mocktest/data_server.go, master/mocktest/meta_server.go, master/mocktest/partition.go, master/vol.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_op_dentry.go, metanode/partition_op_extent.go, metanode/partition_op_inode.go, metanode/partition_op_transaction.go, proto/admin_proto.go, sdk/master/api_admin.go
* Backend audit log support configure in master(per volume).
```sh
└─$ ./build/bin/cfs-cli volume -h
Manage cluster volumes
Usage:
cfs-cli volume [command]
Aliases:
volume, vol
Available Commands:
add-dp        Create and add more data partition to a volume
create        Create a new volume
delete        Delete a volume from cluster
expand        Expand capacity of a volume
info          Show volume information
list          List cluster volumes
set-auditlog  Enable/Disable backend audit log for volume
set-forbidden Set the forbidden property for volume
shrink        Shrink capacity of a volume
transfer      Transfer volume to another user. (Change owner of volume)
update        Update configuration of the volume
Flags:
-h, --help   help for volume …
```
=> [Feature]: Backend audit log support configure in master

blobstore/common/trace/span_context.go, blobstore/common/trace/span_test.go
```
goos: linux
goarch: amd64
pkg: github.com/cubefs/cubefs/blobstore/common/trace cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Benchmark_RandomID_RandLock
Benchmark_RandomID_RandLock-4           83533698                14.94 ns/op            0 B/op          0 allocs/op
Benchmark_RandomID_Maphash
Benchmark_RandomID_Maphash-4            194972664                5.965 ns/op           0 B/op          0 allocs/op
```
fixes #
```release-note
```
=> feat(trace): change trace id generator to maphash

sdk/meta/trash.go
trash supports random interval to prevent a large number of concurrent deletions
=> feature(client): trash use random delete interval 

datanode/wrap_operator.go, docker/conf/metanode.json, master/gapi_user.go, metanode/const.go, metanode/dentry.go, metanode/extend.go, metanode/manager.go, metanode/multi_ver_test.go, metanode/partition.go, metanode/partition_free_list.go, metanode/partition_fsm.go, metanode/partition_fsmop_dentry.go, metanode/partition_fsmop_inode.go, metanode/partition_item.go, proto/packet.go, sdk/data/stream/extent_cache.go, sdk/data/stream/extent_handler.go, sdk/data/stream/stream_writer.go
[fix(metanode):loadPartitions not check the result of calling master
fix(metanode):xattr read snapshot according verlist 
fix(metanode):add verlist to mp snapshot process 
enhance(client): reconstruct process of try init extentHandler by las… 
fix(metanode).inode with layer len large than 0 should be deleted 
fix(client): reuse the split key for streaming writes
fix(metanode):mmap concurrent access cause panic
=> fix(metanode/sdk): snapshot related bugs and enhancement

cli/cmd/vol.go, util/auditlog/auditlog.go
* Avoid `sync.Mutex` in `Audit`.
* Using `RLock` instead of `Lock`.
```release-note
```
=> [Fix]: Audit log performance problem

datanode/partition_op_by_raft.go, master/cluster.go, metanode/partition_fsmop_inode.go, sdk/data/stream/stream_writer.go
1.fix datanode raft snapshot exceed the limit #2302
2.Add leader change infomation when data/meta node not found in memory
3.link of inode count minus wrongly caused by code merge
4.ExtentHandler write may need serveral times and ek maybe nil before success
=> fixbug(datannode,master,client): fix server bugs

cmd/cmd.go, util/log/log.go, util/log/rotate.go
- unify 'rotate' and 'rolling' into 'rotate'
- **support config rotate size and head room**
fixes: #1909
It seems 'log automatically scrolls when there is not enough space' already has been implemented.
=> Support config rotate size and head room 

metanode/partition_free_list.go
fix log panic in function of deleteMarkedEBSInodes
=>  bugfix(metanode): fix log panic in function of deleteMarkedEBSInodes 

master/cluster.go, master/master_manager.go, master/node_selector.go
1.modify node selector log level 
2. only check decommission disk/data node when meta is ready
=> bugfix(master): check decommission disk/data node when meta is ready

master/filecheck.go, metanode/api_handler.go, metanode/dentry.go, metanode/inode.go, metanode/multi_ver_test.go, metanode/partition_fsmop_dentry.go, metanode/sorted_extents.go, sdk/data/stream/extent_cache.go
fix(metanode):append key in sequnce jugement didn't include extent id
fix(metanode):snapshot. dentry deletion on top layer with no snapshotlist then update toplayer to deletion and store version to list althrough no version in mp verlist
version of inode exist identify that it's snapshot version not do deletion  on this node, no matter mplist exist or not, because mpVerlist update while recive master's command of
version deletion,but real deletion may do deletion aysncronus and may not reach the inode, but user can do deletion on top layer at the same time.
=> fix some bugs about wrong deletion duiring snapshot deletion and modification

cli/cmd/const.go, cli/cmd/disk.go, datanode/disk.go, datanode/server_handler.go, datanode/space_manager.go, datanode/wrap_operator.go, master/cluster.go, master/data_node.go, master/topology.go, proto/admin_proto.go, sdk/master/api_admin.go
* Add a status `decommission` to `Disk`. 
* When we change `decommission`, we create/remove a `decommissionMark` file in `disk.Path`.
* If a disk is decommissioned, it will not shown in datanode `/disks` API.
* Master synchronous `DecommissionDisks` with datanode using `HearBeatRequest`.
* Cli support decommission disk.
* Cli support to recommission disk.
**Effects:**
_Before decommission:_
```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~]
└─$ curl -v "http://172.16.1.101:8080/disks"
*   Trying 172.16.1.101:8080...
* Connected to 172.16.1.101 (172.16.1.101) port 8080
> GET /disks HTTP/1.1
> Host: 172.16.1.101:8080
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sat, 25 Nov 2023 11:12:44 GMT
< Content-Length: 278
< Content-Type: text/plain; …
```
=> [Fix]: Decommissioned disk is still shown in datanode

master/api_args_parse.go, master/api_service.go
fix(master): In create volume procedure, sort allowedStorageClass after checking if append volStorageClass info it
=> fix(master): In create volume procedure, sort allowedStorageClass after checking if append volStorageClass info it

libsdk/libsdk.go
libsdk cfs_mkdirs return ENOENT when multi-thread called
fixes #
```release-note
```
=> fix(libsdk): fix cfs_mkdirs bug when multi-thread call

cli/cmd/fmt.go, cli/cmd/vol.go, client/fs/super.go, client/fuse.go, libsdk/libsdk.go, objectnode/fs_volume.go, preload/preload.go, preload/sdk/preloadsdk.go, proto/mount_options.go, sdk/data/stream/extent_client.go, sdk/data/wrapper/wrapper.go
bugfix(client):only clear dp when volume storage class is blobstore
=> bugfix(client):only clear dp when volume storage class is blobstore

master/node_selector.go, master/node_selector_test.go, master/nodeset_selector.go, master/nodeset_selector_test.go
* Straw2 is a selection algorithm which is widely used in Ceph.
* This pull request make cubefs support Straw2 algorithm.
**Effect:**
```log
=== RUN   TestBenchStrawNodeSelector
node_selector_test.go:237: Node 3 select times 38
Node 2 select times 31
Node 1 select times 21
Node 0 select times 10
node_selector_test.go:47: Data Node 0
Total Space:102400 MB
Avaliable Space:45254 MB
node_selector_test.go:47: Data Node 1
Total Space:204800 MB
Avaliable Space:95745 MB
node_selector_test.go:47: Data Node 2
Total Space:307200 MB
Avaliable Space:144415 MB
node_selector_test.go:47: Data Node 3
Total Space:409600 MB
Avaliable Space:218970 MB
node_selector_test.go:237: Node 1 select times 21
Node 2 select times 27
Node 3 select times 41
Node 0 select times 11 …
```
=> [Feature]: Master support Straw2 algorithm when select node and nodeset

datanode/partition.go, metanode/inode.go, metanode/manager_op.go, metanode/sorted_extents.go, proto/extent_key.go, sdk/data/stream/extent_cache.go, storage/extent_store.go
in append ek process,if do neigbor ek merge together of the same extent,the client may have different view of eks,
then the client opertion will not consistent with metanode,and may trigger conflicts.so just add ref for this scenrio,
because the verseq update not always happen
=> client append ek which seq may be updated by metanode,add ref for consistent

master/api_service.go
…t, not set usedSize as totalSize when usedSize > totalSize
fix(master)：fix the calculation of vol usedSize of API /client/volStat, not set usedSize as totalSize when usedSize > totalSize.
This will show the right used size for volumes whose usedSize is larger than totalSize
=> fix(master)：fix the calculation of vol usedSize of API /client/volStat, not set usedSize as totalSize when usedSize > totalSize

sdk/meta/view.go
fix(client): set usedSize as totalSize if usedSize > totalSize when queried from master, to avoid displaying anomalies such as cmd df
=> fix(client): set usedSize as totalSize if usedSize > totalSize when queried from master, to avoid displaying anomalies such as cmd df

client/fs/file.go, client/fs/super.go, client/fuse.go, libsdk/libsdk.go, metanode/forbidden_migration_list.go, metanode/inode.go, metanode/manager_op.go, metanode/partition.go, metanode/partition_fsmop_inode.go, metanode/partition_op_extent.go, metanode/partition_op_inode.go, metanode/partition_test.go, objectnode/fs_volume.go, preload/sdk/preloadsdk.go, proto/admin_proto.go, proto/fs_proto.go, sdk/data/blobstore/reader.go, sdk/data/stream/extent_client.go, sdk/data/stream/extent_handler.go, sdk/data/stream/stream_reader.go, sdk/data/stream/stream_writer.go, sdk/data/wrapper/wrapper.go
1.Simplify the logic of updating extent key after migration
2. reset inode reserved when excute marshall operation
3. initial ebs client in mp
4. remove cold vol or hot vol check in client and objectnode
=> enhance(metanode):fix some bugs about ssd to ebs migration

master/cluster.go, master/data_partition_map.go
… right after the creation of datapartitions
fix(master): in create vol procedure, update datapartition view cache right after the creation of datapartitions.
to void backgroud goroutine trigger datapartition view cache update while creating datapartition and cause the view cache imcomplete
=> fix(master): in create vol procedure, update datapartition view cache right after the creation of datapartitions

master/api_service.go
feat(master)：make the snapshot version an multiple allowedStorageClass mutually exclusive in a volume.
Because now multiple allowedStorageClass can not support snapshot version.
=> feat(master)：make the snapshot version an multiple allowedStorageClass mutually exclusive in a volume.

client/fuse.go, master/api_service_test.go, master/cluster.go, master/cluster_task.go, master/const.go, master/gapi_volume.go, master/monitor_metrics.go, master/vol.go, master/vol_test.go, proto/status.go
1. Exit the client when volume has been marked delete.
2. Use proto.VolStatusMarkDelete to substitute master.markDelete.
fixes #2940 
```release-note
```
=> feat(client): exit when volume has been marked delete

master/api_service.go, master/server.go
fix(master): amend the way judging if the volume has snapshot version, in update allowedStorageClass procedure.
=> fix(master): amend the way judging if the volume has snapshot version, in update allowedStorageClass procedure.

master/api_service.go
fix(master): [hybrid cloud] if vol.volStorageClass is blobStore, add allowedStorageClass if forbidden.
=> fix(master): [hybrid cloud] if vol.volStorageClass is blobStore, add allowedStorageClass if forbidden.

cli/cmd/fmt.go, master/api_service_test.go, master/config.go, master/master_manager.go, master/metadata_fsm_op.go, master/server.go, proto/admin_proto.go
feat(master): [hybrid cloud] handle compatibility of master when older version upgrade to hybrid cloud
(1) auto set mediaType of datanode, zone, datapartiton by config legacy "legacyDataMediaType" and persist; 
(2) auto set storageClass of volume by config legacy "legacyDataMediaType" and persist; 
(3) if need to rollback master to older version, need to do nothing, just replace to old master and restart. because hybrid cloud master only add new fields to meta by not changed old fields.
=> feat(master): [hybrid cloud] handle compatibility of master when older version upgrade to hybrid cloud

cli/cmd/const.go, cli/cmd/disk.go, cli/cmd/fmt.go, master/api_service.go, master/data_partition.go, proto/model.go, sdk/master/api_admin.go
* Support query decommission disk progress in cli.
**It looks like:**
```bash
root@nature-Lenovo-XiaoXinAir-14ALC-2021:/home/nature/Workspace/cubefs# ./build/bin/cfs-cli disk query-progress 172.16.1.101:17310 /home/nature/disk/data1/disk
Status:           Success
Progress:         100.00%
```
**Help message:**
```
nature@nature-Lenovo-XiaoXinAir-14ALC-2021:~/Workspace/cubefs$ ./build/bin/cfs-cli disk -h
Manage cluster disks
Usage:
cfs-cli disk [command]
Aliases:
disk, disk
Available Commands:
check          Check and list unhealthy disks
decommission   Decommission disk on datanode
query-progress Query decommmission progress on datanode
recommission   Recommission disk on datanode
Flags:
-h, --help   help for disk
Use "cfs-cli disk [command] --help" …
```
=> [Feature]: Support query disk decommission progress in cfs-cli

master/node_selector.go, metanode/const.go, metanode/inode.go, metanode/inode_test.go, metanode/metanode.go, metanode/partition.go, metanode/partition_fsm.go, metanode/partition_op_extent.go, metanode/partition_op_inode.go, metanode/transaction_test.go, proto/admin_proto.go
feat(meta): [hybrid cloud] handle compatibility when old version client send createInode request without field StorageClass
=> feat(meta): [hybrid cloud] handle compatibility when old version client send createInode request without field StorageClass

sdk/data/stream/extent_client.go
not check result of InodeGet_ll leadto panic in Truncate
fixes #
```release-note
```
=> fix(sdk): not check result of InodeGet_ll leadto panic in Truncate.

metanode/partition_op_inode.go, proto/packet.go
Copy WriteGeneration and ForbiddenMigration when getting inode from btree
=> bugfix(metanode):Copy WriteGeneration and ForbiddenMigration when

metanode/manager_op.go, metanode/partition_fsmop_inode.go, metanode/partition_op_extent.go, proto/fs_proto.go
copy storage class from HybridCouldExtentsMigration of inode when excuting migration
=> bugfix(metanode): copy storage class from HybridCouldExtentsMigration of inode when excuting migration

master/cluster.go
to debug length of dp.Replicas equals to 0
=> debug(master): to debug length of dp.Replicas equals to 0

blockcache/cmd.go, cli/cli.go, cli/cmd/cluster.go, cli/cmd/fmt.go, client/fuse.go, cmd/cmd.go, fsck/cmd/clean.go, fsck/main.go, libsdk/libsdk.go, master/api_service.go, master/api_service_test.go, master/vol_test.go, metanode/manager_op.go, metanode/transaction_test.go, preload/sdk/preloadsdk.go, proto/errors.go, util/log/log.go, util/log/log_test.go, util/log/rotate.go
Modifying Volume Deletion Related Error Messages and modify the threshold for triggering log cleanup to logLeftSpaceLimitRatio of the total disk space.
fixes #
```release-note
```
=> enhance(cli):Modifying Volume Deletion Related Error Messages.

master/master_manager.go, master/server.go
amend that server.user.clearUserStore() may be invoked before server.user is initialized, in func handleLeaderChange(), to avoid panic
=> amend that server.user.clearUserStore() may be invoked before server.user is initialized, in func handleLeaderChange(), to avoid panic

sdk/data/stream/extent_cache.go, sdk/data/stream/extent_client.go, sdk/data/stream/extent_handler.go, sdk/data/stream/stream_writer.go
…k reentrancy and other lock concurrency
During the truncate process, the extent cache is forcefully refreshed, but it does not have any effect
=> During the truncate process, the extent cache is forcefully refreshed, but it does not have any effect

master/api_args_parse.go, master/api_service.go
support specify count for datanode decomission
=> feature(master): support specify count for datanode decomission

client/fs/super.go, client/fuse.go, master/vol.go, metanode/partition.go, proto/admin_proto.go
fix(master): When updating a volume, ebsBlockSize can be modified if allowedStorageClass contains blobstore.
=> fix(master): When updating a volume, ebsBlockSize can be modified if allowedStorageClass contains blobstore.

datanode/data_partition_repair.go
calculate crc repeatedly in streamRepairExtent，it is not necessary.
fixes #
```release-note
```
=> fix(datanode): remove repeated crc

datanode/wrap_operator.go
Cancel the limit of "maxCount + 10" extents to avoid no available data partitions.
It maybe helpful for issue #3013
```release-note
```
=> fix(data): cancel extent count limit when create extent.

README.md, master/multi_ver_snapshot.go, sdk/data/stream/extent_handler.go
When processing the return from the datanode, if the sequence changes and the extent key is no longer consecutive,
the key inside the extent handler needs to be initialized.The current initialization only changes the file offset and nothing else,
which actually pollutes the extent cache and leads to anomalies in subsequent modifications based on this cache information.
=> fix(client):  snapshot issue trigger by version update && update docs

blobstore/access/controller/allocator_mock_test.go, blobstore/access/controller/cluster.go, blobstore/access/controller/cluster_test.go, blobstore/access/controller/mock_test.go, blobstore/access/controller/volumemgr.go, blobstore/access/controller/volumemgr_test.go, blobstore/access/controller_mock_test.go, blobstore/access/stream_alloc.go, blobstore/access/stream_alloc_test.go, blobstore/access/stream_loop.go, blobstore/access/stream_mock_test.go, blobstore/access/stream_put_test.go, blobstore/api/clustermgr/volume.go
…cess instead proxy
In order to reduce the number of blobstore components, this PR will transplant the volume allocation and retain functions in proxy to access, and adapt the original logic
fixes #
```release-note
```
=> feat(access): add volume allocation and lease retain functions for access

docker/run_docker.sh
* It looks like the output of `go env` is different between 1.21 and 1.18.
```release-note
```
=> chore(build): fix go 1.21 build cache

blobstore/access/controller/cluster_test.go, blobstore/access/controller/service_test.go, blobstore/blobnode/config.go, blobstore/blobnode/datainspect.go, blobstore/blobnode/datainspect_test.go
Blobnode is slow to inspect large-capacity disks and needs to save the current inspection progress through checkpoint.
fixes #
```release-note
```
=> feat(blobnode): add checkpoint for inspectmgr of blobnode

blobstore/blobnode/base/qos/config.go, blobstore/blobnode/base/qos/qos.go, blobstore/blobnode/base/qos/qos_test.go, blobstore/blobnode/config.go, blobstore/blobnode/datainspect.go, blobstore/blobnode/service.go, blobstore/blobnode/svr_test.go, blobstore/common/proto/proxy.go, blobstore/scheduler/blob_deleter.go
merge blobstore-v1.2.4 feature branch to master
1. fix reload config data qos. panic when conf normal mbps is zero
2. fix blobnode datainspect switch
3. fix scheduler roll back to init stage, when err is shard not mark delete 653
fixes #
```release-note
```
=> fix(blobnode): reload config data qos. panic when conf normal mbps is zero

cmd/cmd.go, util/errors/panichook.go, util/errors/panichook_test.go
* Support hook `panic`.
* Flush log before crash(support by hook).
fixes #1910 
```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs]
└─$ ./build/bin/cfs-server -f -c ~/disk/conf/data1.conf 
panic: I'm panic
goroutine 71 [running]:
github.com/cubefs/cubefs/util/errors.hookedPanic({0x16d6a40, 0x1eec3f0})
util/errors/panichook.go:38 +0x77
main.main.func2()
cmd/cmd.go:251 +0x3f
created by main.main
cmd/cmd.go:248 +0xd59
┌──(nature㉿LAPTOP-9TS0FG11)-[~/cubefs]
└─$ cat ~/disk/data1/logs/dataNode/dataNode_error.log 
2023/12/10 00:06:26.961475 [ERROR] cmd.go:250: You should see me in log file
```
**cmd.go:**
```go
func main() {
flag.Parse()
Version := proto.DumpVersion("Server")
if *configVersion { …
```
=> feat(util): Log flush output before crash

blobstore/access/stream.go, blobstore/access/stream_alloc.go, blobstore/access/stream_put.go
1. mark sealed volume, when access stream wirte failed
fixes #
I will merge multiple commits when the code view passes
```release-note
```
=> feat(access):  mark sealed volume when write failed. for blobstore-v1.3.0 feature branch

blobstore/blobnode/datainspect.go, blobstore/blobnode/datainspect_test.go
the blobnode inspection process creates a multi-level file directory, the directory requires execution permissions
fixes #
```release-note
```
=> fix(blobnode): fix checkpoint file permission for inspectmgr of blobnode

docs-zh/source/quick-start/node.md, docs/source/quick-start/node.md, shell/deploy.sh, shell/deploy_client.sh, shell/deploy_object.sh, shell/genConf.sh, shell/tpl/data.tpl, shell/tpl/meta.tpl, shell/tpl/object.tpl
fix typo: `depoly.sh` -> `deploy.sh`
support deploy client and object in Standalone Mode
```bash
cd ./cubefs
make
sh ./shell/deploy.sh /home/data bond0
sh ./shell/deploy_client.sh /home/data
sh ./shell/deploy_object.sh /home/data
```
=> feat(shell): support deploy client and object in Standalone Mode

lcnode/lc_scanner.go, lcnode/meta.go, lcnode/meta_test.go, metanode/partition_fsmop_inode.go, proto/lifecycle.go
DeleteMigrationExtentKey before migration
=> fix(lcnode): [hybrid cloud] DeleteMigrationExtentKey before migration

master/lifecycle_manager.go, master/server.go
try avoid segmentation when close service.
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x139877f]
runtime stack:
runtime.throw({0x18df1b9, 0x7f23ff7fe580})
/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:719 +0x389
goroutine 220 [syscall]:
runtime.cgocall(0x130b969, 0xc00b12db58)
/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00b12db30 sp=0xc00b12daf8 pc=0x4f4f1c
github.com/tecbot/gorocksdb._Cfunc_rocksdb_write(0x7f246001ced0, 0x7f23f03a5b80, 0x7f23f04f3f30, 0xc00b80f488)
/tmp/go-build1895915678/b329/_cgo_gotypes.go:4798 +0x45 fp=0xc00b12db58 sp=0xc00b12db30 pc=0x1157665
github.com/tecbot/gorocksdb.(*DB).Write.func1(0x7f23f04f3f30, …
=> fix(master): try sleep a second before close rocksdb to segmentation error.

metanode/partition_fsmop_inode.go
function
Correct the type conversion error for logCurrentExtentKeys function
=> fix(metanode):Correct the type conversion error for logCurrentExtentKeys

cli/cmd/const.go, cli/cmd/datapartition.go, datanode/partition.go, datanode/wrap_operator.go, docs-zh/source/tools/cfs-cli/datapartition.md, docs/source/tools/cfs-cli/datapartition.md, master/api_service.go, metanode/datapartition.go, metanode/partition_delete_extents.go, metanode/partition_free_list.go, repl/packet.go, repl/repl_protocol.go, sdk/master/api_admin.go, storage/extent_store.go
* Datanode return an error when failed to mark delete extent.
* Metanode skip extent deletion when all replicas of dp is broken.
* Cli support to set datapartition discard flag.
**Effect:**
```log
2024/01/25 19:59:44.309168 [WARN ] partition_delete_extents.go:352: action[deleteExtentsFromList] dp(10) is discard, skip extent(1025)
2024/01/25 19:59:44.309172 [WARN ] partition_delete_extents.go:352: action[deleteExtentsFromList] dp(9) is discard, skip extent(1025)
```
```log
nature@PS9054862:~/cubefs$ ./build/bin/cfs-cli datapartition set-discard -h
Set discard flag for data partition
Usage:
cfs-cli datapartition set-discard [DATA PARTITION ID] [DISCARD] [flags]
Flags:
-h, --help   help for set-discard
```
**Special notes …
=> feat(meta): skip extent deletion if all replicas of dp is discard

authtool/authtool.go, depends/bazil.org/fuse/fs/serve.go, depends/tiglabs/raft/proto/proto.go, depends/tiglabs/raft/raft.go, depends/tiglabs/raft/util/io.go, deploy/cmd/cluster.go, fdstore/fdstore.go, fsck/cmd/getInfo.go, raftstore/partition.go, sdk/data/manager/limiter.go, sdk/data/wrapper/wrapper.go, util/smux_conn_pool.go
- remove redundant 'return' state
- simplify conditional expressions
- remove ineffectual assignment
- 'fdstore.go, line 280' It will not be referenced again in the 'for' loop it belongs to, and will then be overwritten with a new value in the 'os.OpenFile()' function.
- 'fdstore.go, line 303' Handling of the 'fmt.Errorf()' function ends without processing
- 'io.gok line 114' slice is initialized automatically, and since it is not a pointer, it does not use nil.
- 'flag.go, line 740' This could directly return the return value of 'fmt.Errorf()' (actually it doesn't seem necessary, but I can't figure out the intent, so it preserves the meaning of the code)
- 'serve.go, line 1840' It is continuously initialized within the for loop and will not be …
=> feat(master): minor code and comment refactoring

docker/docker-compose.yml
double '<<' isn't allowed to new version of docker-compose, change to the new form.
fix #3100 
```release-note
```
=> fix(docker): fix docker-compose yml #3100

util/auditlog/auditlog.go, util/auditlog/auditlog_test.go
fixes #3178
```release-note
```
=> fix(util): recycle audit logs when rolling

client/fs/dir.go, metanode/partition_free_list.go
remove duplicated logs for deleteMarkedInodes
=> fix(client,metanode): remove duplicated logs for deleteMarkedInodes

libsdk/libsdk.go
fix(libsdk): cfs_close dir print error stream is not opened yet
fixes #
```release-note
```
=> fix(libsdk): cfs_close dir print error stream is not opened yet

GOVERNANCE.md
In our past community operations, we adhered to vendor neutrality and established a steering committee. We frequently discussed matters through WeChat; however, these discussions were not formally incorporated into the governance documentation.
Clarify steering committee responsibilities, supplementary vendor neutral instructions, etc.
=> feat(doc): Update the Governance Document

ROADMAP.md
``` text
Update the document of Roadmap to enhance readability and include potential job responsibilities
```
*(or)*
*(or)*
*(example:)*
*(or)*
=> feat(doc): "Update the document of the roadmap to improve readability and include features that are in preparation but not yet scheduled.

MAINTAINERS.md
Fixes: no
Main Issue: no
I contributed a lot of code to the CubeFS. I want to add myself(Chuanqing Zhang) as a committer to do more things.
In the future, I would first like to see the project code improve stability and security by continuously optimizing legacy issues. Then I will consider improving its performance and scalability, for example by providing support for rdma to improve communication performance, by providing support bitmap ino allocator, by providing support rocksdb instead btree in metanode.
rocksdb branch:https://github.com/cubefs/cubefs/tree/metanode_rocksdb (This branch has already been merged into the rocksdb development branch : https://github.com/cubefs/cubefs/tree/metanode_rocksdb_dev)
raft rdma branch:https://github.com/cubefs/cubefs/tree/online_0701_verbs_server …
=> feat(doc): Add Chuanqing Zhang to be a committer.

cmd/common/args.go, cmd/common/argument.go, cmd/common/argument_test.go, datanode/server_handler.go, metanode/api_handler.go
Parse http argument in common package.
``` go
var id Int
var name String
ParseArguments(r, id.ID().
OnEmpty(func() error { return errors.New("not found id") }).
OnError(func() error { return errors.New("parse id failed") }).
OnValue(func() error { return nil }),
name.Key("name"),
)
```
=> feat(common): add http argument parser

sdk/meta/meta.go
close: #3416
Fixes: #3416
I use the [mdtest with CubeFS backend support](https://github.com/yuangcao/ior/blob/main/src/aiori-CUBEFS.c) to measure the throughput of CubeFS meta subsystem. Each mdtest process will create its own CubeFS client with the MetaWrapper having the same epoch.
Each mdtest process creates the same directory tree (one dir contains millions of files). In this situation, all mdtest processes will create their root dir inode in the same meta partition, because all the mdtest processes' CubeFS client have the same epoch. Then all the files' dentry will be created in the same meta partition, which will cause significant performance degradation.
``` text
In the NewMetaWrapper function, I assign a random value to the mw.epoch. The value is in the range of [0, …
```
=> fix(sdk): NewMetaWrapper initializes the epoch with a random number.

util/btree/btree.go, util/btree/btree_test.go
Fixes:  remove item may changed clone btree; (i+1) children has new cow but do not copy
bug flow
new btree t1
clone btree t2
remove item and need merge i + 1 children.
now, i + 1 children has new cow, but no copy;
t1 modiyf i + 1 children item, t2 follow modify (bug happen).
fix:
when merge i + 1 children, copy it
This change added unit tests
=> fix(metanode): remove item may changed clone btree

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [CubeFS Guru](https://gurubase.io/g/cubefs) to Gurubase. CubeFS Guru uses the data from this repo and data from the [docs](https://cubefs.io/) to answer questions by leveraging the LLM.
In this PR, I showcased the "CubeFS Guru", which highlights that CubeFS now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable …
=> Introducing CubeFS Guru on Gurubase.io

depends/tiglabs/raft/raft.go
Fixes: raft
when using readIndex, it was found that 'apply' is not return poll and unexpected situations may occur in concurrent situations
=> fix(raft): fix apply not return pool.

build/build.sh
fix(othertools): java libcubefs compilation failure caused by path errors
Fixes: #Fix the issue of Java libcubefs compilation failure caused by path errors
Main Issue: # java libcubefs，build failure
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.089 s
[INFO] Finished at: 2025-01-03T10:22:28+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root/GoProject/src/cubefs_metaapp/client/java). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack …
```
=> fix(othertools): java libcubefs compilation failure caused by path errors

depends/tiglabs/raft/raft.go
Fixes: 
Main Issue: 
When readIndex is supported, if committedEntries is equal to 0 and readIndexs is not 0, an apply will be obtained from the pool, but the index is not set, which may cause the index to be greater than curApplied, resulting in data loss.
``` text
Added readindex applied
```
*(or)*
*(or)*
*(example:)*
*(or)*
=> fix(raft): fix readIndex not set index.

blobstore/util/retry/retry.go, blobstore/util/retry/retry_test.go, docker/run_docker.sh
Fixes: #3758
try to wait with context in retry
``` text
cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
BenchmarkWait
BenchmarkWait/success
BenchmarkWait/success-4     432140625    2.793 ns/op    0 B/op  0 allocs/op
BenchmarkWait/retry-3
BenchmarkWait/retry-3-4      97395789   12.27 ns/op     0 B/op  0 allocs/op
BenchmarkContext
BenchmarkContext/success
BenchmarkContext/success-4  449174043    2.641 ns/op    0 B/op  0 allocs/op
BenchmarkContext/retry-3
BenchmarkContext/retry-3-4    3177039  380.2 ns/op    232 B/op  3 allocs/op
```
=> feat(util): try to wait with context in retry

cli/cmd/metanode.go, master/api_service.go, master/cluster.go, master/const.go, util/unit.go
Fixes: #xyz
migrate metanode with cli cmd can not work
changed by this PR
[enhance(master): mp migrate need limit the parrallel count](https://github.com/cubefs/cubefs/pull/2752/commits/c137a273d9595ef200c65ef246860f33e25f24b6)
``` text
I think we can do the following modifications:
1、migrate metanode cli set default mp count with 0 but not maxMpCount
2、remove the check for limit value as it is specified by the user 
and the cli command will detect that this value does not exceed 15
```
*(or)*
*(or)*
*(example:)*
- *This can be verified in development …
=> fix(cli): migrate metanode cmd cannot work with default limit mp count

blobstore/util/bytespool/pool.go, blobstore/util/bytespool/pool_test.go
Fixes: #3786
``` text
pkg: github.com/cubefs/cubefs/blobstore/util/bytespool cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
BenchmarkBytespoolSlice
BenchmarkBytespoolSlice-4        23023845    50.60 ns/op   29 B/op    1 allocs/op
BenchmarkBytespoolPointer
BenchmarkBytespoolPointer-4    60203656    18.60 ns/op    0 B/op    0 allocs/op
```
=> perf(util): store pointer of bytes in bytespool

blobstore/scheduler/blob_deleter.go
during period blobnode chunk compact, delete ops are not allowed, so scheduler bloc_deleter will receive a large number of `chunk is compacting` error logs when MarkDelete/Delete. to reduce log pressure, this entry is adjusted to Warn
```
279993
```
```
2025/04/23 08:41:22.542143 [ERROR] blobstore/scheduler/blob_deleter.go:591 [1e69fa05b5d395f5_e04746940db4553d:30d2094277d60c7f] delete shard failed: bid[180098383], vuid[14894946582529], markDelete[true], code[628], err[chunk is compacting]
2025/04/23 08:41:22.838751 [ERROR] blobstore/scheduler/blob_deleter.go:591 [5405a4333d51fb12_310ee8c5723b95d2:434dbed670e6c4fe] delete shard failed: bid[180605782], vuid[14890685169665], markDelete[true], code[628], err[chunk is compacting]
2025/04/23 08:41:22.958848 [ERROR] …
```
=> fix(scheduler): adjust log levels to reduce unnecessary log output for blob_deleter

blobstore/cmd/cmd.go, blobstore/sdk/sdk_client.go, blobstore/sdk/sdk_client_test.go
This commit adds support for logging to a file in the blobstore sdk client,
allowing configuration of log file path, level, and size.
close: #3862
Signed-off-by: yanghonggang <yanghonggang_yewu@cmss.chinamobile.com>
Signed-off-by: zhangjianwei2 <zhangjianwei2_yewu@cmss.chinamobile.com>
=> feat(bssdk): support log file configuration for sdk client
